import Link from "next/link";

import { AdminCard, AdminGrid, AdminPageContainer, AdminPageHeader, AdminStatCard } from "@/components/admin/ui";
import { getAdminLanguage } from "@/lib/admin/i18n";
import { requireAdminAccess } from "@/lib/auth/require-admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { createMarketingCampaignAction } from "./actions";

export const dynamic = "force-dynamic";
type PageProps = { searchParams: Promise<{ lang?: string }> };
function statusLabel(value:string,ar:boolean){const m:Record<string,[string,string]>={draft:["مسودة","Draft"],pending:["بانتظار الاعتماد","Pending approval"],approved:["معتمدة","Approved"],active:["نشطة","Active"],paused:["متوقفة مؤقتًا","Paused"],completed:["مكتملة","Completed"]};return m[value]?.[ar?0:1]??value;}
function ownerLabel(value:string|null){return value?value.charAt(0).toUpperCase()+value.slice(1):"—";}

export default async function CampaignsPage({searchParams}:PageProps){
  await requireAdminAccess();
  const {lang}=await searchParams;
  const language=getAdminLanguage(lang);
  const isArabic=language==="ar";
  const db=createAdminClient();
  const {data,error}=await db.from("marketing_campaigns").select("id,name,objective,status,start_at,end_at,budget,channels,owner,utm_campaign,created_at").order("created_at",{ascending:false}).limit(100);
  const campaigns=data??[];
  const active=campaigns.filter(i=>i.status==="active").length;
  const awaiting=campaigns.filter(i=>["draft","pending"].includes(i.status)).length;
  const zeroBudget=campaigns.filter(i=>Number(i.budget??0)===0).length;
  return <AdminPageContainer>
    <AdminPageHeader title={isArabic?"الحملات":"Campaigns"} description={isArabic?"من التخطيط إلى الاعتماد ثم التفعيل والقياس. كل حملة الآن لها مساحة عمل مستقلة بدل أن تبقى بطاقة عرض فقط.":"Plan, approve, activate and measure campaigns. Every campaign now has its own operational workspace."}/>
    <AdminGrid className="mb-6 md:grid-cols-3"><AdminStatCard label={isArabic?"حملات نشطة":"Active campaigns"} value={active}/><AdminStatCard label={isArabic?"قيد التجهيز":"In preparation"} value={awaiting}/><AdminStatCard label={isArabic?"Zero-Budget":"Zero-budget"} value={zeroBudget}/></AdminGrid>
    <AdminCard className="mb-6 p-5"><div className="mb-4"><p className="text-sm font-medium text-white">{isArabic?"إنشاء حملة جديدة":"Create a campaign"}</p><p className="mt-1 text-xs text-white/35">{isArabic?"حدد الهدف والقنوات والميزانية. ستبدأ الحملة كمسودة ولن يتم أي نشر تلقائي.":"Set the objective, channels and budget. The campaign starts as a draft with no automatic publishing."}</p></div><form action={createMarketingCampaignAction} className="grid gap-3 lg:grid-cols-3"><input name="name" required placeholder={isArabic?"اسم الحملة":"Campaign name"} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="objective" placeholder={isArabic?"الهدف التجاري أو التسويقي":"Marketing objective"} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="goal" placeholder={isArabic?"النتيجة المستهدفة":"Target outcome"} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="channels" placeholder={isArabic?"القنوات: instagram, facebook...":"Channels: instagram, facebook..."} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><select name="owner" defaultValue="nora" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"><option value="nora">Nora</option><option value="reem">Reem</option><option value="faisal">Faisal</option><option value="ceo">CEO</option></select><input name="budget" type="number" min="0" step="0.01" placeholder={isArabic?"الميزانية — 0 لحملة عضوية":"Budget — 0 for organic"} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="start_at" type="datetime-local" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="end_at" type="datetime-local" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><input name="utm_campaign" placeholder="UTM campaign" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><button className="rounded-xl bg-gold px-4 py-2 text-sm font-medium text-black lg:col-span-3">{isArabic?"إنشاء المسودة وطلب الاعتماد":"Create draft & request approval"}</button></form></AdminCard>
    {error?<AdminCard className="mb-5 p-5 text-sm text-amber-200">{isArabic?"تعذر تحميل بيانات الحملات.":"Campaign data is unavailable."}</AdminCard>:null}
    <div className="grid gap-4">{campaigns.length===0?<AdminCard className="p-6"><p className="text-sm text-white/60">{isArabic?"لا توجد حملات بعد.":"No campaigns yet."}</p></AdminCard>:campaigns.map(item=><AdminCard key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/admin/marketing/campaigns/${item.id}?lang=${language}`} className="text-base font-medium text-white hover:text-gold">{item.name}</Link><div className="mt-1 text-sm text-white/45">{item.objective??(isArabic?"بدون هدف موثق":"No objective recorded")}</div></div><div className="flex items-center gap-2"><span className="rounded-full border border-gold/15 bg-gold/[0.05] px-3 py-1 text-xs text-gold">{statusLabel(item.status,isArabic)}</span><Link href={`/admin/marketing/campaigns/${item.id}?lang=${language}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/55 hover:border-gold/25 hover:text-gold">{isArabic?"فتح الحملة":"Open campaign"}</Link></div></div><div className="mt-5 grid gap-3 text-xs sm:grid-cols-4"><div className="rounded-xl border border-white/[0.07] p-3"><p className="text-white/30">{isArabic?"المالك":"Owner"}</p><p className="mt-1 text-white/70">{ownerLabel(item.owner)}</p></div><div className="rounded-xl border border-white/[0.07] p-3"><p className="text-white/30">{isArabic?"القنوات":"Channels"}</p><p className="mt-1 text-white/70">{(item.channels??[]).join(" · ")||"—"}</p></div><div className="rounded-xl border border-white/[0.07] p-3"><p className="text-white/30">{isArabic?"الميزانية":"Budget"}</p><p className="mt-1 text-white/70">{Number(item.budget??0)===0?(isArabic?"عضوية / 0":"Organic / 0"):item.budget}</p></div><div className="rounded-xl border border-white/[0.07] p-3"><p className="text-white/30">{isArabic?"التتبع":"Tracking"}</p><p className="mt-1 text-white/70">{item.utm_campaign||"—"}</p></div></div></AdminCard>)}</div>
  </AdminPageContainer>;
}
