export const EVENT_TARGETS = {
  ADMIN: "admin",
  TALENT: "talent",
  PUBLISHER: "publisher",
  AUTH_USER: "auth_user",
  OPPORTUNITY: "opportunity",
  APPLICATION: "application",
  CLAIM_REQUEST: "claim_request",
  SUPPORT: "support",
  MESSAGE: "message",
  CONVERSATION: "conversation",
  CASTING_PROJECT: "casting_project",
  PAYMENT: "payment",
  ENTITLEMENT: "entitlement",
  NOTIFICATION: "notification",
  SCENE_ARTICLE: "scene_article",
  CASTING_FILE: "casting_file",
  MANAGED_CASTING_INVITATION: "managed_casting_invitation",
  CASTING_ROLE: "casting_role",
  CASTING_SHORTLIST: "casting_shortlist",
  BOOKING: "booking",
  CASTING_REPLACEMENT: "casting_replacement",
  INVESTOR: "investor",
  INVESTOR_OUTREACH: "investor_outreach",
  INTEGRATION: "integration",
  VERIFICATION_PROOF: "verification_proof",
} as const;
  
  export type EventTarget =
    (typeof EVENT_TARGETS)[keyof typeof EVENT_TARGETS];