import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, useLocalSearchParams } from "expo-router";
import { ChevronLeft, ChevronRight, LockKeyhole, Send, Wifi } from "lucide-react-native";

import { ScreenSkeleton } from "@/components/ScreenSkeleton";
import { getConversation, sendMessage, type ConversationDetailResponse, type MobileMessage } from "@/lib/api";
import { getCurrentUserId, markConversationRead, subscribeToConversationMessages } from "@/lib/chat";
import { formatRelativeTime, isRtlLocale } from "@/lib/i18n";
import { useAppLocale } from "@/lib/locale-context";
import { darkTheme } from "@/lib/theme";

type ConversationPolicy = ConversationDetailResponse["conversation"] & { participantRole?: "talent" | "publisher"; startPolicy?: "publisher_starts"; canSend?: boolean };

export default function ConversationScreen(){
  const params=useLocalSearchParams<{id?:string|string[]}>();const conversationId=Array.isArray(params.id)?params.id[0]:params.id;
  const {locale}=useAppLocale();const ar=locale==="ar",rtl=isRtlLocale(locale),Back=rtl?ChevronRight:ChevronLeft;
  const listRef=useRef<FlatList<MobileMessage>>(null);
  const [data,setData]=useState<ConversationDetailResponse|null>(null),[loading,setLoading]=useState(true),[draft,setDraft]=useState(""),[sending,setSending]=useState(false),[error,setError]=useState<string|null>(null),[live,setLive]=useState(false);
  const append=useCallback((message:MobileMessage)=>{setData((current)=>!current||current.messages.some((x)=>String(x.id)===String(message.id))?current:{...current,messages:[...current.messages,message]});requestAnimationFrame(()=>listRef.current?.scrollToEnd({animated:true}));},[]);
  const load=useCallback(async()=>{if(!conversationId){setError(ar?"تعذر تحديد المحادثة.":"Unable to identify the conversation.");setLoading(false);return;}setLoading(true);setError(null);try{const result=await getConversation(conversationId);if(!result)setError(ar?"هذه المحادثة غير متاحة لهذا الحساب.":"This conversation is unavailable for this account.");else{setData(result);void markConversationRead(conversationId);}}catch{setError(ar?"تعذر فتح المحادثة. تحقق من الاتصال وحاول مرة أخرى.":"Unable to open the conversation. Check your connection and try again.");}finally{setLoading(false);}},[ar,conversationId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!conversationId)return;let cleanup:(()=>void)|undefined;let active=true;void getCurrentUserId().then((id)=>{if(!active||!id)return;cleanup=subscribeToConversationMessages({conversationId,currentUserId:id,onMessage:(message)=>{append(message);if(!message.isMine)void markConversationRead(conversationId);}});if(active)setLive(true);});return()=>{active=false;setLive(false);cleanup?.();};},[append,conversationId]);

  async function submit(){const body=draft.trim();if(!conversationId||!body||sending)return;setSending(true);setError(null);try{const result=await sendMessage(conversationId,body);if(result.ok){setDraft("");append(result.message);}else{const map:Record<string,{ar:string;en:string}>={EMPTY_MESSAGE:{ar:"اكتب رسالة قبل الإرسال.",en:"Write a message before sending."},MESSAGE_TOO_LONG:{ar:"الرسالة طويلة جدًا. الحد الأقصى 4000 حرف.",en:"The message is too long. Maximum 4,000 characters."},CONVERSATION_NOT_ACTIVE:{ar:"هذه المحادثة مغلقة حاليًا.",en:"This conversation is currently closed."},PUBLISHER_MUST_START:{ar:"ينتظر بدء الناشر للمحادثة وفق سياسة ملامح.",en:"Waiting for the publisher to start this conversation under MLAMH policy."},NOT_FOUND:{ar:"المحادثة غير متاحة لهذا الحساب.",en:"This conversation is not available for this account."},UNAUTHENTICATED:{ar:"انتهت جلسة الدخول. سجّل الدخول للمتابعة.",en:"Your session expired. Sign in to continue."},REQUEST_FAILED:{ar:"تعذر إرسال الرسالة بسبب الاتصال.",en:"The message could not be sent because of a connection problem."}};setError((map[result.code]??{ar:"تعذر إرسال الرسالة.",en:"Unable to send the message."})[locale]);}}catch{setError(ar?"تعذر إرسال الرسالة. حاول مرة أخرى.":"Unable to send the message. Try again.");}finally{setSending(false);}}
  if(loading)return <ScreenSkeleton variant="detail" locale={locale} label={ar?"جارٍ تحميل المحادثة":"Loading conversation"}/>;
  if(!data)return <SafeAreaView style={s.center} edges={["top","bottom"]}><Text style={s.centerError}>{error}</Text><Pressable onPress={()=>void load()} style={s.secondary}><Text style={s.secondaryText}>{ar?"إعادة المحاولة":"Try again"}</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.backText}>{ar?"رجوع":"Back"}</Text></Pressable></SafeAreaView>;

  const policy=data.conversation as ConversationPolicy;
  const publisherStarts=policy.startPolicy==="publisher_starts"||policy.participantRole==="talent"&&data.messages.length===0;
  const canSend=policy.canSend??(data.conversation.status==="active"&&!(policy.participantRole==="talent"&&data.messages.length===0));
  const emptyText=policy.participantRole==="talent"&&publisherStarts?(ar?"تم الاختيار. تنتظر الآن رسالة الناشر الأولى، وبعدها يصبح التواصل متاحًا للطرفين.":"You were selected. The publisher sends the first message, then messaging is open to both sides."):(ar?"المحادثة جاهزة. ابدأ برسالة واضحة مرتبطة بالفرصة.":"The conversation is ready. Start with a clear message tied to the opportunity.");

  return <SafeAreaView style={s.screen} edges={["top","bottom"]}><KeyboardAvoidingView style={s.screen} behavior={Platform.OS==="ios"?"padding":undefined}>
    <View style={[s.header,rtl&&s.rowRtl]}><Pressable onPress={()=>router.back()} style={s.backButton}><Back size={22} color={darkTheme.text}/></Pressable><View style={s.avatar}><Text style={s.avatarText}>{data.conversation.partyName.slice(0,1).toUpperCase()}</Text></View><View style={s.headerCopy}><Text numberOfLines={1} style={[s.party,txt(rtl)]}>{data.conversation.partyName}</Text><Text numberOfLines={1} style={[s.context,txt(rtl)]}>{data.conversation.opportunityTitle??(ar?"محادثة ملامح":"MLAMH conversation")}</Text></View><View style={[s.live,!live&&s.syncing]}><Wifi size={11} color={live?darkTheme.accent:darkTheme.muted}/><Text style={[s.liveText,!live&&s.syncText]}>{live?(ar?"مباشر":"Live"):(ar?"مزامنة":"Syncing")}</Text></View></View>
    <View style={[s.privacy,rtl&&s.rowRtl]}><LockKeyhole size={14} color={darkTheme.accent}/><Text style={[s.privacyText,txt(rtl)]}>{ar?"هذه المحادثة مرتبطة بالفرصة. لا حاجة لمشاركة بيانات شخصية خارج ملامح.":"This conversation is tied to the opportunity. Keep personal contact details inside the protected workflow."}</Text></View>
    <FlatList ref={listRef} data={data.messages} keyExtractor={(x)=>String(x.id)} keyboardShouldPersistTaps="handled" contentContainerStyle={s.messages} onContentSizeChange={()=>listRef.current?.scrollToEnd({animated:false})} renderItem={({item})=><Bubble message={item} locale={locale}/>} ListEmptyComponent={<View style={s.empty}><Text style={[s.emptyText,txt(rtl)]}>{emptyText}</Text></View>}/>
    <View style={s.composer}>{error?<Text style={[s.inlineError,txt(rtl)]}>{error}</Text>:null}{!canSend&&policy.participantRole==="talent"?<Text style={[s.waiting,txt(rtl)]}>{ar?"بانتظار الناشر لبدء المحادثة":"Waiting for the publisher to start"}</Text>:null}<View style={[s.composeRow,rtl&&s.rowRtl]}><TextInput value={draft} onChangeText={setDraft} editable={canSend&&!sending} multiline maxLength={4000} placeholder={canSend?(ar?"اكتب رسالة":"Write a message"):(ar?"التواصل غير متاح الآن":"Messaging is not available yet")} placeholderTextColor={darkTheme.muted} textAlign={rtl?"right":"left"} style={[s.input,txt(rtl)]}/><Pressable disabled={!canSend||!draft.trim()||sending} onPress={()=>void submit()} style={[s.send,(!canSend||!draft.trim()||sending)&&s.disabled]}>{sending?<ActivityIndicator color={darkTheme.background}/>:<Send size={18} color={darkTheme.background} style={rtl?{transform:[{rotate:"180deg"}]}:undefined}/>}</Pressable></View></View>
  </KeyboardAvoidingView></SafeAreaView>;
}
function Bubble({message,locale}:{message:MobileMessage;locale:"ar"|"en"}){const rtl=locale==="ar";return <View style={[s.bubble,message.isMine?s.mine:s.theirs]}><Text style={[s.message,message.isMine&&s.mineText,txt(rtl)]}>{message.body}</Text><Text style={[s.messageTime,message.isMine&&s.mineTime]}>{formatRelativeTime(message.createdAt,locale)}</Text></View>}
function txt(rtl:boolean){return{textAlign:rtl?"right" as const:"left" as const,writingDirection:rtl?"rtl" as const:"ltr" as const}}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:darkTheme.background},center:{flex:1,alignItems:"center",justifyContent:"center",gap:14,padding:24,backgroundColor:darkTheme.background},centerError:{color:darkTheme.text,textAlign:"center"},secondary:{minHeight:46,borderWidth:1,borderColor:darkTheme.border,borderRadius:14,paddingHorizontal:18,alignItems:"center",justifyContent:"center"},secondaryText:{color:darkTheme.text,fontWeight:"800"},backText:{color:darkTheme.accent,fontWeight:"800"},rowRtl:{flexDirection:"row-reverse"},header:{minHeight:68,paddingHorizontal:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:darkTheme.border,flexDirection:"row",alignItems:"center",gap:9},backButton:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:darkTheme.border,backgroundColor:darkTheme.surface,alignItems:"center",justifyContent:"center"},avatar:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:"#C9A96244",alignItems:"center",justifyContent:"center"},avatarText:{color:darkTheme.accent,fontWeight:"900"},headerCopy:{flex:1,minWidth:0,gap:2},party:{color:darkTheme.text,fontSize:14,fontWeight:"900"},context:{color:darkTheme.muted,fontSize:9},live:{minHeight:28,borderRadius:999,borderWidth:1,borderColor:"#C9A96244",paddingHorizontal:8,flexDirection:"row",alignItems:"center",gap:4},syncing:{borderColor:darkTheme.border},liveText:{color:darkTheme.accent,fontSize:8,fontWeight:"900"},syncText:{color:darkTheme.muted},privacy:{marginHorizontal:12,marginTop:8,padding:9,borderRadius:12,backgroundColor:"#C9A96208",flexDirection:"row",alignItems:"center",gap:7},privacyText:{flex:1,color:darkTheme.muted,fontSize:9,lineHeight:14},messages:{padding:14,gap:8,flexGrow:1,justifyContent:"flex-end"},bubble:{maxWidth:"84%",borderRadius:17,paddingHorizontal:13,paddingTop:9,paddingBottom:6,gap:4},mine:{alignSelf:"flex-end",backgroundColor:darkTheme.accent,borderBottomRightRadius:5},theirs:{alignSelf:"flex-start",backgroundColor:darkTheme.surface,borderWidth:1,borderColor:darkTheme.border,borderBottomLeftRadius:5},message:{color:darkTheme.text,fontSize:14,lineHeight:20},mineText:{color:darkTheme.background,fontWeight:"600"},messageTime:{color:darkTheme.muted,fontSize:7,textAlign:"right"},mineTime:{color:"#15151599"},empty:{padding:28,alignItems:"center"},emptyText:{color:darkTheme.muted,fontSize:11,lineHeight:18,maxWidth:320},composer:{borderTopWidth:1,borderTopColor:darkTheme.border,padding:10,gap:6},composeRow:{flexDirection:"row",alignItems:"flex-end",gap:8},input:{flex:1,minHeight:48,maxHeight:120,borderWidth:1,borderColor:darkTheme.border,borderRadius:16,backgroundColor:darkTheme.surface,color:darkTheme.text,paddingHorizontal:13,paddingVertical:11},send:{width:48,height:48,borderRadius:15,backgroundColor:darkTheme.accent,alignItems:"center",justifyContent:"center"},disabled:{opacity:.35},inlineError:{color:"#E59A9A",fontSize:10},waiting:{color:darkTheme.accent,fontSize:10}});
