import { getSaudiCityBySlug } from "@/lib/data/saudi-cities";
import { createEvent, EVENT_TARGETS, EVENT_TYPES } from "@/lib/events";
import { createAdminClient } from "@/lib/supabase/admin";

const publisherStatuses=["draft","pending_review","needs_changes","closed","archived"] as const;
const publicStatuses=["open","published"] as const;
type Status=(typeof publisherStatuses)[number]|(typeof publicStatuses)[number];
const allowedTypes=new Set(["actor","model"]); const allowedGenders=new Set(["any","male","female"]); const compensationTypes=new Set(["fixed","negotiable","unpaid"]);
function clean(v:unknown){return typeof v==="string"?v.trim():""}
function isStatus(v:string):v is Status{return (publisherStatuses as readonly string[]).includes(v)||(publicStatuses as readonly string[]).includes(v)}
function integerOrNull(v:unknown,min:number,max:number){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isInteger(n)&&n>=min&&n<=max?n:undefined}
function budget(v:unknown){const x=clean(v).replace(/,/g,"");if(!x)return null;return /^\d+$/.test(x)?x:undefined}

export async function updateMobilePublisherOpportunity(userId:string,id:number,input:Record<string,unknown>){
  if(!Number.isInteger(id)||id<=0)return {ok:false as const,code:"INVALID_ID" as const};
  const locale=input.locale==="en"?"en":"ar"; const title=clean(input.title); const description=clean(input.description); const city=getSaudiCityBySlug(clean(input.citySlug)); const gender=clean(input.requiredGender)||"any"; const type=clean(input.opportunityType); const requestedStatus=clean(input.status)||"draft"; const minAge=integerOrNull(input.minAge,0,100); const maxAge=integerOrNull(input.maxAge,0,100); const applicationDays=integerOrNull(input.applicationDays,1,90); const compensationType=clean(input.compensationType)||"fixed"; const normalizedBudget=compensationType==="fixed"?budget(input.budget):null;
  if(title.length<3||title.length>120)return {ok:false as const,code:"INVALID_TITLE" as const};
  if(description.length<20||description.length>3000)return {ok:false as const,code:"INVALID_DESCRIPTION" as const};
  if(!city)return {ok:false as const,code:"INVALID_CITY" as const}; if(!allowedTypes.has(type))return {ok:false as const,code:"INVALID_TYPE" as const}; if(!allowedGenders.has(gender))return {ok:false as const,code:"INVALID_GENDER" as const}; if(!isStatus(requestedStatus))return {ok:false as const,code:"INVALID_STATUS" as const}; if(minAge===undefined||maxAge===undefined||applicationDays===undefined)return {ok:false as const,code:"INVALID_NUMERIC_FIELD" as const}; if(minAge!==null&&maxAge!==null&&minAge>maxAge)return {ok:false as const,code:"INVALID_AGE_RANGE" as const}; if(!compensationTypes.has(compensationType))return {ok:false as const,code:"INVALID_COMPENSATION" as const}; if(compensationType==="fixed"&&(!normalizedBudget||normalizedBudget===undefined||Number(normalizedBudget)<=0))return {ok:false as const,code:"INVALID_BUDGET" as const};
  const admin=createAdminClient(); const {data:profile,error:profileError}=await admin.from("profiles").select("id,account_type,approval_status").eq("user_id",userId).maybeSingle(); if(profileError||!profile||profile.account_type!=="publisher")return {ok:false as const,code:"PUBLISHER_REQUIRED" as const}; if(profile.approval_status!=="approved")return {ok:false as const,code:"PUBLISHER_NOT_APPROVED" as const};
  const {data:publisher,error:publisherError}=await admin.from("publishers").select("id,status").eq("profile_id",profile.id).maybeSingle(); if(publisherError||!publisher)return {ok:false as const,code:"PUBLISHER_NOT_FOUND" as const}; if(publisher.status==="suspended")return {ok:false as const,code:"PUBLISHER_SUSPENDED" as const};
  const {data:opportunity,error:oppError}=await admin.from("opportunities").select("id,publisher_id,status").eq("id",id).eq("publisher_id",publisher.id).maybeSingle(); if(oppError||!opportunity)return {ok:false as const,code:"NOT_FOUND" as const}; const current=clean(opportunity.status); if(!isStatus(current))return {ok:false as const,code:"INVALID_CURRENT_STATUS" as const};
  const allowed:Status[]=current==="open"||current==="published"?[current,"closed","archived"]:current==="needs_changes"?["draft","pending_review","closed","archived"]:["draft","pending_review","closed","archived"]; if(!allowed.includes(requestedStatus))return {ok:false as const,code:"INVALID_TRANSITION" as const};
  const requiresNewReview=(current==="open"||current==="published")&&requestedStatus===current; const resubmitted=current==="needs_changes"&&requestedStatus==="pending_review"; const finalStatus:Status=requiresNewReview?"pending_review":requestedStatus; const published=finalStatus==="published"||finalStatus==="open";
  const {data:updated,error:updateError}=await admin.from("opportunities").update({title,description,city_slug:city.slug,city_ar:city.ar,city_en:city.en,required_gender:gender,opportunity_type:type,min_age:minAge,max_age:maxAge,compensation_type:compensationType,budget:normalizedBudget,application_days:applicationDays??30,status:finalStatus,published,updated_at:new Date().toISOString()}).eq("id",id).eq("publisher_id",publisher.id).select("id").single(); if(updateError||!updated)return {ok:false as const,code:"UPDATE_FAILED" as const};
  if(requiresNewReview||resubmitted){try{await createEvent({type:EVENT_TYPES.opportunity_pending_review,target:EVENT_TARGETS.ADMIN,targetId:"admin",actorId:publisher.id,metadata:{opportunityId:id,publisherId:publisher.id,title,city_ar:city.ar,city_en:city.en,opportunityType:type,compensationType,budget:normalizedBudget,reason:resubmitted?"resubmitted_after_changes":"updated_after_publication"}})}catch{}}
  return {ok:true as const,status:finalStatus,requiresReview:requiresNewReview||resubmitted};
}