import { useCallback, useEffect, useState } from "react";
import { FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { ChevronLeft, ChevronRight, MessageCircle } from "lucide-react-native";

import { PublisherTabBar } from "@/components/PublisherTabBar";
import { ScreenSkeleton } from "@/components/ScreenSkeleton";
import { formatLatinNumber, formatRelativeTime, isRtlLocale } from "@/lib/i18n";
import { useAppLocale } from "@/lib/locale-context";
import { getPublisherConversations, getPublisherDashboard, type MobileConversation } from "@/lib/publisher-api";
import { darkTheme, radii, spacing, typography } from "@/lib/theme";

export default function PublisherMessagesScreen(){
  const {locale}=useAppLocale();const ar=locale==="ar",rtl=isRtlLocale(locale);
  const [items,setItems]=useState<MobileConversation[]>([]),[unread,setUnread]=useState(0),[hasOpportunities,setHasOpportunities]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError(null);try{const [result,dashboard]=await Promise.all([getPublisherConversations(),getPublisherDashboard(locale).catch(()=>null)]);if(!result){setError(ar?"تعذر تحميل المحادثات.":"Unable to load conversations.");setItems([]);setUnread(0);}else{setItems(result.items);setUnread(result.unreadCount);}setHasOpportunities(Boolean(dashboard?.opportunities.length));}catch{setError(ar?"تعذر تحميل المحادثات. تحقق من الاتصال وحاول مرة أخرى.":"Unable to load conversations. Check your connection and try again.");}finally{setLoading(false);setRefreshing(false);}},[ar,locale]);
  useEffect(()=>{void load()},[load]);
  if(loading)return <ScreenSkeleton variant="list" locale={locale} label={ar?"جارٍ تحميل الرسائل":"Loading messages"}/>;

  return <SafeAreaView style={s.screen} edges={["top"]}>
    <FlatList data={items} keyExtractor={(x)=>String(x.id)} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={darkTheme.accent}/>} ListHeaderComponent={<View style={s.header}>
      <View style={[s.titleRow,rtl&&s.rowRtl]}><View style={s.flex}><Text style={[s.brand,txt(rtl)]}>{ar?"ملامح للأعمال":"MLAMH FOR BUSINESS"}</Text><Text accessibilityRole="header" style={[s.title,txt(rtl)]}>{ar?"الرسائل":"Messages"}</Text><Text style={[s.subtitle,txt(rtl)]}>{ar?"محادثاتك المرتبطة بالفرص والاختيارات في مكان واحد.":"Conversations tied to your opportunities and selections, in one place."}</Text></View>{unread>0?<View style={s.badge}><Text style={s.badgeText}>{unread>99?"99+":formatLatinNumber(unread,locale)}</Text></View>:null}</View>
      {error?<View style={s.errorBox}><Text style={[s.error,txt(rtl)]}>{error}</Text><Pressable onPress={()=>void load()}><Text style={s.retry}>{ar?"إعادة المحاولة":"Try again"}</Text></Pressable></View>:null}
    </View>} renderItem={({item})=><ConversationRow item={item} locale={locale}/>} ListEmptyComponent={!error?<View style={s.empty}><View style={s.emptyIcon}><MessageCircle size={25} color={darkTheme.accent}/></View><Text style={[s.emptyTitle,txt(rtl)]}>{ar?"لا توجد محادثات بعد":"No conversations yet"}</Text><Text style={[s.emptyBody,txt(rtl)]}>{ar?"بعد قبول موهبة لإحدى فرصك ستظهر المحادثة هنا ويمكنك بدء التواصل.":"After accepting talent for an opportunity, the conversation appears here and you can start messaging."}</Text><Pressable onPress={()=>router.push(hasOpportunities?"/publisher":"/publisher/opportunities/new")} style={s.action}><Text style={s.actionText}>{hasOpportunities?(ar?"إدارة الفرص":"Manage opportunities"):(ar?"إنشاء أول فرصة":"Create first opportunity")}</Text></Pressable></View>:null} showsVerticalScrollIndicator={false}/>
    <PublisherTabBar active="messages" locale={locale} unreadCount={unread}/>
  </SafeAreaView>;
}
function ConversationRow({item,locale}:{item:MobileConversation;locale:"ar"|"en"}){const rtl=locale==="ar",Arrow=rtl?ChevronLeft:ChevronRight,time=item.lastActivityAt?formatRelativeTime(item.lastActivityAt,locale):"";return <Pressable onPress={()=>router.push(`/conversations/${item.id}`)} style={({pressed})=>[s.row,rtl&&s.rowRtl,item.unreadCount>0&&s.rowUnread,pressed&&s.pressed]}>{item.partyImageUrl?<Image source={{uri:item.partyImageUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{item.partyName.slice(0,1).toUpperCase()}</Text></View>}<View style={s.flex}><View style={[s.rowTop,rtl&&s.rowRtl]}><Text numberOfLines={1} style={[s.party,txt(rtl)]}>{item.partyName}</Text><Text style={s.time}>{time}</Text></View><Text numberOfLines={1} style={[s.opportunity,txt(rtl)]}>{item.opportunityTitle??"MLAMH"}</Text><Text numberOfLines={1} style={[s.preview,txt(rtl)]}>{item.latestMessage??(locale==="ar"?"ابدأ المحادثة":"Start the conversation")}</Text></View>{item.unreadCount>0?<View style={s.unread}><Text style={s.unreadText}>{item.unreadCount>99?"99+":formatLatinNumber(item.unreadCount,locale)}</Text></View>:<Arrow size={17} color={darkTheme.muted}/>}</Pressable>}
function txt(rtl:boolean){return{textAlign:rtl?"right" as const:"left" as const,writingDirection:rtl?"rtl" as const:"ltr" as const}}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:darkTheme.background},content:{paddingHorizontal:spacing.lg,paddingBottom:112},header:{paddingTop:8,paddingBottom:18,gap:12},titleRow:{flexDirection:"row",alignItems:"flex-start",gap:12},rowRtl:{flexDirection:"row-reverse"},flex:{flex:1,minWidth:0},brand:{color:darkTheme.accent,fontSize:10,fontWeight:"900"},title:{...typography.pageTitle,color:darkTheme.text,marginTop:4},subtitle:{...typography.body,color:darkTheme.muted,marginTop:4,maxWidth:430},badge:{minWidth:28,height:28,borderRadius:14,backgroundColor:darkTheme.accent,paddingHorizontal:7,alignItems:"center",justifyContent:"center",marginTop:8},badgeText:{color:darkTheme.background,fontSize:9,fontWeight:"900"},errorBox:{gap:7,padding:12,borderRadius:radii.md,backgroundColor:darkTheme.dangerSurface,borderWidth:1,borderColor:"#E59A9A33"},error:{color:darkTheme.danger,fontSize:11},retry:{color:darkTheme.accent,fontSize:11,fontWeight:"900"},row:{minHeight:84,flexDirection:"row",alignItems:"center",gap:11,padding:12,marginBottom:9,borderWidth:1,borderColor:darkTheme.border,borderRadius:radii.lg,backgroundColor:darkTheme.surface},rowUnread:{borderColor:"#C9A96255",backgroundColor:"#C9A96208"},pressed:{opacity:.7},avatar:{width:46,height:46,borderRadius:23},avatarFallback:{width:46,height:46,borderRadius:23,borderWidth:1,borderColor:darkTheme.border,alignItems:"center",justifyContent:"center"},avatarText:{color:darkTheme.accent,fontSize:16,fontWeight:"900"},rowTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},party:{flex:1,color:darkTheme.text,fontSize:14,fontWeight:"900"},time:{color:darkTheme.muted,fontSize:8},opportunity:{color:darkTheme.accent,fontSize:9,fontWeight:"800",marginTop:3},preview:{color:darkTheme.muted,fontSize:10,marginTop:4},unread:{minWidth:22,height:22,borderRadius:11,backgroundColor:darkTheme.accent,alignItems:"center",justifyContent:"center",paddingHorizontal:5},unreadText:{color:darkTheme.background,fontSize:8,fontWeight:"900"},empty:{minHeight:360,alignItems:"center",justifyContent:"center",gap:10,padding:26},emptyIcon:{width:52,height:52,borderRadius:18,borderWidth:1,borderColor:"#C9A96244",backgroundColor:"#C9A9620D",alignItems:"center",justifyContent:"center"},emptyTitle:{color:darkTheme.text,fontSize:17,fontWeight:"900",textAlign:"center"},emptyBody:{color:darkTheme.muted,fontSize:11,lineHeight:18,maxWidth:330,textAlign:"center"},action:{minHeight:46,borderRadius:radii.md,backgroundColor:darkTheme.accent,paddingHorizontal:18,alignItems:"center",justifyContent:"center",marginTop:4},actionText:{color:darkTheme.background,fontWeight:"900",fontSize:12}});
