import { AdminCard, AdminGrid, AdminPageContainer, AdminPageHeader, AdminStatCard } from "@/components/admin/ui";
import { getAdminLanguage } from "@/lib/admin/i18n";
import { requireAdminAccess } from "@/lib/auth/require-admin";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic="force-dynamic";type PageProps={searchParams:Promise<{lang?:string}>};
function statusLabel(value:string,ar:boolean){const m:Record<string,[string,string]>={draft:["مسودة","Draft"],ready:["جاهز للمراجعة","Ready for review"],approved:["معتمد","Approved"],published:["منشور","Published"],archived:["مؤرشف","Archived"]};return m[value]?.[ar?0:1]??value;}
function typeLabel(value:string,ar:boolean){const m:Record<string,[string,string]>={image:["صورة","Image"],video:["فيديو","Video"],story:["ستوري","Story"],reel:["ريلز","Reel"],carousel:["كاروسيل","Carousel"],post:["منشور","Post"]};return m[value]?.[ar?0:1]??value;}
export default async function CreativeStudioPage({searchParams}:PageProps){await requireAdminAccess();const{lang}=await searchParams;const isArabic=getAdminLanguage(lang)==="ar";const db=createAdminClient();const{data,error}=await db.from("marketing_creatives").select("id,content_id,campaign_id,type,platform,aspect_ratio,status,storage_path,preview_path,created_by_agent_id,version,created_at").order("created_at",{ascending:false}).limit(150);const rows=data??[];const ready=rows.filter(i=>["ready","approved"].includes(i.status)).length;const published=rows.filter(i=>i.status==="published").length;const drafts=rows.filter(i=>i.status==="draft").length;
return <AdminPageContainer><AdminPageHeader title={isArabic?"Creative Studio":"Creative Studio"} description={isArabic?"مكتبة تنفيذية للكرياتيف: شاهد ما هو مسودة، وما ينتظر المراجعة، وما أصبح جاهزًا أو منشورًا.":"An executive creative library showing drafts, review-ready assets and published work."}/><AdminGrid className="mb-6 md:grid-cols-3"><AdminStatCard label={isArabic?"مسودات":"Drafts"} value={drafts}/><AdminStatCard label={isArabic?"جاهز للمراجعة":"Ready"} value={ready}/><AdminStatCard label={isArabic?"منشور":"Published"} value={published}/></AdminGrid>{error?<AdminCard className="mb-5 p-5 text-sm text-amber-200">{isArabic?"تعذر تحميل ملفات Creative Studio.":"Creative Studio data is unavailable."}</AdminCard>:null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.length===0?<AdminCard className="p-6 md:col-span-2 xl:col-span-3"><p className="text-sm text-white/60">{isArabic?"لا توجد أصول إبداعية بعد.":"No creative assets yet."}</p><p className="mt-1 text-xs text-white/30">{isArabic?"عند إنشاء أول محتوى بصري سيظهر هنا كأصل قابل للمراجعة والإصدار.":"New visual work will appear here as a reviewable, versioned asset."}</p></AdminCard>:rows.map(item=><AdminCard key={item.id} className="overflow-hidden"><div className="flex aspect-[16/8] items-center justify-center border-b border-white/[0.06] bg-gradient-to-br from-white/[0.04] to-gold/[0.035]"><div className="text-center"><p className="text-2xl text-white/20">{item.aspect_ratio||"—"}</p><p className="mt-2 text-[10px] uppercase tracking-[.18em] text-white/25">{item.platform||"MLAMH"}</p></div></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-white">{typeLabel(item.type,isArabic)}</p><p className="mt-1 text-xs text-white/35">{item.platform||"—"} · {item.aspect_ratio||"—"}</p></div><span className="rounded-full border border-gold/15 bg-gold/[0.05] px-2.5 py-1 text-[10px] text-gold">{statusLabel(item.status,isArabic)}</span></div><div className="mt-4 flex items-center justify-between text-[11px] text-white/30"><span>{isArabic?"الإصدار":"Version"} {item.version}</span><span>{item.created_by_agent_id?`${isArabic?"بواسطة":"by"} ${item.created_by_agent_id}`:(isArabic?"MLAMH Team":"MLAMH Team")}</span></div></div></AdminCard>)}</div></AdminPageContainer>;
}
