export type SeoLandingLocaleContent = {
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  intro: string;
  whyTitle: string;
  whyText: string;
  projectTypes: string[];
  tipsTitle: string;
  tips: string[];
  faq: Array<{ question: string; answer: string }>;
};

export type SeoLandingDefinition = {
  slug: string;
  keywords: string[];
  ar: SeoLandingLocaleContent;
  en: SeoLandingLocaleContent;
};

export const SEO_ACQUISITION_LANDINGS: SeoLandingDefinition[] = [
  {
    slug: "models-saudi-arabia",
    keywords: ["مودل السعودية", "مودلز السعودية", "مودلز للإعلانات في السعودية", "models saudi arabia"],
    ar: {
      title: "مودلز في السعودية للإعلانات والتصوير | ملامح",
      description: "ابحث عن مودلز في السعودية لمشاريع الإعلانات والتصوير والمحتوى عبر ملامح، أو انشر فرصة كاستينج لتستقبل طلبات المواهب المناسبة.",
      eyebrow: "مودلز السعودية",
      heading: "تحتاج مودل في السعودية لمشروعك؟ ابدأ من ملامح.",
      intro: "ملامح تساعد البراندات والمتاجر والوكالات وشركات الإنتاج وأصحاب المشاريع على تنظيم احتياجهم للمودلز في السعودية. لا نعرض ملفات خاصة على هذه الصفحة؛ الهدف أن تحدد احتياجك وتنشر فرصة واضحة ليصل إليك المهتمون المناسبون.",
      whyTitle: "استخدامات شائعة للمودلز في السوق السعودي",
      whyText: "الاحتياج يختلف بين تصوير منتج، حملة رقمية، محتوى اجتماعي، متجر إلكتروني أو فعالية. كلما كان الـBrief أوضح في المدينة ونوع الاستخدام ومدة التصوير والمقابل، كانت الطلبات أقرب إلى المطلوب.",
      projectTypes: ["حملات إعلانية وتجارية", "تصوير منتجات ومتاجر إلكترونية", "محتوى سوشيال ميديا", "مطاعم ومقاهي وضيافة", "تجميل وأزياء ولايف ستايل", "فعاليات ومعارض"],
      tipsTitle: "قبل نشر فرصة المودل",
      tips: ["حدد المدينة وموقع التصوير بوضوح.", "اذكر طبيعة الاستخدام: إعلان، محتوى، متجر، فعالية أو تصوير ثابت.", "وضح مدة التصوير والمقابل وحقوق الاستخدام إن وجدت.", "اكتب المتطلبات المهمة فقط وتجنب الشروط غير الضرورية."],
      faq: [
        { question: "كيف أطلب مودلز عبر ملامح؟", answer: "أنشئ حساب ناشر ثم انشر فرصة كاستينج تتضمن المدينة ونوع المشروع والمتطلبات والمقابل. بعد المراجعة تظهر الفرصة للمواهب المناسبة للتقديم." },
        { question: "هل تعرض هذه الصفحة أسماء أو صور المواهب؟", answer: "لا. هذه Landing Page للوصول من البحث وشرح الخدمة، ولا تعرض ملفات المواهب الخاصة." },
        { question: "هل ملامح وكالة مواهب؟", answer: "ملامح منصة تربط الناشرين والمواهب وتدير رحلة الفرصة والتقديم والاختيار داخل المنصة، وليست وكالة تمثيل تقليدية." },
      ],
    },
    en: {
      title: "Models in Saudi Arabia for Ads & Shoots | MLAMH",
      description: "Find a structured way to source models in Saudi Arabia for advertising, shoots and content. Post a casting opportunity on MLAMH and receive relevant applications.",
      eyebrow: "MODELS IN SAUDI ARABIA",
      heading: "Need models in Saudi Arabia for your next project?",
      intro: "MLAMH helps brands, agencies, production teams, stores and project owners structure their model requirements in Saudi Arabia. This landing page does not expose private talent profiles; it helps you define the need and post an opportunity for relevant talent to apply.",
      whyTitle: "Common model use cases in Saudi Arabia",
      whyText: "Model requirements vary across product shoots, campaigns, social content, e-commerce and events. A clear brief with city, usage, shoot duration and compensation improves the quality of applications.",
      projectTypes: ["Advertising campaigns", "Product and e-commerce shoots", "Social media content", "Restaurants and hospitality", "Beauty, fashion and lifestyle", "Events and exhibitions"],
      tipsTitle: "Before posting a model opportunity",
      tips: ["Specify the city and shoot location.", "Explain the usage: ad, content, e-commerce, event or stills.", "State shoot duration, compensation and usage rights when relevant.", "Keep requirements focused on what the project actually needs."],
      faq: [
        { question: "How do I source models through MLAMH?", answer: "Create a publisher account and post a casting opportunity with the city, project type, requirements and compensation. Once reviewed, relevant talent can apply." },
        { question: "Does this page show talent names or photos?", answer: "No. It is an SEO landing page and does not expose private talent profiles." },
        { question: "Is MLAMH a talent agency?", answer: "MLAMH is a platform that connects publishers and talent and manages the opportunity, application and selection workflow rather than operating as a traditional representation agency." },
      ],
    },
  },
  {
    slug: "models-riyadh",
    keywords: ["مودل الرياض", "مودلز الرياض", "مودلز تصوير الرياض", "models riyadh"],
    ar: {
      title: "مودلز الرياض للإعلانات والتصوير | ملامح",
      description: "تحتاج مودل أو مودلز في الرياض؟ انشر فرصة كاستينج على ملامح لمشاريع التصوير والإعلانات والمحتوى والفعاليات.",
      eyebrow: "مودلز الرياض",
      heading: "مودلز الرياض لمشاريع الإعلان والتصوير والمحتوى.",
      intro: "إذا كان مشروعك في الرياض، يمكنك استخدام ملامح لنشر احتياج واضح للمودلز بدل الاعتماد على الرسائل المتفرقة. تحدد طبيعة المشروع والموعد والمتطلبات، ثم تستقبل الطلبات داخل مسار واحد منظم.",
      whyTitle: "متى تحتاج مودل في الرياض؟",
      whyText: "الرياض سوق نشط للحملات التجارية، المتاجر، المطاعم، الفعاليات، المحتوى الرقمي والإنتاج. صفحة البحث هذه تقودك إلى نشر الفرصة ولا تكشف أي ملفات خاصة للمواهب.",
      projectTypes: ["إعلانات البراندات", "افتتاحات وفعاليات", "مطاعم ومقاهي", "تصوير أزياء وتجميل", "متاجر إلكترونية", "محتوى الشركات"],
      tipsTitle: "كيف تجعل فرصة الرياض أوضح؟",
      tips: ["اذكر الحي أو نطاق موقع التصوير عند الحاجة.", "حدد إن كان الحضور ليوم واحد أو عدة أيام.", "وضح إن كانت الخبرة شرطًا أم أن الوجوه الجديدة مقبولة.", "أضف الموعد المتوقع والمقابل قبل النشر."],
      faq: [
        { question: "هل يمكن نشر فرصة مودل خاصة بالرياض فقط؟", answer: "نعم، يمكنك تحديد الرياض كمدينة للمشروع وكتابة متطلبات الفرصة بشكل واضح." },
        { question: "هل يلزم عرض المواهب على الصفحة؟", answer: "لا. الصفحة هدفها الوصول من Google وتحويل الناشر إلى نشر فرصة داخل ملامح." },
        { question: "هل يمكن للمتاجر الصغيرة استخدام ملامح؟", answer: "نعم، ملامح تدعم أصحاب المشاريع والمتاجر والأنشطة التجارية إلى جانب الشركات والوكالات." },
      ],
    },
    en: {
      title: "Models in Riyadh for Ads & Shoots | MLAMH",
      description: "Need models in Riyadh? Post a casting opportunity on MLAMH for advertising, content, e-commerce, events and production projects.",
      eyebrow: "MODELS IN RIYADH",
      heading: "Source models in Riyadh through a clear casting workflow.",
      intro: "For projects in Riyadh, MLAMH lets publishers post a structured model requirement instead of relying on scattered messages. Define the project, date and requirements, then receive applications in one workflow.",
      whyTitle: "When projects need models in Riyadh",
      whyText: "Riyadh has active demand across commercial campaigns, retail, restaurants, events, digital content and production. This page is built for discovery and conversion without exposing private talent profiles.",
      projectTypes: ["Brand campaigns", "Events and launches", "Restaurants and cafes", "Fashion and beauty shoots", "E-commerce", "Corporate content"],
      tipsTitle: "Make your Riyadh casting clearer",
      tips: ["Add the district or general shoot area when useful.", "State whether the booking is one day or multiple days.", "Clarify if prior experience is required or new faces are welcome.", "Include the expected date and compensation."],
      faq: [
        { question: "Can I post a Riyadh-only model opportunity?", answer: "Yes. Set Riyadh as the project city and describe the requirements clearly." },
        { question: "Do you need to display talent on this page?", answer: "No. The page is designed to capture search demand and move publishers into MLAMH's opportunity workflow." },
        { question: "Can small businesses use MLAMH?", answer: "Yes. MLAMH supports project owners, stores and small businesses as well as companies and agencies." },
      ],
    },
  },
  {
    slug: "models-jeddah",
    keywords: ["مودل جدة", "مودلز جدة", "مودلز تصوير جدة", "models jeddah"],
    ar: {
      title: "مودلز جدة للإعلانات والتصوير | ملامح",
      description: "ابحث عن مودلز لمشاريع جدة عبر نشر فرصة كاستينج منظمة على ملامح للإعلانات والتصوير والمتاجر والمحتوى.",
      eyebrow: "مودلز جدة",
      heading: "مشروعك في جدة ويحتاج مودل؟ انشر الفرصة بوضوح.",
      intro: "ملامح توفر للجهات وأصحاب المشاريع في جدة مسارًا واضحًا لنشر احتياج المودلز واستقبال الطلبات. لا تحتاج الصفحة إلى عرض ملفات المواهب حتى تؤدي دورها في الوصول من محركات البحث.",
      whyTitle: "مشاريع المودلز في جدة",
      whyText: "تتنوع الاحتياجات بين الضيافة والسياحة والمطاعم والتجزئة والأزياء والمحتوى والحملات الموسمية. الأفضل أن يعكس نص الفرصة طبيعة المشروع الفعلية بدل استخدام وصف عام.",
      projectTypes: ["ضيافة وسياحة", "مطاعم ومقاهي", "أزياء وتجزئة", "تصوير منتجات", "حملات رقمية", "فعاليات موسمية"],
      tipsTitle: "نقاط مهمة لفرصة جدة",
      tips: ["حدد جدة بوضوح ومكان التنفيذ التقريبي.", "اشرح هل الاستخدام صور ثابتة أم فيديو أم فعالية.", "اذكر مدة الحضور والتعويض.", "وضح أي متطلبات مرتبطة بالمنتج أو الجمهور."],
      faq: [
        { question: "هل أقدر أنشر فرصة مودل في جدة فقط؟", answer: "نعم، حدد جدة كمدينة للفرصة وأكمل تفاصيل المشروع." },
        { question: "هل ملامح مناسب للمطاعم والمتاجر؟", answer: "نعم، الناشر قد يكون متجرًا أو نشاطًا تجاريًا أو صاحب مشروع أو شركة أو وكالة." },
        { question: "هل الصفحة نفسها تعرض قاعدة بيانات المواهب؟", answer: "لا، هذه الصفحة تعريفية وتحويلية، بينما الوصول للمواهب يتم وفق صلاحيات ومسارات المنصة." },
      ],
    },
    en: {
      title: "Models in Jeddah for Ads & Shoots | MLAMH",
      description: "Post a structured casting opportunity in Jeddah for models needed in advertising, hospitality, retail, e-commerce and content projects.",
      eyebrow: "MODELS IN JEDDAH",
      heading: "Need a model in Jeddah? Publish the requirement clearly.",
      intro: "MLAMH gives businesses and project owners in Jeddah a clear path to post model requirements and receive applications. The landing page can rank for relevant searches without exposing talent profiles.",
      whyTitle: "Model projects in Jeddah",
      whyText: "Demand spans hospitality, tourism, restaurants, retail, fashion, content and seasonal campaigns. The strongest opportunity pages describe the real project rather than using a generic casting note.",
      projectTypes: ["Hospitality and tourism", "Restaurants and cafes", "Fashion and retail", "Product shoots", "Digital campaigns", "Seasonal events"],
      tipsTitle: "Key details for a Jeddah opportunity",
      tips: ["State Jeddah and the approximate shoot area.", "Explain whether the usage is stills, video or an event.", "Include attendance duration and compensation.", "Add any requirements tied to the product or audience."],
      faq: [
        { question: "Can I post a Jeddah-only model opportunity?", answer: "Yes. Set Jeddah as the opportunity city and add the project details." },
        { question: "Is MLAMH suitable for restaurants and stores?", answer: "Yes. Publishers can be stores, small businesses, project owners, companies or agencies." },
        { question: "Does this page expose a talent database?", answer: "No. It is a discovery and conversion page. Talent access remains governed by MLAMH product permissions and privacy." },
      ],
    },
  },
  {
    slug: "actors-saudi-arabia",
    keywords: ["ممثلين السعودية", "ممثلين سعوديين", "ممثلين للإعلانات", "actors saudi arabia"],
    ar: {
      title: "ممثلين في السعودية للإعلانات والإنتاج | ملامح",
      description: "تحتاج ممثلين في السعودية لإعلان أو محتوى أو إنتاج؟ انشر فرصة كاستينج على ملامح واستقبل طلبات المواهب المناسبة.",
      eyebrow: "ممثلين السعودية",
      heading: "تحتاج ممثلين في السعودية؟ حوّل احتياجك إلى فرصة واضحة.",
      intro: "ملامح تساعد شركات الإنتاج والوكالات والبراندات وأصحاب المشاريع على نشر فرص تمثيل منظمة في السعودية. بدل عرض ملفات خاصة للعامة، نركز هنا على جذب الباحث عن الخدمة وتحويله إلى ناشر فرصة.",
      whyTitle: "أنواع مشاريع التمثيل",
      whyText: "اختيار الممثل يتأثر بطبيعة الدور، اللهجة، العمر التمثيلي، موقع التصوير، عدد أيام العمل وحقوق الاستخدام. وجود هذه المعلومات منذ البداية يقلل الطلبات غير المناسبة.",
      projectTypes: ["إعلانات تجارية", "محتوى براندات", "أفلام قصيرة", "إنتاج رقمي", "كومبارس وأدوار مساندة", "فعاليات وتجارب أداء"],
      tipsTitle: "ما الذي يجب أن يحتويه إعلان الكاستينج؟",
      tips: ["صف الدور بدل الاكتفاء بعبارة مطلوب ممثل.", "حدد المدينة وأيام التصوير المتوقعة.", "اذكر اللهجة أو اللغة إذا كانت أساسية للدور.", "وضح المقابل وحقوق الاستخدام عند وجود إعلان مدفوع."],
      faq: [
        { question: "كيف أجد ممثلين لمشروع في السعودية؟", answer: "ابدأ بحساب ناشر ثم أنشئ فرصة كاستينج تتضمن تفاصيل الدور والموقع والموعد والمقابل." },
        { question: "هل يمكن استقبال وجوه جديدة؟", answer: "نعم، يمكنك توضيح أن الفرصة تقبل وجوهًا جديدة أو خبرة محددة حسب المشروع." },
        { question: "هل تعرض هذه الصفحة ممثلين بأسمائهم؟", answer: "لا. الصفحة مخصصة للبحث والوصول، ولا تكشف ملفات المواهب الخاصة." },
      ],
    },
    en: {
      title: "Actors in Saudi Arabia for Ads & Production | MLAMH",
      description: "Need actors in Saudi Arabia for advertising, branded content or production? Post a casting opportunity on MLAMH and receive relevant applications.",
      eyebrow: "ACTORS IN SAUDI ARABIA",
      heading: "Need actors in Saudi Arabia? Turn the requirement into a clear casting opportunity.",
      intro: "MLAMH helps production companies, agencies, brands and project owners post structured acting opportunities in Saudi Arabia. Instead of exposing private talent profiles publicly, this page captures service intent and moves publishers into the opportunity workflow.",
      whyTitle: "Common acting project types",
      whyText: "Actor selection depends on role, dialect, playing age, shoot location, working days and usage rights. Sharing these details early improves application relevance.",
      projectTypes: ["Commercials", "Branded content", "Short films", "Digital production", "Extras and supporting roles", "Events and auditions"],
      tipsTitle: "What should a casting notice include?",
      tips: ["Describe the role instead of only saying actor needed.", "State the city and expected shoot dates.", "Mention dialect or language when essential.", "Explain compensation and usage rights for commercial work."],
      faq: [
        { question: "How do I find actors for a project in Saudi Arabia?", answer: "Create a publisher account and post a casting opportunity with role, location, schedule and compensation details." },
        { question: "Can I accept new faces?", answer: "Yes. You can state that new faces are welcome or require specific experience based on the project." },
        { question: "Does this page list actors by name?", answer: "No. It is designed for search acquisition and does not expose private talent profiles." },
      ],
    },
  },
  {
    slug: "actors-riyadh",
    keywords: ["ممثلين الرياض", "ممثلين للإعلانات في الرياض", "ممثلين تصوير الرياض", "actors riyadh"],
    ar: {
      title: "ممثلين الرياض للإعلانات والتصوير | ملامح",
      description: "انشر فرصة كاستينج في الرياض للممثلين المطلوبين في الإعلانات والمحتوى والإنتاج عبر منصة ملامح.",
      eyebrow: "ممثلين الرياض",
      heading: "ممثلين الرياض لمشروعك القادم — ابدأ بفرصة كاستينج.",
      intro: "إذا كان لديك إعلان أو إنتاج أو محتوى في الرياض، اجعل نقطة البداية فرصة واضحة داخل ملامح. تحدد الدور والموعد والموقع والمقابل، ثم تدير الطلبات في مكان واحد.",
      whyTitle: "احتياجات التمثيل في الرياض",
      whyText: "الطلب يشمل الإعلانات التجارية، محتوى الشركات، الحملات الرقمية، الفيديوهات القصيرة، الفعاليات والكومبارس. كل نوع يحتاج Brief مختلفًا حتى يصل إلى الجمهور الصحيح.",
      projectTypes: ["إعلانات فيديو", "محتوى شركات", "حملات رقمية", "مشاهد قصيرة", "كومبارس", "فعاليات"],
      tipsTitle: "فرصة تمثيل أفضل في الرياض",
      tips: ["حدد طبيعة الدور وحجمه.", "اذكر الرياض وموقع التنفيذ التقريبي.", "وضح إن كان هناك نص أو تجربة أداء.", "حدد المقابل والموعد المتوقع."],
      faq: [
        { question: "هل يمكنني نشر تجربة أداء في الرياض؟", answer: "نعم، يمكنك نشر فرصة تمثيل وتوضيح ما إذا كان الاختيار يتطلب تجربة أداء أو Self-tape." },
        { question: "هل الناشر يجب أن يكون شركة؟", answer: "لا. يمكن أن يكون فردًا أو صاحب مشروع أو متجرًا أو نشاطًا تجاريًا أو شركة أو وكالة." },
        { question: "كيف أبدأ؟", answer: "أنشئ حساب ناشر أو سجل الدخول ثم ابدأ فرصة جديدة من ملامح." },
      ],
    },
    en: {
      title: "Actors in Riyadh for Ads & Production | MLAMH",
      description: "Post a Riyadh casting opportunity for actors needed in commercials, branded content, digital production and events through MLAMH.",
      eyebrow: "ACTORS IN RIYADH",
      heading: "Actors in Riyadh for your next project — start with a casting opportunity.",
      intro: "If you are producing an ad, campaign or content project in Riyadh, start with a clear opportunity on MLAMH. Define the role, date, location and compensation, then manage applications in one place.",
      whyTitle: "Acting demand in Riyadh",
      whyText: "Projects include commercials, corporate content, digital campaigns, short-form video, events and extras. Each type benefits from a different brief and selection criteria.",
      projectTypes: ["Video commercials", "Corporate content", "Digital campaigns", "Short scenes", "Extras", "Events"],
      tipsTitle: "A stronger Riyadh casting opportunity",
      tips: ["Define the role and its scope.", "State Riyadh and the approximate location.", "Explain whether a script, audition or self-tape is required.", "Include compensation and expected timing."],
      faq: [
        { question: "Can I post an audition in Riyadh?", answer: "Yes. Post an acting opportunity and specify whether selection requires an audition or self-tape." },
        { question: "Does the publisher have to be a company?", answer: "No. Publishers can be individuals, project owners, stores, businesses, companies or agencies." },
        { question: "How do I start?", answer: "Create a publisher account or sign in, then create a new opportunity on MLAMH." },
      ],
    },
  },
  {
    slug: "actors-jeddah",
    keywords: ["ممثلين جدة", "كاستنج جدة ممثلين", "ممثلين للإعلانات جدة", "actors jeddah"],
    ar: {
      title: "ممثلين جدة للإعلانات والإنتاج | ملامح",
      description: "تحتاج ممثلين في جدة؟ انشر فرصة تمثيل أو كاستينج على ملامح لمشاريع الإعلانات والمحتوى والإنتاج والفعاليات.",
      eyebrow: "ممثلين جدة",
      heading: "ابحث عن ممثلين لمشروعك في جدة عبر فرصة منظمة.",
      intro: "بدل البحث اليدوي بين الحسابات، تتيح ملامح للناشر في جدة إنشاء فرصة واضحة للممثلين ثم استقبال طلبات المهتمين وإدارة القرار داخل المنصة.",
      whyTitle: "مشاريع التمثيل في جدة",
      whyText: "الحملات المحلية والضيافة والسياحة والمطاعم والمحتوى التجاري والإنتاج القصير كلها قد تحتاج ممثلين بأنماط مختلفة. وضوح الدور يساعد على الوصول إلى المرشح الأنسب.",
      projectTypes: ["إعلانات محلية", "ضيافة وسياحة", "مطاعم ومقاهي", "محتوى تجاري", "مشاهد إنتاجية", "فعاليات"],
      tipsTitle: "اكتب فرصة جدة بشكل أدق",
      tips: ["اذكر نوع الدور والظهور المطلوب.", "حدد جدة والموعد المتوقع.", "وضح متطلبات اللهجة أو اللغة.", "بيّن إن كان الدور مدفوعًا وطبيعة الاستخدام."],
      faq: [
        { question: "هل يمكن نشر فرصة لممثلين في جدة فقط؟", answer: "نعم، حدد جدة كمدينة الفرصة واكتب تفاصيل الدور." },
        { question: "هل أحتاج وكالة كاستينج حتى أستخدم ملامح؟", answer: "لا، يمكن للجهة أو صاحب المشروع استخدام ملامح مباشرة كناشر." },
        { question: "هل التواصل مفتوح مع أي موهبة؟", answer: "التواصل في ملامح مرتبط بمسار الطلب أو الفرصة وقرارات الاهتمام والاختيار داخل المنصة." },
      ],
    },
    en: {
      title: "Actors in Jeddah for Ads & Production | MLAMH",
      description: "Need actors in Jeddah? Post an acting or casting opportunity on MLAMH for advertising, branded content, production and events.",
      eyebrow: "ACTORS IN JEDDAH",
      heading: "Source actors for a Jeddah project through a structured opportunity.",
      intro: "Instead of manually searching across profiles, MLAMH lets Jeddah publishers create a clear acting opportunity, receive applications and manage selection in one workflow.",
      whyTitle: "Acting projects in Jeddah",
      whyText: "Local campaigns, hospitality, tourism, restaurants, commercial content and short-form production can all require different kinds of actors. Clear role details improve relevance.",
      projectTypes: ["Local commercials", "Hospitality and tourism", "Restaurants and cafes", "Commercial content", "Production scenes", "Events"],
      tipsTitle: "Write a more precise Jeddah opportunity",
      tips: ["Describe the role and type of appearance.", "State Jeddah and the expected date.", "Add dialect or language requirements.", "Clarify compensation and commercial usage."],
      faq: [
        { question: "Can I post a Jeddah-only actor opportunity?", answer: "Yes. Set Jeddah as the opportunity city and describe the role." },
        { question: "Do I need a casting agency to use MLAMH?", answer: "No. A business or project owner can use MLAMH directly as a publisher." },
        { question: "Is messaging open with any talent?", answer: "Communication on MLAMH is tied to the request or opportunity workflow and the parties' selection or interest state." },
      ],
    },
  },
  {
    slug: "casting-saudi-arabia",
    keywords: ["كاستنج السعودية", "كاستينج السعودية", "شركة كاستنج في السعودية", "casting saudi arabia"],
    ar: {
      title: "كاستنج السعودية | ممثلين ومودلز للمشاريع | ملامح",
      description: "منصة كاستنج في السعودية للجهات وأصحاب المشاريع: انشر فرصة للممثلين أو المودلز، استقبل الطلبات وابدأ الاختيار عبر ملامح.",
      eyebrow: "كاستنج السعودية",
      heading: "الكاستنج في السعودية يبدأ من Brief واضح وفرصة منظمة.",
      intro: "ملامح توفر مسارًا رقميًا للناشرين الذين يحتاجون ممثلين أو مودلز في السعودية. يمكنك نشر فرصة بنفسك أو إرسال Brief لخدمة الكاستينج المُدارة، دون الحاجة إلى عرض ملفات خاصة على صفحة البحث.",
      whyTitle: "مساران حسب طريقة عملك",
      whyText: "إذا كنت تعرف متطلباتك يمكنك نشر فرصة مباشرة. وإذا كان المشروع يحتاج مساعدة في تنظيم الـBrief والبحث والفرز والـShortlist، يمكنك استخدام خدمة الكاستينج المُدارة من ملامح.",
      projectTypes: ["فرص تمثيل", "فرص مودل", "كاستنج إعلانات", "مشاريع محتوى", "فعاليات", "إنتاجات متعددة الأدوار"],
      tipsTitle: "Brief كاستينج أقوى",
      tips: ["حدد الدور أو نوع الموهبة المطلوبة.", "اكتب المدينة والموعد ونطاق العمل.", "وضح المقابل وحقوق الاستخدام.", "افصل بين المتطلبات الضرورية والتفضيلات."],
      faq: [
        { question: "هل أستطيع نشر فرصة بنفسي؟", answer: "نعم. حساب الناشر يتيح إنشاء فرصة وإرسالها للمراجعة ثم استقبال الطلبات بعد نشرها." },
        { question: "هل توجد خدمة كاستينج مُدارة؟", answer: "نعم. يمكنك إرسال Brief لملامح لتحديد نطاق خدمة البحث والفرز والـShortlist والتأكيد حسب المشروع." },
        { question: "هل ملامح شركة كاستنج تقليدية؟", answer: "ملامح منصة كاستينج ومواهب توفر أدوات نشر الفرص والتقديم والاختيار، إضافة إلى خدمة كاستينج مُدارة للمشاريع التي تحتاج تشغيلًا أعمق." },
      ],
    },
    en: {
      title: "Casting in Saudi Arabia | Actors & Models | MLAMH",
      description: "A Saudi casting platform for companies and project owners. Post actor or model opportunities, receive applications and manage selection on MLAMH.",
      eyebrow: "CASTING SAUDI ARABIA",
      heading: "Casting in Saudi Arabia starts with a clear brief and a structured opportunity.",
      intro: "MLAMH gives publishers a digital workflow for sourcing actors and models in Saudi Arabia. Post an opportunity directly or send a brief for managed casting, without exposing private talent profiles on the search landing page.",
      whyTitle: "Two ways to run your casting",
      whyText: "If your requirements are ready, publish the opportunity yourself. If the project needs help with brief structuring, sourcing, screening and shortlist delivery, use MLAMH's managed casting service.",
      projectTypes: ["Acting opportunities", "Model opportunities", "Commercial casting", "Content projects", "Events", "Multi-role productions"],
      tipsTitle: "A stronger casting brief",
      tips: ["Define the role or talent type.", "Add city, timing and work scope.", "Explain compensation and usage rights.", "Separate hard requirements from preferences."],
      faq: [
        { question: "Can I publish a casting opportunity myself?", answer: "Yes. A publisher account can create an opportunity, submit it for review and receive applications after publication." },
        { question: "Is managed casting available?", answer: "Yes. Send a brief to MLAMH to scope sourcing, screening, shortlist delivery and confirmation for the project." },
        { question: "Is MLAMH a traditional casting company?", answer: "MLAMH is a casting and talent platform with opportunity, application and selection tools, plus managed casting for projects that need deeper operational support." },
      ],
    },
  },
  {
    slug: "casting-riyadh",
    keywords: ["كاستنج الرياض", "كاستينج الرياض", "شركة كاستنج الرياض", "casting riyadh"],
    ar: {
      title: "كاستنج الرياض | ممثلين ومودلز للمشاريع | ملامح",
      description: "لديك مشروع في الرياض ويحتاج ممثلين أو مودلز؟ انشر فرصة كاستنج على ملامح أو أرسل Brief لخدمة الكاستينج المُدارة.",
      eyebrow: "كاستنج الرياض",
      heading: "كاستنج الرياض لمشروعك — من الاحتياج إلى فرصة واضحة.",
      intro: "للإعلانات والمحتوى والفعاليات والإنتاج في الرياض، تجمع ملامح مسار النشر والتقديم والاختيار في مكان واحد. الناشر يستطيع نشر الفرصة مباشرة أو طلب إدارة أعمق للكاستينج.",
      whyTitle: "مشاريع تحتاج كاستنج في الرياض",
      whyText: "الرياض تستضيف حملات وفعاليات وإنتاجات ومشاريع محتوى متكررة. صفحة الهبوط تستهدف من يبحث عن خدمة الكاستينج وتوجهه إلى الإجراء المناسب بدل عرض قاعدة المواهب للعامة.",
      projectTypes: ["حملات تجارية", "إنتاج فيديو", "فعاليات", "مطاعم ومتاجر", "محتوى رقمي", "مشاريع متعددة الأدوار"],
      tipsTitle: "ابدأ بطريقة منظمة",
      tips: ["اكتب الهدف من المشروع.", "حدد عدد الأدوار أو المواهب المطلوبة.", "أضف مواعيد التصوير والموقع.", "اختر بين نشر الفرصة بنفسك أو إرسال Brief."],
      faq: [
        { question: "هل ملامح تخدم مشاريع الرياض؟", answer: "نعم، يمكنك تحديد الرياض في الفرصة أو الـBrief وإدارة المشروع من خلال ملامح." },
        { question: "هل أستطيع نشر كاستنج إعلان؟", answer: "نعم، أنشئ فرصة وحدد أنها لمشروع إعلاني مع تفاصيل الاستخدام والمقابل." },
        { question: "ماذا لو لم أعرف كيف أكتب الـBrief؟", answer: "يمكنك استخدام خدمة الكاستينج المُدارة وإرسال المعلومات المتوفرة لتقوم ملامح بمراجعة النطاق." },
      ],
    },
    en: {
      title: "Casting in Riyadh | Actors & Models for Projects | MLAMH",
      description: "Running a project in Riyadh that needs actors or models? Post a casting opportunity on MLAMH or send a brief for managed casting.",
      eyebrow: "CASTING RIYADH",
      heading: "Casting in Riyadh — turn the project need into a clear opportunity.",
      intro: "For advertising, content, events and production in Riyadh, MLAMH brings posting, applications and selection into one workflow. Publishers can post directly or request deeper managed casting support.",
      whyTitle: "Projects that need casting in Riyadh",
      whyText: "Riyadh hosts frequent campaigns, events, productions and content projects. This landing page targets casting service intent and routes visitors to the right action instead of exposing a public talent database.",
      projectTypes: ["Commercial campaigns", "Video production", "Events", "Restaurants and retail", "Digital content", "Multi-role projects"],
      tipsTitle: "Start with a structured brief",
      tips: ["State the project objective.", "Define the number of roles or talent needed.", "Add shoot dates and location.", "Choose between self-posting and managed casting."],
      faq: [
        { question: "Does MLAMH support Riyadh projects?", answer: "Yes. Set Riyadh in the opportunity or brief and manage the workflow through MLAMH." },
        { question: "Can I post a commercial casting?", answer: "Yes. Create an opportunity and explain the commercial usage and compensation." },
        { question: "What if I do not know how to write the brief?", answer: "Use managed casting and send the information you have so MLAMH can review and scope the project." },
      ],
    },
  },
  {
    slug: "commercial-casting-saudi-arabia",
    keywords: ["كاستنج إعلانات", "ممثلين للإعلانات", "مودلز للإعلانات في السعودية", "commercial casting saudi arabia"],
    ar: {
      title: "كاستنج إعلانات في السعودية | ممثلين ومودلز | ملامح",
      description: "انشر كاستنج إعلان في السعودية للوصول إلى ممثلين أو مودلز مناسبين للحملات التجارية والمحتوى والبراندات عبر ملامح.",
      eyebrow: "كاستنج إعلانات",
      heading: "إعلانك يحتاج الوجه المناسب، وليس مجرد عدد أكبر من المتقدمين.",
      intro: "في كاستنج الإعلانات، الملاءمة مع المنتج والجمهور ونبرة الحملة أهم من البحث العام عن وجوه. ملامح تساعدك على نشر فرصة دقيقة توضح الاستخدام، المدينة، مدة التصوير، المقابل ومتطلبات الدور.",
      whyTitle: "ما الذي يختلف في كاستنج الإعلانات؟",
      whyText: "الإعلان قد يتضمن حقوق استخدام، مدة حملة، قنوات نشر، حصرية أو احتياجًا لنمط حضور محدد. كتابة هذه التفاصيل بوضوح تحمي الطرفين وتحسن جودة الاختيار.",
      projectTypes: ["إعلانات فيديو", "صور حملات", "UGC ومحتوى براند", "تصوير منتجات", "إعلانات مطاعم وضيافة", "تجميل وأزياء"],
      tipsTitle: "تفاصيل لا تنسها في إعلان الكاستينج",
      tips: ["حدد قنوات الاستخدام ومدة الحملة عند توفرها.", "وضح هل توجد حصرية أو Buyout.", "اذكر عدد ساعات أو أيام التصوير.", "اربط المتطلبات بصورة البراند والجمهور المستهدف."],
      faq: [
        { question: "هل يمكن نشر فرصة لإعلان تجاري؟", answer: "نعم. اختر نوع الفرصة المناسب واكتب تفاصيل الإعلان والاستخدام والمقابل." },
        { question: "هل أستطيع طلب ممثلين ومودلز في نفس المشروع؟", answer: "يمكن تنظيم المشروع بحسب الأدوار والاحتياجات، وخاصة في المشاريع متعددة الأدوار." },
        { question: "هل توفر ملامح خدمة إدارة كاستنج الإعلان؟", answer: "نعم، للمشاريع التي تحتاج البحث والفرز والـShortlist والتأكيد يمكن إرسال Brief لخدمة الكاستينج المُدارة." },
      ],
    },
    en: {
      title: "Commercial Casting in Saudi Arabia | Actors & Models | MLAMH",
      description: "Post commercial casting opportunities in Saudi Arabia for actors and models needed in brand campaigns, advertising and content.",
      eyebrow: "COMMERCIAL CASTING",
      heading: "Your campaign needs the right face, not simply more applicants.",
      intro: "Commercial casting is about fit with the product, audience and campaign tone. MLAMH helps you publish a precise opportunity that explains usage, city, shoot duration, compensation and role requirements.",
      whyTitle: "What makes commercial casting different?",
      whyText: "Advertising may involve usage rights, campaign duration, channels, exclusivity or a specific on-camera presence. Clear terms protect both sides and improve the selection process.",
      projectTypes: ["Video commercials", "Campaign stills", "UGC and branded content", "Product shoots", "Hospitality advertising", "Beauty and fashion"],
      tipsTitle: "Details to include in a commercial casting",
      tips: ["State usage channels and campaign duration when known.", "Explain exclusivity or buyout terms.", "Add shoot hours or days.", "Tie requirements to the brand and target audience."],
      faq: [
        { question: "Can I post a commercial advertising opportunity?", answer: "Yes. Choose the appropriate opportunity type and include the commercial usage and compensation." },
        { question: "Can one project require actors and models?", answer: "Yes. Multi-role projects can be structured around separate roles and requirements." },
        { question: "Does MLAMH offer managed commercial casting?", answer: "Yes. Projects that need sourcing, screening, shortlist delivery and confirmation can be submitted through the managed casting brief." },
      ],
    },
  },
  {
    slug: "talent-agency-saudi-arabia",
    keywords: ["وكالة مواهب السعودية", "منصة مواهب السعودية", "شركة مواهب السعودية", "talent agency saudi arabia"],
    ar: {
      title: "منصة مواهب في السعودية للناشرين والمواهب | ملامح",
      description: "ملامح منصة مواهب وكاستينج في السعودية لربط الجهات وأصحاب المشاريع بالممثلين والمودلز عبر فرص منظمة وتقديم واختيار داخل المنصة.",
      eyebrow: "منصة مواهب السعودية",
      heading: "إذا كنت تبحث عن وكالة مواهب في السعودية، تعرّف على نموذج ملامح.",
      intro: "ملامح ليست وكالة تمثيل تقليدية؛ هي منصة تربط الناشر بالموهبة من خلال فرص وطلبات واضحة. هذا النموذج يعطي الشركات والوكالات والمتاجر وأصحاب المشاريع قناة واحدة لنشر الاحتياج وإدارة التقديم والاختيار.",
      whyTitle: "الفرق بين المنصة والوكالة التقليدية",
      whyText: "الوكالة التقليدية قد تمثل قائمة محددة من المواهب. ملامح تبني سوقًا منظمًا: الناشر ينشر احتياجه، المواهب المناسبة تتقدم، ثم تُدار حالة الطلب والاختيار والتواصل داخل المنصة.",
      projectTypes: ["شركات إنتاج", "وكالات إعلان", "براندات", "متاجر وأنشطة تجارية", "منظمو فعاليات", "أصحاب مشاريع"],
      tipsTitle: "متى تستخدم ملامح؟",
      tips: ["عندما تحتاج نشر فرصة بدل البحث اليدوي.", "عندما تريد استقبال الطلبات في مكان واحد.", "عندما تحتاج فرز المتقدمين وتتبع قرارات القبول والرفض.", "عندما تريد خدمة كاستينج مُدارة لمشروع أكبر."],
      faq: [
        { question: "هل ملامح وكالة مواهب؟", answer: "ملامح منصة مواهب وكاستينج وليست وكالة تمثيل تقليدية. المواهب والناشرون يستخدمون المنصة لإدارة الفرص والتقديم والاختيار." },
        { question: "هل يمكن للشركات نشر فرص؟", answer: "نعم. الشركات والوكالات والبراندات والمتاجر وأصحاب المشاريع يمكنهم استخدام حساب الناشر بحسب المسار المناسب." },
        { question: "كيف تبدأ الجهة؟", answer: "أنشئ حساب ناشر، أكمل بيانات الجهة، ثم أنشئ طلبًا أو فرصة حسب احتياج المشروع." },
      ],
    },
    en: {
      title: "Talent Platform in Saudi Arabia for Publishers & Talent | MLAMH",
      description: "MLAMH is a Saudi talent and casting platform connecting publishers with actors and models through structured opportunities, applications and selection workflows.",
      eyebrow: "SAUDI TALENT PLATFORM",
      heading: "Searching for a talent agency in Saudi Arabia? See how MLAMH is different.",
      intro: "MLAMH is not a traditional representation agency. It is a platform that connects publishers and talent through clear opportunities and applications, giving companies, agencies, stores and project owners one workflow for sourcing and selection.",
      whyTitle: "Platform versus traditional agency",
      whyText: "A traditional agency may represent a fixed roster. MLAMH operates a structured marketplace: publishers post a need, relevant talent applies, and the application, decision and communication states are managed inside the platform.",
      projectTypes: ["Production companies", "Advertising agencies", "Brands", "Stores and businesses", "Event organizers", "Project owners"],
      tipsTitle: "When to use MLAMH",
      tips: ["When you need to post an opportunity instead of searching manually.", "When you want applications in one place.", "When you need to screen applicants and track decisions.", "When a larger project needs managed casting support."],
      faq: [
        { question: "Is MLAMH a talent agency?", answer: "MLAMH is a talent and casting platform rather than a traditional representation agency. Talent and publishers use it to manage opportunities, applications and selection." },
        { question: "Can companies post opportunities?", answer: "Yes. Companies, agencies, brands, stores and project owners can use the publisher account flow that fits them." },
        { question: "How does a company start?", answer: "Create a publisher account, complete the organization details, then create a request or opportunity based on the project need." },
      ],
    },
  },
];

export function getSeoAcquisitionLanding(slug: string) {
  return SEO_ACQUISITION_LANDINGS.find((landing) => landing.slug === slug) ?? null;
}

export const SEO_ACQUISITION_SLUGS = SEO_ACQUISITION_LANDINGS.map((landing) => landing.slug);
