import { useCallback, useEffect, useState } from "react";
import { FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { ChevronLeft, ChevronRight, LockKeyhole, MessageCircle, MessagesSquare } from "lucide-react-native";

import { AppTabBar } from "@/components/AppTabBar";
import { ScreenSkeleton } from "@/components/ScreenSkeleton";
import { getConversations, getNotifications, type MobileConversation } from "@/lib/api";
import { formatLatinNumber, formatRelativeTime, isRtlLocale } from "@/lib/i18n";
import { useAppLocale } from "@/lib/locale-context";
import { darkTheme } from "@/lib/theme";

export default function MessagesScreen(){
  const {locale}=useAppLocale();const ar=locale==="ar",rtl=isRtlLocale(locale);
  const [items,setItems]=useState<MobileConversation[]>([]),[unread,setUnread]=useState(0),[notifications,setNotifications]=useState(0),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError(null);try{const [result,note]=await Promise.all([getConversations(),getNotifications().catch(()=>null)]);if(!result){setError(ar?"تعذر تحميل المحادثات.":"Unable to load messages.");setItems([]);setUnread(0);}else{setItems(result.items);setUnread(result.unreadCount);}setNotifications(note?.unreadCount??0);}catch{setError(ar?"تعذر تحميل المحادثات. تحقق من الاتصال وحاول مرة أخرى.":"Unable to load messages. Check your connection and try again.");}finally{setLoading(false);setRefreshing(false);}},[ar]);
  useEffect(()=>{void load();},[load]);
  if(loading)return <ScreenSkeleton variant="list" locale={locale} label={ar?"جارٍ تحميل الرسائل":"Loading messages"}/>;
  return <SafeAreaView style={s.screen} edges={["top"]}><FlatList data={items} keyExtractor={(x)=>String(x.id)} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={darkTheme.accent}/>} ListHeaderComponent={<View style={s.header}><View style={[s.titleRow,rtl&&s.rowRtl]}><View style={s.icon}><MessagesSquare size={21} color={darkTheme.accent}/></View><View style={s.flex}><Text style={[s.brand,txt(rtl)]}>{ar?"ملامح":"MLAMH"}</Text><Text style={[s.title,txt(rtl)]}>{ar?"الرسائل":"Messages"}</Text></View>{unread>0?<View style={s.badge}><Text style={s.badgeText}>{unread>99?"99+":formatLatinNumber(unread,locale)}</Text></View>:null}</View><Text style={[s.subtitle,txt(rtl)]}>{ar?"بعد اختيارك تفتح المحادثة، ويبدأ الناشر بالرسالة الأولى. بعدها يصبح التواصل متاحًا للطرفين.":"After you are selected, the conversation opens and the publisher sends the first message. Then both sides can chat."}</Text><View style={[s.policy,rtl&&s.rowRtl]}><LockKeyhole size={15} color={darkTheme.accent}/><Text style={[s.policyText,txt(rtl)]}>{ar?"بيانات التواصل الخاصة لا تظهر في التصفح وتبقى المحادثة مرتبطة بالفرصة.":"Private contact details stay out of discovery and the conversation remains tied to the opportunity."}</Text></View>{error?<View style={s.errorBox}><Text style={[s.error,txt(rtl)]}>{error}</Text><Pressable onPress={()=>void load()}><Text style={s.retry}>{ar?"إعادة المحاولة":"Try again"}</Text></Pressable></View>:null}</View>} renderItem={({item})=><Row item={item} locale={locale}/>} ListEmptyComponent={!error?<View style={s.empty}><View style={s.emptyIcon}><MessageCircle size={26} color={darkTheme.accent}/></View><Text style={[s.emptyTitle,txt(rtl)]}>{ar?"لا توجد محادثات بعد":"No conversations yet"}</Text><Text style={[s.emptyBody,txt(rtl)]}>{ar?"عند اختيارك في إحدى الفرص ستظهر المحادثة هنا تلقائيًا.":"When you are selected for an opportunity, the conversation will appear here automatically."}</Text></View>:null} showsVerticalScrollIndicator={false}/><AppTabBar active="messages" locale={locale} notificationCount={notifications}/></SafeAreaView>;
}
function Row({item,locale}:{item:MobileConversation;locale:"ar"|"en"}){const rtl=locale==="ar",Arrow=rtl?ChevronLeft:ChevronRight;return <Pressable onPress={()=>router.push(`/conversations/${item.id}`)} style={({pressed})=>[s.row,rtl&&s.rowRtl,item.unreadCount>0&&s.rowUnread,pressed&&s.pressed]}>{item.partyImageUrl?<Image source={{uri:item.partyImageUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{item.partyName.slice(0,1).toUpperCase()}</Text></View>}<View style={s.flex}><View style={[s.rowTop,rtl&&s.rowRtl]}><Text numberOfLines={1} style={[s.party,txt(rtl)]}>{item.partyName}</Text><Text style={s.time}>{item.lastActivityAt?formatRelativeTime(item.lastActivityAt,locale):""}</Text></View><Text numberOfLines={1} style={[s.opp,txt(rtl)]}>{item.opportunityTitle??"MLAMH"}</Text><Text numberOfLines={1} style={[s.preview,txt(rtl)]}>{item.latestMessage??(locale==="ar"?"بانتظار رسالة الناشر":"Waiting for the publisher")}</Text></View>{item.unreadCount>0?<View style={s.unread}><Text style={s.unreadText}>{item.unreadCount>99?"99+":formatLatinNumber(item.unreadCount,locale)}</Text></View>:<Arrow size={17} color={darkTheme.muted}/>}</Pressable>}
function txt(rtl:boolean){return{textAlign:rtl?"right" as const:"left" as const,writingDirection:rtl?"rtl" as const:"ltr" as const}}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:darkTheme.background},content:{padding:18,paddingBottom:112},header:{gap:12,marginBottom:18},titleRow:{flexDirection:"row",alignItems:"center",gap:10},rowRtl:{flexDirection:"row-reverse"},icon:{width:42,height:42,borderRadius:15,borderWidth:1,borderColor:"#C9A96244",backgroundColor:"#C9A9620D",alignItems:"center",justifyContent:"center"},flex:{flex:1,minWidth:0},brand:{color:darkTheme.accent,fontSize:10,fontWeight:"900"},title:{color:darkTheme.text,fontSize:27,fontWeight:"900",marginTop:2},badge:{minWidth:27,height:27,borderRadius:14,backgroundColor:darkTheme.accent,paddingHorizontal:7,alignItems:"center",justifyContent:"center"},badgeText:{color:darkTheme.background,fontSize:9,fontWeight:"900"},subtitle:{color:darkTheme.muted,fontSize:12,lineHeight:19},policy:{flexDirection:"row",alignItems:"center",gap:8,padding:12,borderWidth:1,borderColor:"#C9A96233",borderRadius:15,backgroundColor:"#C9A96208"},policyText:{flex:1,color:darkTheme.muted,fontSize:10,lineHeight:16},errorBox:{gap:8,padding:12,borderRadius:14,backgroundColor:"#E59A9A0E"},error:{color:"#E59A9A",fontSize:11},retry:{color:darkTheme.accent,fontWeight:"800"},row:{minHeight:90,flexDirection:"row",alignItems:"center",gap:11,padding:12,marginBottom:9,borderWidth:1,borderColor:darkTheme.border,borderRadius:19,backgroundColor:darkTheme.surface},rowUnread:{borderColor:"#C9A96255",backgroundColor:"#C9A96208"},pressed:{opacity:.68},avatar:{width:48,height:48,borderRadius:24},avatarFallback:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:darkTheme.border,alignItems:"center",justifyContent:"center"},avatarText:{color:darkTheme.accent,fontSize:17,fontWeight:"900"},rowTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},party:{flex:1,color:darkTheme.text,fontSize:14,fontWeight:"900"},time:{color:darkTheme.muted,fontSize:8},opp:{color:darkTheme.accent,fontSize:9,fontWeight:"800",marginTop:3},preview:{color:darkTheme.muted,fontSize:10,marginTop:4},unread:{minWidth:22,height:22,borderRadius:11,backgroundColor:darkTheme.accent,alignItems:"center",justifyContent:"center",paddingHorizontal:5},unreadText:{color:darkTheme.background,fontSize:8,fontWeight:"900"},empty:{minHeight:270,alignItems:"center",justifyContent:"center",gap:10,padding:26},emptyIcon:{width:52,height:52,borderRadius:18,borderWidth:1,borderColor:"#C9A96244",backgroundColor:"#C9A9620D",alignItems:"center",justifyContent:"center"},emptyTitle:{color:darkTheme.text,fontSize:17,fontWeight:"900"},emptyBody:{color:darkTheme.muted,fontSize:11,lineHeight:18,maxWidth:330}});
