import { useCallback, useEffect, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { BellRing, ChevronLeft, ChevronRight } from "lucide-react-native";

import { AppTabBar } from "@/components/AppTabBar";
import { PublisherTabBar } from "@/components/PublisherTabBar";
import { ScreenSkeleton } from "@/components/ScreenSkeleton";
import { getMobileAccountContext } from "@/lib/account";
import { getNotifications, markNotificationRead, type MobileNotification } from "@/lib/api";
import { formatRelativeTime, isRtlLocale } from "@/lib/i18n";
import { useAppLocale } from "@/lib/locale-context";
import { leaveAuthenticatedScreen } from "@/lib/navigation";
import { useNotificationSync } from "@/lib/notifications-context";
import { darkTheme, radii, spacing, typography } from "@/lib/theme";

type NotificationFilter = "all" | "unread";

export default function NotificationsScreen() {
  const { locale } = useAppLocale();
  const ar = locale === "ar";
  const rtl = isRtlLocale(locale);
  const Back = rtl ? ChevronRight : ChevronLeft;
  const { refresh: refreshBadge } = useNotificationSync();
  const [items,setItems]=useState<MobileNotification[]>([]),[unread,setUnread]=useState(0),[accountType,setAccountType]=useState<"talent"|"publisher">("talent"),[filter,setFilter]=useState<NotificationFilter>("all"),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);

  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError(null);try{const [result,account]=await Promise.all([getNotifications(),getMobileAccountContext().catch(()=>null)]);if(!result){router.replace({pathname:"/login",params:{next:"/notifications"}});return;}setAccountType(account?.type==="publisher"?"publisher":"talent");setItems(result.items);setUnread(result.unreadCount);void refreshBadge();}catch{setError(ar?"تعذر تحميل الإشعارات. تحقق من الاتصال وحاول مرة أخرى.":"Unable to load notifications. Check your connection and try again.");}finally{setLoading(false);setRefreshing(false);}},[ar,refreshBadge]);
  useEffect(()=>{void load()},[load]);

  async function openNotification(item:MobileNotification){if(!item.isRead){const updated=await markNotificationRead(item.id);if(updated){setItems((current)=>current.map((entry)=>entry.id===item.id?{...entry,isRead:true}:entry));setUnread((count)=>Math.max(0,count-1));void refreshBadge();}}const target=item.target;if(target.type==="conversation")return router.push(`/conversations/${target.id}`);if(target.type==="publisher_opportunity")return router.push(`/publisher/opportunities/${target.id}`);if(target.type==="opportunity")return router.push(`/opportunities/${target.id}`);if(target.type==="talent_applications")return router.push("/applications");}

  if(loading)return <ScreenSkeleton variant="list" locale={locale} label={ar?"جارٍ تحميل الإشعارات":"Loading notifications"}/>;
  const visible=filter==="unread"?items.filter((item)=>!item.isRead):items;
  const homeRoute=accountType==="publisher"?"/publisher":"/profile";

  return <SafeAreaView style={s.screen} edges={["top"]}>
    <FlatList data={visible} keyExtractor={(item)=>String(item.id)} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={darkTheme.accent}/>} ItemSeparatorComponent={()=><View style={{height:9}}/>} ListHeaderComponent={<View style={s.header}>
      <View style={[s.topRow,rtl&&s.rowRtl]}><Pressable accessibilityRole="button" accessibilityLabel={ar?"رجوع":"Back"} onPress={()=>leaveAuthenticatedScreen(homeRoute)} style={s.back}><Back size={20} color={darkTheme.text}/></Pressable><View style={s.flex}><Text style={[s.brand,txt(rtl)]}>{ar?"ملامح":"MLAMH"}</Text><Text accessibilityRole="header" style={[s.title,txt(rtl)]}>{ar?"الإشعارات":"Notifications"}</Text></View>{unread>0?<View style={s.badge}><Text style={s.badgeText}>{unread>99?"99+":unread}</Text></View>:null}</View>
      <View accessibilityRole="tablist" style={[s.filters,rtl&&s.rowRtl]}><Filter active={filter==="all"} label={ar?"الكل":"All"} onPress={()=>setFilter("all")}/><Filter active={filter==="unread"} label={ar?"غير المقروء":"Unread"} onPress={()=>setFilter("unread")}/></View>
      {error?<View style={s.errorBox}><Text style={[s.error,txt(rtl)]}>{error}</Text><Pressable onPress={()=>void load()}><Text style={s.retry}>{ar?"إعادة المحاولة":"Try again"}</Text></Pressable></View>:null}
    </View>} renderItem={({item})=><NotificationRow item={item} locale={locale} onPress={()=>void openNotification(item)}/>} ListEmptyComponent={!error?<View style={s.empty}><View style={s.emptyIcon}><BellRing size={24} color={darkTheme.accent}/></View><Text style={[s.emptyTitle,txt(rtl)]}>{filter==="unread"?(ar?"لا يوجد شيء ينتظر قراءتك":"Nothing waiting to be read"):(ar?"لا توجد إشعارات بعد":"No notifications yet")}</Text><Text style={[s.emptyBody,txt(rtl)]}>{ar?"ستظهر هنا تحديثات الحساب والفرص والرسائل التي تحتاج انتباهك.":"Account, opportunity and message updates that need your attention will appear here."}</Text></View>:null} showsVerticalScrollIndicator={false}/>
    {accountType==="publisher"?<PublisherTabBar active="notifications" locale={locale} notificationCount={unread}/>:<AppTabBar active="notifications" locale={locale} notificationCount={unread}/>} 
  </SafeAreaView>;
}
function Filter({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable accessibilityRole="tab" accessibilityState={{selected:active}} onPress={onPress} style={[s.filter,active&&s.filterActive]}><Text style={[s.filterText,active&&s.filterTextActive]}>{label}</Text></Pressable>}
function NotificationRow({item,locale,onPress}:{item:MobileNotification;locale:"ar"|"en";onPress:()=>void}){const rtl=locale==="ar",ar=locale==="ar";return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.row,!item.isRead&&s.rowUnread,pressed&&s.pressed]}><View style={[s.rowTop,rtl&&s.rowRtl]}><View style={[s.category,!item.isRead&&s.categoryUnread]}><Text style={[s.categoryText,!item.isRead&&s.categoryTextUnread]}>{categoryLabel(item.category,locale)}</Text></View><View style={[s.timeWrap,rtl&&s.rowRtl]}>{!item.isRead?<View style={s.dot}/>:null}<Text style={s.time}>{formatRelativeTime(item.createdAt,locale)}</Text></View></View><Text numberOfLines={2} style={[s.rowTitle,txt(rtl)]}>{item.title}</Text>{item.body?<Text numberOfLines={3} style={[s.rowBody,txt(rtl)]}>{item.body}</Text>:null}<Text style={[s.openText,txt(rtl)]}>{item.target.type==="none"?(ar?"للعلم":"For your information"):(ar?"فتح التحديث":"Open update")}</Text></Pressable>}
function categoryLabel(category:string|null|undefined,locale:"ar"|"en"){const ar=locale==="ar";const map:Record<string,[string,string]>={message:["رسالة","Message"],application:["طلب","Application"],opportunity:["فرصة","Opportunity"],profile:["الملف","Profile"],review:["مراجعة","Review"],system:["النظام","System"]};const value=category?map[category.toLowerCase()]:null;return value?(ar?value[0]:value[1]):(ar?"تحديث":"Update")}
function txt(rtl:boolean){return{textAlign:rtl?"right" as const:"left" as const,writingDirection:rtl?"rtl" as const:"ltr" as const}}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:darkTheme.background},content:{paddingHorizontal:spacing.lg,paddingBottom:112},header:{paddingTop:8,paddingBottom:16,gap:14},topRow:{minHeight:52,flexDirection:"row",alignItems:"center",gap:11},rowRtl:{flexDirection:"row-reverse"},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:darkTheme.border,backgroundColor:darkTheme.surface,alignItems:"center",justifyContent:"center"},flex:{flex:1,minWidth:0},brand:{color:darkTheme.accent,fontSize:9,fontWeight:"900"},title:{...typography.pageTitle,color:darkTheme.text,marginTop:2},badge:{minWidth:28,height:28,borderRadius:14,backgroundColor:darkTheme.accent,alignItems:"center",justifyContent:"center",paddingHorizontal:6},badgeText:{color:darkTheme.background,fontSize:9,fontWeight:"900"},filters:{flexDirection:"row",gap:8},filter:{minHeight:38,borderRadius:19,borderWidth:1,borderColor:darkTheme.border,backgroundColor:darkTheme.surface,paddingHorizontal:16,alignItems:"center",justifyContent:"center"},filterActive:{borderColor:darkTheme.accent,backgroundColor:darkTheme.chip},filterText:{color:darkTheme.muted,fontSize:11,fontWeight:"800"},filterTextActive:{color:darkTheme.accent},errorBox:{borderWidth:1,borderColor:"#E59A9A33",backgroundColor:darkTheme.dangerSurface,borderRadius:radii.md,padding:12,gap:6},error:{color:darkTheme.danger,fontSize:11},retry:{color:darkTheme.accent,fontWeight:"900",fontSize:11},row:{borderWidth:1,borderColor:darkTheme.border,borderRadius:radii.lg,backgroundColor:darkTheme.surface,padding:14,gap:7},rowUnread:{borderColor:"#C9A96255",backgroundColor:"#C9A96208"},pressed:{opacity:.7},rowTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},category:{borderRadius:999,borderWidth:1,borderColor:darkTheme.border,paddingHorizontal:8,paddingVertical:4},categoryUnread:{borderColor:"#C9A96255"},categoryText:{color:darkTheme.muted,fontSize:8,fontWeight:"800"},categoryTextUnread:{color:darkTheme.accent},timeWrap:{flexDirection:"row",alignItems:"center",gap:5},dot:{width:6,height:6,borderRadius:3,backgroundColor:darkTheme.accent},time:{color:darkTheme.muted,fontSize:8},rowTitle:{color:darkTheme.text,fontSize:14,lineHeight:20,fontWeight:"900"},rowBody:{color:darkTheme.muted,fontSize:11,lineHeight:18},openText:{color:darkTheme.accent,fontSize:9,fontWeight:"900",marginTop:2},empty:{minHeight:360,alignItems:"center",justifyContent:"center",gap:10,padding:26},emptyIcon:{width:52,height:52,borderRadius:18,borderWidth:1,borderColor:"#C9A96244",backgroundColor:"#C9A9620D",alignItems:"center",justifyContent:"center"},emptyTitle:{color:darkTheme.text,fontSize:17,fontWeight:"900",textAlign:"center"},emptyBody:{color:darkTheme.muted,fontSize:11,lineHeight:18,maxWidth:330,textAlign:"center"}});