import Link from "next/link";
import { notFound } from "next/navigation";

import { AdminBadge, AdminCard, AdminGrid, AdminPageContainer, AdminPageHeader, AdminStatCard } from "@/components/admin/ui";
import { getAdminLanguage } from "@/lib/admin/i18n";
import { requireAdminAccess } from "@/lib/auth/require-admin";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";
type PageProps = { params: Promise<{ id: string }>; searchParams: Promise<{ lang?: string }> };
function statusLabel(value:string|null,ar:boolean){if(!value)return "—";const m:Record<string,[string,string]>={draft:["مسودة","Draft"],pending:["بانتظار الاعتماد","Pending approval"],approved:["معتمدة","Approved"],active:["نشطة","Active"],paused:["متوقفة مؤقتًا","Paused"],completed:["مكتملة","Completed"],ready:["جاهز","Ready"],review:["مراجعة","Review"],approval:["بانتظار قرار","Waiting approval"],published:["منشور","Published"],measured:["تم القياس","Measured"],failed:["فشل","Failed"],scheduled:["مجدول","Scheduled"],waiting_approval:["بانتظار الاعتماد","Waiting approval"]};return m[value]?.[ar?0:1]??value.replaceAll("_"," ");}

export default async function CampaignWorkspacePage({params,searchParams}:PageProps){
  await requireAdminAccess();
  const [{id},{lang}]=await Promise.all([params,searchParams]);
  const campaignId=Number(id);
  if(!Number.isInteger(campaignId)||campaignId<=0)notFound();
  const language=getAdminLanguage(lang);
  const ar=language==="ar";
  const db=createAdminClient();
  const [campaignResult,contentResult,creativesResult,tasksResult]=await Promise.all([
    db.from("marketing_campaigns").select("id,name,objective,status,start_at,end_at,budget,channels,owner,utm_campaign,created_at").eq("id",campaignId).maybeSingle(),
    db.from("marketing_content").select("id,title,hook,caption,channel,status,content_type,scheduled_at,published_at,created_at").eq("campaign_id",campaignId).order("created_at",{ascending:false}).limit(100),
    db.from("marketing_creatives").select("id,content_id,type,platform,aspect_ratio,status,preview_path,version,created_at").eq("campaign_id",campaignId).order("created_at",{ascending:false}).limit(100),
    db.from("marketing_tasks").select("id,title,status,agent_id,channel,approval_status,created_at").eq("campaign_id",campaignId).order("created_at",{ascending:false}).limit(100),
  ]);
  const campaign=campaignResult.data;
  if(!campaign)notFound();
  const contents=contentResult.data??[];
  const creatives=creativesResult.data??[];
  const tasks=tasksResult.data??[];
  const contentIds=contents.map(item=>item.id);
  const jobsResult=contentIds.length?await db.from("marketing_channel_jobs").select("id,content_id,channel,status,scheduled_at,published_at,last_error,created_at").in("content_id",contentIds).order("created_at",{ascending:false}):{data:[],error:null};
  const jobs=jobsResult.data??[];
  const readyCreatives=creatives.filter(item=>["ready","approved"].includes(item.status)).length;
  const publishedJobs=jobs.filter(item=>item.status==="published").length;
  const attentionJobs=jobs.filter(item=>["failed","waiting_approval"].includes(item.status)).length;
  const waitingContent=contents.filter(item=>item.status==="approval").length;
  const pendingTasks=tasks.filter(item=>item.approval_status==="pending").length;

  return <AdminPageContainer>
    <div className="mb-4"><Link href={`/admin/marketing/campaigns?lang=${language}`} className="text-xs text-gold/70 hover:text-gold">{ar?"← العودة إلى الحملات":"← Back to campaigns"}</Link></div>
    <AdminPageHeader eyebrow={ar?"MLAMH · مساحة عمل الحملة":"MLAMH · CAMPAIGN WORKSPACE"} title={campaign.name} description={campaign.objective??(ar?"مساحة تشغيل موحدة للحملة: المحتوى والكرياتيف والاعتماد وحالة النشر في شاشة واحدة.":"Unified campaign operations: content, creative, approvals, and publishing state in one workspace.")} />
    <AdminGrid className="mb-6 md:grid-cols-4"><AdminStatCard label={ar?"المحتوى":"Content"} value={contents.length}/><AdminStatCard label={ar?"الكرياتيف":"Creative assets"} value={creatives.length}/><AdminStatCard label={ar?"ينتظر قرارًا":"Awaiting decision"} value={waitingContent+pendingTasks}/><AdminStatCard label={ar?"منشور":"Published jobs"} value={publishedJobs}/></AdminGrid>
    <AdminCard className="mb-6 p-5"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><AdminBadge variant="gold">{statusLabel(campaign.status,ar)}</AdminBadge>{Number(campaign.budget??0)===0?<AdminBadge variant="success">Zero-Budget</AdminBadge>:null}{readyCreatives>0?<AdminBadge variant="muted">{readyCreatives} {ar?"كرياتيف جاهز":"creative ready"}</AdminBadge>:null}</div><div className="mt-4 grid gap-4 text-xs sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-white/30">{ar?"المالك":"Owner"}</p><p className="mt-1 text-white/70">{campaign.owner??"—"}</p></div><div><p className="text-white/30">{ar?"القنوات":"Channels"}</p><p className="mt-1 text-white/70">{(campaign.channels??[]).join(" · ")||"—"}</p></div><div><p className="text-white/30">{ar?"الميزانية":"Budget"}</p><p className="mt-1 text-white/70">{campaign.budget??"—"}</p></div><div><p className="text-white/30">{ar?"التتبع":"Tracking"}</p><p className="mt-1 text-white/70">{campaign.utm_campaign??"—"}</p></div><div><p className="text-white/30">{ar?"يحتاج انتباه":"Needs attention"}</p><p className={`mt-1 ${attentionJobs>0?"text-amber-200":"text-emerald-200"}`}>{attentionJobs}</p></div></div></div><div className="grid w-full gap-2 sm:grid-cols-2 xl:w-72 xl:grid-cols-1"><Link href={`/admin/marketing/content?lang=${language}&campaign_id=${campaign.id}`} className="rounded-xl border border-gold/25 bg-gold/[0.08] px-4 py-3 text-center text-sm font-medium text-gold">{ar?"محتوى الحملة":"Campaign content"}</Link><Link href={`/admin/marketing/creative?lang=${language}&campaign_id=${campaign.id}`} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-center text-sm text-white/65">{ar?"كرياتيف الحملة":"Campaign creative"}</Link><Link href={`/admin/marketing/social?lang=${language}&campaign_id=${campaign.id}`} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-center text-sm text-white/65">{ar?"الجدولة والنشر":"Scheduling & publishing"}</Link><Link href={`/admin/marketing/approvals?lang=${language}`} className="rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-center text-sm text-white/65">{ar?"القرارات والاعتمادات":"Decisions"}</Link></div></div></AdminCard>
    {attentionJobs>0?<AdminCard className="mb-5 border-red-300/15 bg-red-300/[0.04] p-4 text-sm text-red-100">{ar?`يوجد ${attentionJobs} تنفيذ نشر يحتاج مراجعة.`:`${attentionJobs} publishing job(s) need review.`}</AdminCard>:null}
    <div className="mb-6 grid gap-5 xl:grid-cols-2">
      <AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><h2 className="text-base text-white">{ar?"المحتوى":"Content"}</h2><Link href={`/admin/marketing/content?lang=${language}&campaign_id=${campaign.id}`} className="text-xs text-gold/70">{ar?"كل محتوى الحملة ←":"Campaign content →"}</Link></div><div className="divide-y divide-white/[0.06]">{contents.length===0?<div className="p-5 text-sm text-white/35">{ar?"لا يوجد محتوى مرتبط بهذه الحملة بعد.":"No content linked to this campaign yet."}</div>:contents.map(item=><div key={item.id} className="p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-white/75">{item.title??item.hook??`Content #${item.id}`}</p><p className="mt-1 text-xs text-white/35">{item.content_type??"—"} · {item.channel??"—"}</p></div><AdminBadge variant={["published","measured"].includes(item.status)?"success":item.status==="approval"?"warning":"muted"}>{statusLabel(item.status,ar)}</AdminBadge></div></div>)}</div></AdminCard>
      <AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><h2 className="text-base text-white">{ar?"الكرياتيف":"Creative"}</h2><Link href={`/admin/marketing/creative?lang=${language}&campaign_id=${campaign.id}`} className="text-xs text-gold/70">{ar?"كل كرياتيف الحملة ←":"Campaign creative →"}</Link></div><div className="divide-y divide-white/[0.06]">{creatives.length===0?<div className="p-5 text-sm text-white/35">{ar?"لا توجد أصول إبداعية مرتبطة بهذه الحملة بعد.":"No creative assets linked to this campaign yet."}</div>:creatives.map(item=><Link key={item.id} href={`/admin/marketing/creative/${item.id}?lang=${language}`} className="block p-4 transition hover:bg-white/[0.02]"><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-white/75">{item.type} · {item.platform??"—"}</p><p className="mt-1 text-xs text-white/35">{item.aspect_ratio??"—"} · v{item.version}</p></div><AdminBadge variant={["ready","approved","published"].includes(item.status)?"success":"muted"}>{statusLabel(item.status,ar)}</AdminBadge></div></Link>)}</div></AdminCard>
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><AdminCard className="overflow-hidden"><div className="border-b border-white/[0.07] px-5 py-4"><h2 className="text-base text-white">{ar?"مهام الفريق":"Team tasks"}</h2></div><div className="divide-y divide-white/[0.06]">{tasks.length===0?<div className="p-5 text-sm text-white/35">{ar?"لا توجد مهام مرتبطة بالحملة.":"No campaign tasks."}</div>:tasks.slice(0,12).map(task=><div key={task.id} className="p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm text-white/75">{task.title}</p><p className="mt-1 text-xs text-white/35">{task.agent_id??"—"} · {task.channel??"internal"}</p></div><span className="text-xs text-gold/70">{statusLabel(task.status,ar)}</span></div></div>)}</div></AdminCard><AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><h2 className="text-base text-white">{ar?"التنفيذ الاجتماعي":"Social execution"}</h2><Link href={`/admin/marketing/social?lang=${language}&campaign_id=${campaign.id}`} className="text-xs text-gold/70">{ar?"فتح المجدول ←":"Open scheduler →"}</Link></div><div className="divide-y divide-white/[0.06]">{jobs.length===0?<div className="p-5 text-sm text-white/35">{ar?"لا توجد عمليات نشر مرتبطة بالحملة.":"No publishing jobs for this campaign."}</div>:jobs.slice(0,12).map(job=><div key={job.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white/75">{contents.find(item=>item.id===job.content_id)?.title??`Content #${job.content_id}`}</p><p className="mt-1 text-xs text-white/35">{job.channel}</p>{job.last_error?<p className="mt-1 text-xs text-red-200/70">{job.last_error}</p>:null}</div><span className="text-xs text-gold/70">{statusLabel(job.status,ar)}</span></div></div>)}</div></AdminCard></div>
  </AdminPageContainer>;
}
