import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { BriefcaseBusiness, House, MessageCircle, Plus, Search, UserRound, type LucideIcon } from "lucide-react-native";

import { getMobileAccountContext } from "@/lib/account";
import type { AppLocale } from "@/lib/i18n";
import { darkTheme } from "@/lib/theme";

type Theme = typeof darkTheme;
type PublisherTab = "dashboard" | "talents" | "create" | "messages" | "profile" | "notifications";
type ViewerKind = "checking" | "publisher" | "other";
type TabDefinition = { key: Exclude<PublisherTab,"notifications">; path:"/publisher"|"/talents"|"/publisher/opportunities/new"|"/publisher/messages"|"/publisher/profile"; ar:string; en:string; icon:LucideIcon };

// Physical order is stable in both locales. This mirrors the talent bar contract:
// the profile sits on the physical right edge, then Messages, Create, Talents, Home.
const tabs:TabDefinition[]=[
  {key:"dashboard",path:"/publisher",ar:"الرئيسية",en:"Home",icon:House},
  {key:"talents",path:"/talents",ar:"المواهب",en:"Talents",icon:Search},
  {key:"create",path:"/publisher/opportunities/new",ar:"فرصة",en:"Create",icon:Plus},
  {key:"messages",path:"/publisher/messages",ar:"الرسائل",en:"Messages",icon:MessageCircle},
  {key:"profile",path:"/publisher/profile",ar:"الملف",en:"Profile",icon:UserRound},
];

export function PublisherTabBar({active,locale,theme=darkTheme,unreadCount=0}:{active:PublisherTab;locale:AppLocale;theme?:Theme;unreadCount?:number;notificationCount?:number}){
  const insets=useSafeAreaInsets();const{width}=useWindowDimensions();const compact=width<=380;const styles=createStyles(theme);const ar=locale==="ar";const[viewer,setViewer]=useState<ViewerKind>(active==="talents"?"checking":"publisher");
  useEffect(()=>{if(active!=="talents")return;let mounted=true;void getMobileAccountContext().then((account)=>{if(mounted)setViewer(account?.type==="publisher"?"publisher":"other")}).catch(()=>{if(mounted)setViewer("other")});return()=>{mounted=false}},[active]);
  if(active==="talents"&&viewer!=="publisher")return <View style={[styles.outer,compact&&styles.outerCompact,{paddingBottom:Math.max(insets.bottom,8)}]}><View style={[styles.publicShell,compact&&styles.shellCompact]}><Pressable accessibilityRole="button" onPress={()=>router.replace("/opportunities")} style={({pressed})=>[styles.publicAction,compact&&styles.tabCompact,pressed&&styles.pressed]}><BriefcaseBusiness size={compact?17:18} color={theme.muted}/><Text style={[styles.publicActionText,compact&&styles.labelCompact,ar&&styles.arabicText]}>{ar?"الفرص":"Opportunities"}</Text></Pressable><View style={[styles.publicCurrent,compact&&styles.tabCompact]}><Search size={compact?18:19} color={theme.accent}/><Text style={[styles.publicCurrentText,compact&&styles.labelCompact,ar&&styles.arabicText]}>{ar?"المواهب":"Talents"}</Text></View><Pressable accessibilityRole="button" onPress={()=>router.push(viewer==="checking"?"/login":"/signup")} style={({pressed})=>[styles.publicAction,compact&&styles.tabCompact,pressed&&styles.pressed]}><UserRound size={compact?17:18} color={theme.muted}/><Text style={[styles.publicActionText,compact&&styles.labelCompact,ar&&styles.arabicText]}>{ar?(viewer==="checking"?"الدخول":"انضم"):(viewer==="checking"?"Sign in":"Join")}</Text></Pressable></View></View>;
  return <View style={[styles.outer,compact&&styles.outerCompact,{paddingBottom:Math.max(insets.bottom,8)}]}><View accessibilityRole="tablist" style={[styles.shell,compact&&styles.shellCompact]}>{tabs.map((tab)=>{const selected=active===tab.key,badge=tab.key==="messages"?unreadCount:0,label=ar?tab.ar:tab.en,Icon=tab.icon;return <Pressable key={tab.key} accessibilityRole="tab" accessibilityLabel={badge>0?`${label}, ${badge>99?"99+":badge}`:label} accessibilityState={{selected}} onPress={()=>router.replace(tab.path)} style={({pressed})=>[styles.tab,compact&&styles.tabCompact,selected&&styles.tabSelected,pressed&&styles.pressed]}><View style={styles.iconWrap}><Icon size={compact?17:18} color={selected?theme.accent:theme.muted}/>{badge>0?<View style={[styles.badge,ar&&styles.badgeRtl]}><Text style={styles.badgeText}>{badge>99?"99+":badge}</Text></View>:null}</View><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.82} style={[styles.label,compact&&styles.labelCompact,ar&&styles.arabicText,selected&&styles.labelSelected]}>{label}</Text></Pressable>})}</View></View>;
}
function createStyles(theme:Theme){return StyleSheet.create({outer:{backgroundColor:theme.background,paddingHorizontal:10,paddingTop:7},outerCompact:{paddingHorizontal:6},shell:{minHeight:68,flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:theme.border,borderRadius:24,backgroundColor:theme.nav,paddingHorizontal:5,paddingVertical:6},shellCompact:{minHeight:64,borderRadius:21,paddingHorizontal:3,paddingVertical:5},tab:{flex:1,minHeight:54,borderRadius:17,alignItems:"center",justifyContent:"center",gap:5,paddingHorizontal:2},tabCompact:{minHeight:50,borderRadius:15,gap:3,paddingHorizontal:1},tabSelected:{backgroundColor:theme.chip},iconWrap:{minHeight:20,alignItems:"center",justifyContent:"center",position:"relative"},label:{color:theme.muted,fontSize:9,lineHeight:13,fontWeight:"700",textAlign:"center",flexShrink:1},labelCompact:{fontSize:8,lineHeight:11},labelSelected:{color:theme.accent,fontWeight:"900"},badge:{position:"absolute",top:-6,right:-11,minWidth:16,height:16,paddingHorizontal:3,borderRadius:8,alignItems:"center",justifyContent:"center",backgroundColor:theme.accent},badgeRtl:{right:undefined,left:-11},badgeText:{color:theme.background,fontSize:8,fontWeight:"900"},publicShell:{minHeight:68,flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:theme.border,borderRadius:24,backgroundColor:theme.nav,paddingHorizontal:6,paddingVertical:6},publicAction:{flex:1,minHeight:54,borderRadius:17,alignItems:"center",justifyContent:"center",gap:5},publicActionText:{color:theme.muted,fontSize:9,fontWeight:"700",textAlign:"center"},publicCurrent:{flex:1,minHeight:54,borderRadius:17,alignItems:"center",justifyContent:"center",gap:5,backgroundColor:theme.chip},publicCurrentText:{color:theme.accent,fontSize:9,fontWeight:"900",textAlign:"center"},pressed:{opacity:.65},arabicText:{letterSpacing:0,writingDirection:"rtl"}})}
