import Link from "next/link";
import { MarketingLiveRefresh } from "@/components/admin/marketing/MarketingLiveRefresh";
import { AdminCard, AdminPageContainer, AdminPageHeader } from "@/components/admin/ui";
import { getAdminLanguage } from "@/lib/admin/i18n";
import { requireAdminAccess } from "@/lib/auth/require-admin";
import { createAdminClient } from "@/lib/supabase/admin";

export const metadata={title:"MLAMH Marketing Command Center — Admin",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
type PageProps={searchParams:Promise<{lang?:string}>};
type Activity={id:number;agent_id:string|null;task_id:number|null;action:string;reason:string|null;channel:string|null;error:string|null;created_at:string};
const actionAr:Record<string,string>={task_created:"بدأ مهمة جديدة",task_completed:"أكمل المهمة",task_retry_queued:"أعاد المهمة للمحاولة",task_failed:"تعذر تنفيذ المهمة",resolved:"حدد جهة الاتصال",lead:"جهز عميلاً محتملاً",brief:"جهز موجز العمل",matched:"طابق المواهب",draft_prepared:"جهز مسودة",approval_requested:"طلب قرارك",deduplicated:"منع تنفيذًا مكررًا"};
function fmt(v:string,ar:boolean){return new Intl.DateTimeFormat(ar?"ar-SA":"en-US",{hour:"numeric",minute:"2-digit",day:"numeric",month:"short"}).format(new Date(v))}
function statusText(v:string,ar:boolean){const x:Record<string,[string,string]>={working:["يعمل الآن","Working now"],idle:["جاهز","Ready"],waiting_approval:["ينتظر قرارًا","Waiting for decision"],scheduled:["مجدول","Scheduled"],error:["يحتاج مراجعة","Needs review"],paused:["متوقف","Paused"]};return x[v]?.[ar?0:1]??v.replaceAll("_"," ")}
export default async function MarketingHubOverviewPage({searchParams}:PageProps){
 await requireAdminAccess();const{lang}=await searchParams;const language=getAdminLanguage(lang),ar=language==="ar",db=createAdminClient();
 const [approvals,tasks,agents,activity,content,integrations,applications,talents]=await Promise.all([
  db.from("marketing_approvals").select("id,task_id,approval_level,reason,channel,risk_level,status,created_at").eq("status","pending").order("created_at",{ascending:false}).limit(3),
  db.from("marketing_tasks").select("id,title,status,agent_id,channel,priority,created_at").in("status",["running","queued","scheduled","waiting_approval"]).order("created_at",{ascending:false}).limit(8),
  db.from("marketing_agents").select("id,name,role,status,current_task_id,last_action_at,tasks_completed,tasks_failed").eq("is_active",true).order("id"),
  db.from("marketing_agent_activity").select("id,agent_id,task_id,action,reason,channel,error,created_at").order("created_at",{ascending:false}).limit(8),
  db.from("marketing_content").select("id,title,caption,hook,channel,status,content_type,created_at").order("created_at",{ascending:false}).limit(4),
  db.from("marketing_integrations").select("provider,status").order("provider"),
  db.from("opportunity_applications").select("id",{count:"exact",head:true}),
  db.from("profiles").select("id",{count:"exact",head:true}).eq("account_type","talent")
 ]);
 const team=agents.data??[],names=new Map(team.map((a:any)=>[a.id,a.name])),active=team.filter((a:any)=>a.status==="working").length,pending=approvals.data??[],work=tasks.data??[],recent=activity.data??[] as Activity[],creative=content.data??[],connected=(integrations.data??[]).filter((i:any)=>i.status==="connected").length;
 const headline=pending.length>0?(ar?`${pending.length} قرار ينتظر اعتمادك`:`${pending.length} decision${pending.length>1?"s":""} need your approval`):active>0?(ar?`${active} من فريق التسويق يعمل الآن`:`${active} marketing agent${active>1?"s are":" is"} working now`):(ar?"فريق التسويق جاهز للدورة التالية":"Marketing team is ready for the next cycle");
 return <AdminPageContainer><MarketingLiveRefresh intervalMs={7000}/><AdminPageHeader eyebrow="MLAMH · MARKETING COMMAND" title={ar?"مركز قيادة التسويق":"Marketing Command Center"} description={ar?"اعرف ما يحدث الآن، ما الذي يحتاج قرارك، وما الذي ينجزه الفريق — دون ضوضاء تشغيلية.":"Know what is happening, what needs your decision, and what the team is delivering — without operational noise."}/>
 <section className="mb-6 overflow-hidden rounded-[28px] border border-gold/20 bg-gradient-to-br from-gold/[0.12] via-white/[0.025] to-black/30 p-6 md:p-8"><div className="grid gap-8 xl:grid-cols-[1.4fr_.6fr]"><div><p className="text-xs uppercase tracking-[.24em] text-gold/60">TODAY AT MLAMH</p><h2 className="mt-3 max-w-3xl text-3xl font-light leading-tight text-white md:text-4xl">{headline}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/45">{ar?`${work.length} أعمال نشطة · ${connected} قنوات متصلة · ${team.reduce((n:number,a:any)=>n+(a.tasks_completed??0),0)} مهمة أنجزها الفريق.`:`${work.length} active work items · ${connected} connected channels · ${team.reduce((n:number,a:any)=>n+(a.tasks_completed??0),0)} team tasks completed.`}</p></div><div className="grid grid-cols-3 gap-2 self-end"><div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><p className="text-[10px] text-white/35">{ar?"يعمل الآن":"Working"}</p><p className="mt-2 text-2xl text-white">{active}</p></div><div className="rounded-2xl border border-gold/20 bg-gold/[.06] p-4"><p className="text-[10px] text-gold/55">{ar?"قرارك":"Your call"}</p><p className="mt-2 text-2xl text-gold">{pending.length}</p></div><div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><p className="text-[10px] text-white/35">{ar?"متصل":"Connected"}</p><p className="mt-2 text-2xl text-white">{connected}</p></div></div></div></section>
 <div className="mb-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><AdminCard className="overflow-hidden"><div className="border-b border-white/[.07] p-5"><p className="text-[10px] uppercase tracking-[.22em] text-gold/60">YOUR DECISIONS</p><h2 className="mt-1 text-xl text-white">{ar?"يحتاج منك الآن":"Needs you now"}</h2></div>{pending.length===0?<div className="p-7"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-full border border-emerald-400/20 bg-emerald-400/[.07] text-emerald-300">✓</div><p className="text-sm text-white/70">{ar?"لا يوجد إجراء مطلوب منك الآن.":"Nothing needs your action right now."}</p><p className="mt-2 text-xs leading-6 text-white/35">{ar?"الفريق يستطيع متابعة العمل ضمن الصلاحيات المعتمدة.":"The team can continue within its approved authority."}</p></div>:<div className="divide-y divide-white/[.06]">{pending.map((a:any)=><Link key={a.id} href={`/admin/marketing/approvals?lang=${language}`} className="block p-5 transition hover:bg-white/[.025]"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-sm font-medium text-white/80">{a.reason||(ar?"قرار تسويقي بانتظارك":"Marketing decision awaiting you")}</p><p className="mt-1 text-xs text-white/35">{[a.channel,a.approval_level,a.risk_level].filter(Boolean).join(" · ")}</p></div><span className="shrink-0 rounded-full border border-gold/20 bg-gold/[.06] px-2.5 py-1 text-[10px] text-gold">{ar?"مراجعة":"Review"}</span></div></Link>)}</div>}</AdminCard>
 <AdminCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><p className="text-[10px] uppercase tracking-[.22em] text-gold/60">TEAM FLOOR</p><h2 className="mt-1 text-xl text-white">{ar?"من يعمل على ماذا؟":"Who is doing what?"}</h2></div><Link href={`/admin/marketing/ai-team?lang=${language}`} className="text-xs text-gold/70">{ar?"الفريق بالكامل ←":"Full team →"}</Link></div><div className="grid gap-px bg-white/[.06] sm:grid-cols-2">{team.slice(0,6).map((a:any)=>{const t=work.find((x:any)=>x.id===a.current_task_id);return <div key={a.id} className="bg-black/20 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-medium text-white/85">{a.name}</p><p className="mt-1 text-xs text-white/35">{a.role}</p></div><span className={`mt-1 h-2.5 w-2.5 rounded-full ${a.status==="working"?"animate-pulse bg-gold":a.status==="error"?"bg-amber-300":"bg-emerald-400"}`}/></div><p className="mt-5 text-[10px] uppercase tracking-[.15em] text-white/25">{statusText(a.status,ar)}</p><p className="mt-1 min-h-10 text-sm leading-5 text-white/65">{t?.title??(ar?"لا توجد مهمة نشطة الآن":"No active assignment right now")}</p></div>})}</div></AdminCard></div>
 <div className="mb-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.22em] text-gold/60">CONTENT PIPELINE</p><h2 className="mt-1 text-xl text-white">{ar?"ما الذي يصنعه الفريق؟":"What is being made?"}</h2></div><Link href={`/admin/marketing/content?lang=${language}`} className="text-xs text-gold/70">{ar?"كل المحتوى ←":"All content →"}</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{creative.length===0?<AdminCard className="p-6 text-sm text-white/40">{ar?"لا يوجد محتوى حديث.":"No recent content."}</AdminCard>:creative.map((c:any)=><Link key={c.id} href={`/admin/marketing/content?lang=${language}`}><AdminCard className="group h-full overflow-hidden transition hover:-translate-y-1 hover:border-gold/20"><div className="relative aspect-[16/9] overflow-hidden bg-gradient-to-br from-gold/[.10] via-white/[.035] to-black/30"><div className="absolute inset-x-5 bottom-5 h-px bg-gradient-to-r from-gold/60 via-white/20 to-transparent"/><div className="absolute bottom-5 start-5 h-3 w-3 -translate-y-1/2 rounded-full border border-gold/40 bg-black"/></div><div className="p-4"><div className="mb-2 flex items-center justify-between gap-3"><span className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[10px] text-white/55">{c.channel??c.content_type??"Content"}</span><span className="text-[10px] text-gold/60">{c.status?.replaceAll("_"," ")}</span></div><p className="line-clamp-2 text-sm font-medium leading-6 text-white/80">{c.title??c.hook??(ar?"محتوى تسويقي":"Marketing content")}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/30">{c.caption??c.hook??""}</p></div></AdminCard></Link>)}</div></div>
 <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><AdminCard className="overflow-hidden"><div className="border-b border-white/[.07] p-5"><p className="text-[10px] uppercase tracking-[.22em] text-gold/60">RECENT MOVES</p><h2 className="mt-1 text-xl text-white">{ar?"آخر ما أنجزه الفريق":"What just happened"}</h2></div><div className="divide-y divide-white/[.06]">{recent.length===0?<div className="p-6 text-sm text-white/35">{ar?"لا توجد حركة حديثة.":"No recent activity."}</div>:recent.slice(0,5).map((i:Activity)=><div key={i.id} className="flex gap-4 p-5"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${i.error?"bg-amber-300":"bg-emerald-400"}`}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-sm font-medium text-white/75">{i.agent_id?names.get(i.agent_id)??i.agent_id:"Marketing AI"}</p><p className="shrink-0 text-[10px] text-white/25">{fmt(i.created_at,ar)}</p></div><p className="mt-1 text-sm text-white/45">{ar?actionAr[i.action]??i.action.replaceAll("_"," "):i.action.replaceAll("_"," ")}</p>{i.reason&&<p className="mt-1 line-clamp-1 text-xs text-white/25">{i.reason}</p>}</div></div>)}</div></AdminCard><AdminCard className="p-5"><p className="text-[10px] uppercase tracking-[.22em] text-gold/60">MARKET PULSE</p><h2 className="mt-1 text-xl text-white">{ar?"نبض المنصة":"Platform pulse"}</h2><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><p className="text-[10px] text-white/35">{ar?"إجمالي المواهب":"Total talents"}</p><p className="mt-2 text-3xl font-light text-white">{talents.count??0}</p></div><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><p className="text-[10px] text-white/35">{ar?"طلبات الفرص":"Applications"}</p><p className="mt-2 text-3xl font-light text-white">{applications.count??0}</p></div></div><div className="mt-7 border-t border-white/[.07] pt-5"><Link href={`/admin/marketing/analytics?lang=${language}`} className="text-xs text-gold/70">{ar?"فتح التحليلات الكاملة ←":"Open full analytics →"}</Link></div></AdminCard></div>
 </AdminPageContainer>;
}
