export type MarketingPlaybookCatalogItem = {
  key: string;
  titleAr: string;
  titleEn: string;
  category: "foundation" | "demand" | "lifecycle" | "growth" | "content" | "measurement" | "seo" | "research";
  status: "approved" | "next" | "later";
  version: number;
  sourceSkill: string;
  purpose: string;
  approval: "auto" | "approval_required" | "ceo_only";
  outcome: string;
};

export const marketingPlaybookCatalog: MarketingPlaybookCatalogItem[] = [
  { key: "product-positioning-audience", titleAr: "تموضع المنتج والجمهور", titleEn: "Product Positioning & Audience Context", category: "foundation", status: "approved", version: 1, sourceSkill: "product-marketing", purpose: "Keep every marketing workflow aligned to one canonical MLAMH definition, audience model, market context, voice, privacy rules, and marketplace loop.", approval: "auto", outcome: "Consistent positioning across outreach, content, CRO, SEO, and AI-generated work." },
  { key: "publisher-prospecting", titleAr: "استهداف الناشرين والعملاء", titleEn: "Publisher Prospecting", category: "demand", status: "approved", version: 1, sourceSkill: "prospecting", purpose: "Prioritize publishers with credible demand signals, professional contact evidence, market fit, and a realistic path to a brief.", approval: "auto", outcome: "More qualified publisher leads and fewer low-value outreach attempts." },
  { key: "governed-cold-outreach", titleAr: "التواصل البارد المحكوم", titleEn: "Governed Cold Outreach", category: "demand", status: "approved", version: 1, sourceSkill: "cold-email", purpose: "Prepare concise, relevant publisher outreach while preserving sender identity, approval policy, opt-out handling, and existing execution channels.", approval: "approval_required", outcome: "Higher positive reply and brief conversion without increasing governance risk." },
  { key: "email-followup-reply-handling", titleAr: "متابعة البريد ومعالجة الردود", titleEn: "Email Follow-up & Reply Handling", category: "lifecycle", status: "approved", version: 1, sourceSkill: "emails", purpose: "Use reply classification, safe routing, governed follow-up timing, opt-out suppression, and feedback diagnostics to move real conversations toward briefs.", approval: "approval_required", outcome: "Better reply-to-brief conversion and fewer unnecessary follow-ups." },
  { key: "analytics-attribution", titleAr: "التحليلات والإسناد", titleEn: "Analytics & Attribution", category: "measurement", status: "approved", version: 1, sourceSkill: "analytics + attribution", purpose: "Measure source and channel contribution to qualified talent, publisher replies, briefs, applications, selections, and marketplace liquidity.", approval: "auto", outcome: "Growth decisions based on qualified outcomes rather than traffic or send volume alone." },
  { key: "signup-conversion-review", titleAr: "مراجعة تحويل التسجيل", titleEn: "Signup Conversion Review", category: "growth", status: "next", version: 1, sourceSkill: "cro + signup", purpose: "Identify friction in Talent and Publisher registration while preserving explicit role intent and product policy.", approval: "auto", outcome: "Higher completed signups with lower role-selection error and no dark patterns." },
  { key: "talent-onboarding-activation", titleAr: "تفعيل المواهب بعد التسجيل", titleEn: "Talent Onboarding Activation", category: "growth", status: "next", version: 1, sourceSkill: "onboarding", purpose: "Move new talent from signup to a complete, submitted, approvable profile and first meaningful opportunity interaction.", approval: "auto", outcome: "Higher profile completion, submission, approval, and first-application rates." },
  { key: "referral-sharing-loops", titleAr: "الإحالات وحلقات المشاركة", titleEn: "Referral & Sharing Loops", category: "growth", status: "next", version: 1, sourceSkill: "referrals + marketing-loops", purpose: "Create measurable talent- and opportunity-led sharing loops that bring users back into MLAMH rather than leaking activity to untracked channels.", approval: "approval_required", outcome: "Activated referral users and compounding organic acquisition." },
  { key: "content-strategy-brand-voice", titleAr: "استراتيجية المحتوى ونبرة العلامة", titleEn: "Content Strategy & Brand Voice", category: "content", status: "next", version: 1, sourceSkill: "content-strategy + copywriting + social", purpose: "Tie organic content to specific marketplace goals, audiences, channels, and conversion events while preserving MLAMH voice.", approval: "approval_required", outcome: "Content that creates qualified visits, signups, applications, replies, and briefs." },
  { key: "experiment-design", titleAr: "تصميم التجارب", titleEn: "Experiment Design / A-B Testing", category: "measurement", status: "next", version: 1, sourceSkill: "ab-testing", purpose: "Define hypotheses, primary metrics, guardrails, evidence thresholds, and stop criteria before changing conversion flows.", approval: "auto", outcome: "Reversible, evidence-based improvements instead of opinion-driven iteration." },
  { key: "seo-audit", titleAr: "تدقيق الظهور في البحث", titleEn: "SEO Audit", category: "seo", status: "next", version: 1, sourceSkill: "seo-audit + schema + ai-seo", purpose: "Protect crawlability, metadata, structured data, AI-search visibility, and public privacy boundaries across MLAMH discovery surfaces.", approval: "auto", outcome: "More qualified organic discovery with correct indexation and structured data." },
  { key: "programmatic-seo-guardrails", titleAr: "ضوابط SEO البرنامجي", titleEn: "Programmatic SEO Guardrails", category: "seo", status: "later", version: 1, sourceSkill: "programmatic-seo + site-architecture", purpose: "Scale market, city, category, talent, and opportunity discovery pages only where each page has unique user value and country-aware context.", approval: "approval_required", outcome: "Scalable organic acquisition without thin, duplicate, or privacy-sensitive pages." },
  { key: "competitor-intelligence", titleAr: "ذكاء المنافسين", titleEn: "Competitor Intelligence", category: "research", status: "later", version: 1, sourceSkill: "competitor-profiling", purpose: "Track positioning, acquisition channels, market coverage, product claims, and gaps using sourced evidence rather than assumptions.", approval: "auto", outcome: "Sharper positioning and prioritization without copying competitors." },
  { key: "customer-research", titleAr: "بحث العملاء والمستخدمين", titleEn: "Customer Research", category: "research", status: "later", version: 1, sourceSkill: "customer-research", purpose: "Capture recurring needs, objections, language, and friction from real Talent and Publisher interactions and feed validated learning back into playbooks.", approval: "auto", outcome: "Messaging and product growth decisions grounded in observed user evidence." },
];

export const approvedMarketingPlaybooks = marketingPlaybookCatalog.filter((item) => item.status === "approved");
export const nextMarketingPlaybooks = marketingPlaybookCatalog.filter((item) => item.status === "next");
