import Link from "next/link";
import { createCastingPaymentAction, updateCastingCommercialStatusAction, updateCastingPaymentStatusAction } from "@/lib/actions/admin-casting-commercial";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";
const commercialStatuses = ["lead", "proposal", "won", "lost", "cancelled"];
const paymentStatuses = ["pending", "paid", "failed", "refunded", "cancelled"];
const packageLabels: Record<string, { ar: string; en: string }> = {
  starter: { ar: "Managed Basic", en: "Managed Basic" },
  pro: { ar: "Managed Pro", en: "Managed Pro" },
  custom: { ar: "Managed Enterprise", en: "Managed Enterprise" },
};
function money(value: unknown) { const n = Number(value); return new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(Number.isFinite(n) ? n : 0); }

export default async function CastingCommercialPage({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const { lang } = await searchParams;
  const language = lang === "en" ? "en" : "ar";
  const ar = language === "ar";
  const admin = createAdminClient();
  const [{ data: projects }, { data: payments }] = await Promise.all([
    admin.from("casting_projects").select("id,project_title,company_name,status,commercial_status,package_code,quoted_amount,currency,created_at").eq("service_mode", "managed").order("created_at", { ascending: false }),
    admin.from("casting_payments").select("id,casting_project_id,status,amount,currency,provider,provider_reference,paid_at,created_at").order("created_at", { ascending: false }),
  ]);
  const managedProjectIds = new Set((projects ?? []).map((project) => Number(project.id)));
  const paymentRows = (payments ?? []).filter((payment) => managedProjectIds.has(Number(payment.casting_project_id)));
  const paymentMap = new Map<number, typeof paymentRows>();
  for (const payment of paymentRows) { const id = Number(payment.casting_project_id); paymentMap.set(id, [...(paymentMap.get(id) ?? []), payment]); }

  return <div dir={ar ? "rtl" : "ltr"} className="px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><Link href={`/admin/casting?lang=${language}`} className="text-xs text-gold hover:underline">{ar ? "← العودة إلى MLAMH Casting" : "← Back to MLAMH Casting"}</Link><p className="mt-4 text-xs uppercase tracking-[0.28em] text-gold">MANAGED CASTING · COMMERCIAL OPERATIONS</p><h1 className="mt-3 text-3xl font-light text-white sm:text-4xl">{ar ? "المبيعات والتحصيل" : "Sales & Collections"}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/40">{ar ? "هذه الصفحة خاصة بمشاريع Managed Casting فقط. قيمة العرض تمثل Pipeline، ولا يُسجل الإيراد إلا من دفعات Paid الفعلية." : "This pipeline is isolated to Managed Casting projects only. Quoted value is pipeline; revenue is recognized only from actual Paid ledger entries."}</p></div><Link href={`/admin/casting/analytics?lang=${language}`} className="rounded-xl border border-gold/25 px-4 py-2.5 text-sm text-gold">{ar ? "لوحة المؤشرات" : "Analytics"}</Link></div>

    <div className="mt-6 space-y-5">{(projects ?? []).length === 0 ? <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-10 text-center text-sm text-white/35">{ar ? "لا توجد مشاريع Managed Casting تجارية حاليًا." : "No Managed Casting commercial projects yet."}</div> : (projects ?? []).map((project) => { const projectPayments = paymentMap.get(Number(project.id)) ?? []; const paid = projectPayments.filter(p => p.status === "paid").reduce((s,p)=>s+Number(p.amount||0),0); const refunded = projectPayments.filter(p => p.status === "refunded").reduce((s,p)=>s+Number(p.amount||0),0); const net = Math.max(0, paid-refunded); const packageLabel = project.package_code ? packageLabels[project.package_code] : null; return <section key={project.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2 text-[11px]"><span className="rounded-full border border-white/10 px-2.5 py-1 text-white/40">#{project.id}</span><span className="rounded-full border border-gold/20 px-2.5 py-1 text-gold">{project.commercial_status || "lead"}</span>{packageLabel ? <span className="rounded-full border border-white/10 px-2.5 py-1 text-white/40">{ar ? packageLabel.ar : packageLabel.en}</span> : null}</div><Link href={`/admin/casting/${project.id}?lang=${language}`} className="mt-3 block text-xl font-light text-white hover:text-gold">{project.project_title}</Link><p className="mt-1 text-xs text-white/35">{project.company_name || "—"}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/[0.07] bg-black/20 p-3"><p className="text-[10px] text-white/30">Quoted</p><p className="mt-1 text-sm text-white">{money(project.quoted_amount)} {project.currency || "SAR"}</p></div><div className="rounded-xl border border-emerald-400/15 bg-emerald-400/[0.03] p-3"><p className="text-[10px] text-emerald-300/60">Collected</p><p className="mt-1 text-sm text-white">{money(net)} {project.currency || "SAR"}</p></div><div className="rounded-xl border border-white/[0.07] bg-black/20 p-3"><p className="text-[10px] text-white/30">Payments</p><p className="mt-1 text-sm text-white">{projectPayments.length}</p></div></div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[0.75fr_1.25fr]"><form action={updateCastingCommercialStatusAction} className="rounded-xl border border-white/[0.07] bg-black/20 p-4"><input type="hidden" name="project_id" value={project.id}/><label className="text-xs text-white/40">{ar ? "حالة الصفقة" : "Deal status"}</label><div className="mt-2 flex gap-2"><select name="commercial_status" defaultValue={project.commercial_status || "lead"} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white">{commercialStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="rounded-lg border border-gold/25 px-4 py-2 text-xs text-gold">{ar ? "حفظ" : "Save"}</button></div></form>
      <form action={createCastingPaymentAction} className="rounded-xl border border-white/[0.07] bg-black/20 p-4"><input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="currency" value={project.currency || "SAR"}/><p className="text-xs text-white/40">{ar ? "تسجيل حركة مالية" : "Record ledger entry"}</p><p className="mt-1 text-[11px] leading-5 text-white/25">{ar ? "هذا سجل تشغيلي يدوي، وليس إنشاء رابط دفع أو تحصيل تلقائي." : "This is an operational ledger entry, not a payment-link or automatic charge action."}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input required name="amount" type="number" min="0.01" step="0.01" placeholder={project.currency || "SAR"} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white"/><select name="status" defaultValue="pending" className="rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white">{paymentStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><input name="provider" placeholder="manual / tap" className="rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white"/><input name="provider_reference" placeholder={ar ? "مرجع الدفع" : "Payment reference"} className="rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white"/></div><textarea name="internal_notes" rows={2} placeholder={ar ? "ملاحظات داخلية" : "Internal notes"} className="mt-2 w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white"/><button className="mt-2 rounded-lg bg-gold px-4 py-2 text-xs font-medium text-black">{ar ? "إضافة للسجل" : "Add ledger entry"}</button></form></div>
      {projectPayments.length ? <div className="mt-4 space-y-2">{projectPayments.map(payment=><form key={payment.id} action={updateCastingPaymentStatusAction} className="flex flex-col gap-2 rounded-xl border border-white/[0.06] px-4 py-3 text-xs sm:flex-row sm:items-center"><input type="hidden" name="payment_id" value={payment.id}/><input type="hidden" name="project_id" value={project.id}/><span className="text-white/75">{money(payment.amount)} {payment.currency}</span><span className="text-white/30">{payment.provider || "manual"}{payment.provider_reference ? ` · ${payment.provider_reference}` : ""}</span><select name="status" defaultValue={payment.status} className="sm:ms-auto rounded-lg border border-white/10 bg-black px-2 py-1.5 text-white/60">{paymentStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="rounded-lg border border-white/10 px-3 py-1.5 text-white/50 hover:text-gold">{ar ? "تحديث" : "Update"}</button></form>)}</div> : null}</section>; })}</div>
  </div></div>;
}
