"use client";

import { CheckCircle2, FileText, RotateCcw, XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { approveTalentAction, rejectTalentAction, requestTalentChangesAction } from "@/lib/actions/review-talent";

type ReviewStatus = "not_submitted" | "pending" | "changes_requested" | "approved" | "rejected" | "suspended";
type ReviewDecision = "approve" | "changes" | "reject";
type Props = { talentId: number; status: string | null | undefined; language: "ar" | "en" };

const CHANGE_REASONS = [
  { value: "profile_image_low_quality", ar: "جودة الصورة الرئيسية منخفضة", en: "Main profile photo quality is too low" },
  { value: "profile_image_unclear", ar: "الصورة الرئيسية غير واضحة أو غير مناسبة للملف المهني", en: "Main profile photo is unclear or unsuitable for a professional profile" },
  { value: "gallery_needs_improvement", ar: "صور المعرض تحتاج تحسين أو صور أوضح", en: "Gallery needs clearer or improved photos" },
  { value: "bio_needs_update", ar: "النبذة المهنية تحتاج تحديث", en: "Professional bio needs an update" },
  { value: "profile_information_incomplete", ar: "بيانات الملف تحتاج استكمال", en: "Profile information needs completion" },
  { value: "measurements_need_update", ar: "القياسات أو بيانات المظهر تحتاج تحديث", en: "Measurements or appearance details need an update" },
  { value: "portfolio_links_need_update", ar: "روابط الأعمال أو الملف المهني تحتاج تحديث", en: "Portfolio or professional links need an update" },
  { value: "other", ar: "سبب آخر", en: "Other reason" },
] as const;

export function AdminTalentReviewActions({ talentId, status, language }: Props) {
  const router = useRouter();
  const isArabic = language === "ar";
  const [isPending, startTransition] = useTransition();
  const [selectedDecision, setSelectedDecision] = useState<ReviewDecision | null>(null);
  const [reasonPreset, setReasonPreset] = useState("");
  const [reason, setReason] = useState("");
  const [adminNote, setAdminNote] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [isError, setIsError] = useState(false);
  const normalizedStatus = (status ?? "not_submitted") as ReviewStatus;
  const requiresReason = selectedDecision === "changes" || selectedDecision === "reject";

  function openConfirmation(decision: ReviewDecision) { setMessage(null); setIsError(false); setReasonPreset(""); setReason(""); setAdminNote(""); setSelectedDecision(decision); }
  function closeConfirmation() { if (isPending) return; setSelectedDecision(null); setReasonPreset(""); setReason(""); setAdminNote(""); }
  function choosePreset(value: string) { setReasonPreset(value); const preset = CHANGE_REASONS.find((item) => item.value === value); if (preset && value !== "other") setReason(isArabic ? preset.ar : preset.en); else if (value === "other") setReason(""); }

  function executeDecision() {
    if (!selectedDecision) return;
    const cleanReason = reason.trim(); const cleanAdminNote = adminNote.trim();
    if (requiresReason && !cleanReason) { setIsError(true); setMessage(isArabic ? (selectedDecision === "reject" ? "اكتب سبب رفض الملف قبل المتابعة." : "اختر أو اكتب سبب طلب التعديل قبل المتابعة.") : (selectedDecision === "reject" ? "Please enter a rejection reason before continuing." : "Choose or enter a reason for the requested changes.")); return; }
    setMessage(null); setIsError(false);
    const formData = new FormData(); formData.set("id", String(talentId)); formData.set("locale", language); if (cleanReason) formData.set("reason", cleanReason); if (cleanAdminNote) formData.set("admin_note", cleanAdminNote);
    startTransition(async () => { try { const result = selectedDecision === "approve" ? await approveTalentAction(formData) : selectedDecision === "changes" ? await requestTalentChangesAction(formData) : await rejectTalentAction(formData); setMessage(result.message); setIsError(!result.success); if (result.success) { setSelectedDecision(null); setReasonPreset(""); setReason(""); setAdminNote(""); router.refresh(); } } catch (error) { console.error("[AdminTalentReviewActions]", error); setIsError(true); setMessage(isArabic ? "حدث خطأ غير متوقع أثناء تنفيذ القرار." : "An unexpected error occurred while applying the decision."); } });
  }

  const config = selectedDecision === "approve" ? { title: isArabic ? "اعتماد ملف الموهبة؟" : "Approve talent profile?", description: isArabic ? "سيتم اعتماد الملف ونشره ليصبح ظاهرًا للجهات الناشرة." : "The profile will be approved and published for publishers.", button: isArabic ? "تأكيد الاعتماد" : "Confirm approval", className: "border-emerald-400/25 bg-emerald-400/[0.08] text-emerald-300 hover:bg-emerald-400 hover:text-black" } : selectedDecision === "changes" ? { title: isArabic ? "إعادة الملف للتعديل؟" : "Request profile changes?", description: isArabic ? "سيعود الملف إلى الموهبة لاستكمال أو تعديل البيانات المطلوبة، ولن يكون منشورًا حتى تتم مراجعته من جديد." : "The profile will be returned to the talent for updates and will remain unpublished until reviewed again.", button: isArabic ? "تأكيد طلب التعديل" : "Confirm changes", className: "border-amber-400/25 bg-amber-400/[0.08] text-amber-200 hover:bg-amber-400 hover:text-black" } : selectedDecision === "reject" ? { title: isArabic ? "رفض ملف الموهبة؟" : "Reject talent profile?", description: isArabic ? "سيتم رفض الملف وإخفاؤه عن الجهات الناشرة. يجب تسجيل سبب واضح للقرار." : "The profile will be rejected and hidden from publishers. A clear reason must be recorded.", button: isArabic ? "تأكيد الرفض" : "Confirm rejection", className: "border-red-400/25 bg-red-400/[0.08] text-red-300 hover:bg-red-400 hover:text-black" } : null;

  return <>
    <section dir={isArabic ? "rtl" : "ltr"} className="rounded-3xl border border-gold/15 bg-gold/[0.035] p-5 sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] uppercase tracking-[0.25em] text-gold">{isArabic ? "قرار المراجعة" : "Review decision"}</p><h2 className="mt-2 text-xl font-light text-white">{isArabic ? "إجراءات الملف" : "Profile actions"}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/40">{isArabic ? "اختر القرار المناسب بعد مراجعة بيانات الموهبة. سيتم تحديث الحالة وتسجيل القرار في سجل المراجعات." : "Choose the appropriate decision after reviewing the profile. The status and review history will be updated."}</p></div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" disabled={isPending || normalizedStatus === "approved"} onClick={() => openConfirmation("approve")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/[0.07] px-5 text-sm text-emerald-300 transition hover:bg-emerald-400 hover:text-black disabled:opacity-35"><CheckCircle2 className="h-4 w-4" />{isArabic ? "اعتماد" : "Approve"}</button><button type="button" disabled={isPending || normalizedStatus === "changes_requested"} onClick={() => openConfirmation("changes")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-amber-400/20 bg-amber-400/[0.07] px-5 text-sm text-amber-200 transition hover:bg-amber-400 hover:text-black disabled:opacity-35"><RotateCcw className="h-4 w-4" />{isArabic ? "طلب تعديل" : "Request changes"}</button><button type="button" disabled={isPending || normalizedStatus === "rejected"} onClick={() => openConfirmation("reject")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-red-400/20 bg-red-400/[0.07] px-5 text-sm text-red-300 transition hover:bg-red-400 hover:text-black disabled:opacity-35"><XCircle className="h-4 w-4" />{isArabic ? "رفض" : "Reject"}</button></div></div>{message ? <div role="status" className={`mt-5 rounded-2xl border px-4 py-3 text-sm ${isError ? "border-red-400/20 bg-red-400/[0.07] text-red-300" : "border-emerald-400/20 bg-emerald-400/[0.07] text-emerald-300"}`}>{message}</div> : null}</section>
    {selectedDecision && config ? <div role="dialog" aria-modal="true" dir={isArabic ? "rtl" : "ltr"} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"><button type="button" aria-label={isArabic ? "إغلاق" : "Close"} onClick={closeConfirmation} className="absolute inset-0 cursor-default"/><div className="relative z-10 max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl border border-white/[0.1] bg-[#0b0b0b] p-6 shadow-2xl sm:p-7"><p className="text-[10px] uppercase tracking-[0.25em] text-gold">{isArabic ? "تأكيد القرار" : "Confirm decision"}</p><h2 className="mt-3 text-2xl font-light text-white">{config.title}</h2><p className="mt-3 text-sm leading-7 text-white/45">{config.description}</p>
      {selectedDecision === "changes" ? <div className="mt-6"><label htmlFor="change-reason-preset" className="mb-2 block text-xs font-medium text-white/70">{isArabic ? "سبب جاهز" : "Reason preset"}</label><select id="change-reason-preset" value={reasonPreset} onChange={(e) => choosePreset(e.target.value)} disabled={isPending} className="w-full rounded-2xl border border-white/[0.1] bg-[#111] px-4 py-3 text-sm text-white outline-none focus:border-gold/35"><option value="">{isArabic ? "اختر سبب طلب التعديل" : "Choose a change reason"}</option>{CHANGE_REASONS.map((item) => <option key={item.value} value={item.value}>{isArabic ? item.ar : item.en}</option>)}</select></div> : null}
      {requiresReason ? <div className="mt-5"><div className="mb-2 flex items-center justify-between"><label htmlFor="review-reason" className="text-xs font-medium text-white/70">{isArabic ? (selectedDecision === "reject" ? "سبب الرفض" : "الرسالة التي ستظهر للموهبة") : (selectedDecision === "reject" ? "Rejection reason" : "Message shown to talent")}</label><span className="text-[10px] text-red-300/70">{isArabic ? "مطلوب" : "Required"}</span></div><textarea id="review-reason" value={reason} onChange={(e) => setReason(e.target.value)} disabled={isPending} maxLength={1000} rows={4} placeholder={isArabic ? "اكتب سببًا واضحًا وقابلًا للتنفيذ..." : "Write a clear, actionable reason..."} className="w-full resize-none rounded-2xl border border-white/[0.1] bg-white/[0.025] px-4 py-3 text-sm leading-6 text-white outline-none placeholder:text-white/20 focus:border-gold/35"/><div className="mt-1 text-end text-[10px] text-white/25">{reason.length}/1000</div></div> : null}
      <div className="mt-5"><div className="mb-2 flex items-center gap-2"><FileText className="h-3.5 w-3.5 text-white/35"/><label htmlFor="admin-note" className="text-xs font-medium text-white/55">{isArabic ? "ملاحظة داخلية للإدارة" : "Internal admin note"}</label></div><textarea id="admin-note" value={adminNote} onChange={(e) => setAdminNote(e.target.value)} disabled={isPending} maxLength={1000} rows={3} className="w-full resize-none rounded-2xl border border-white/[0.1] bg-white/[0.025] px-4 py-3 text-sm leading-6 text-white outline-none focus:border-gold/35"/></div>{message && isError ? <div className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/[0.07] px-4 py-3 text-sm text-red-300">{message}</div> : null}<div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={isPending} onClick={closeConfirmation} className="min-h-11 rounded-xl border border-white/10 px-5 text-sm text-white/55 hover:text-white">{isArabic ? "إلغاء" : "Cancel"}</button><button type="button" disabled={isPending} onClick={executeDecision} className={`min-h-11 rounded-xl border px-5 text-sm transition disabled:opacity-50 ${config.className}`}>{isPending ? (isArabic ? "جارٍ التنفيذ..." : "Applying...") : config.button}</button></div></div></div> : null}
  </>;
}
