create table if not exists public.casting_project_files (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  category text not null default 'general'
    check (category in ('general','call_sheet','brief','reference','contract','invoice','deliverable','other')),
  visible_to_client boolean not null default true,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists casting_project_files_storage_path_key
  on public.casting_project_files(storage_path);

create index if not exists casting_project_files_project_idx
  on public.casting_project_files(casting_project_id, created_at desc);

alter table public.casting_project_files enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'casting-project-files',
  'casting-project-files',
  false,
  20971520,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.casting_project_files is
  'Private Managed Casting files accessed through signed URLs generated on the server.';
