-- MLAMH Scene content foundation.
-- Additive only: this migration does not alter users, profiles, talents,
-- publishers, opportunities, applications, conversations, or messages.

create table if not exists public.scene_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null,
  name_en text not null,
  description_ar text,
  description_en text,
  audience text not null default 'all' check (audience in ('all', 'talent', 'publisher')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scene_articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_id bigint references public.scene_categories(id) on delete set null,
  content_type text not null default 'guide' check (
    content_type in ('guide', 'help', 'industry', 'story', 'report', 'qa')
  ),
  audience text not null default 'all' check (audience in ('all', 'talent', 'publisher')),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),

  title_ar text not null,
  title_en text,
  excerpt_ar text,
  excerpt_en text,
  content_ar text not null,
  content_en text,

  cover_image_url text,
  cover_image_alt_ar text,
  cover_image_alt_en text,

  author_name_ar text,
  author_name_en text,
  read_time_minutes integer check (read_time_minutes is null or read_time_minutes > 0),
  tags text[] not null default '{}',

  seo_title_ar text,
  seo_title_en text,
  seo_description_ar text,
  seo_description_en text,

  cta_label_ar text,
  cta_label_en text,
  cta_href text,

  is_featured boolean not null default false,
  sort_order integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint scene_articles_published_at_check check (
    status <> 'published' or published_at is not null
  )
);

create index if not exists scene_categories_active_sort_idx
  on public.scene_categories (is_active, sort_order, id);

create index if not exists scene_articles_public_idx
  on public.scene_articles (status, published_at desc, id desc);

create index if not exists scene_articles_category_idx
  on public.scene_articles (category_id, status, published_at desc);

create index if not exists scene_articles_audience_idx
  on public.scene_articles (audience, status, published_at desc);

create index if not exists scene_articles_featured_idx
  on public.scene_articles (is_featured, status, published_at desc)
  where is_featured = true;

drop trigger if exists scene_categories_set_updated_at on public.scene_categories;
create trigger scene_categories_set_updated_at
before update on public.scene_categories
for each row
execute function public.set_updated_at();

drop trigger if exists scene_articles_set_updated_at on public.scene_articles;
create trigger scene_articles_set_updated_at
before update on public.scene_articles
for each row
execute function public.set_updated_at();

alter table public.scene_categories enable row level security;
alter table public.scene_articles enable row level security;

drop policy if exists "Public can read active Scene categories"
  on public.scene_categories;
create policy "Public can read active Scene categories"
on public.scene_categories
for select
using (is_active = true);

drop policy if exists "Public can read published Scene articles"
  on public.scene_articles;
create policy "Public can read published Scene articles"
on public.scene_articles
for select
using (
  status = 'published'
  and published_at is not null
  and published_at <= now()
);

-- Category seeds only. No user or production workflow data is touched.
insert into public.scene_categories (
  slug,
  name_ar,
  name_en,
  description_ar,
  description_en,
  audience,
  sort_order
)
values
  ('talent', 'للمواهب', 'For Talent', 'أدلة عملية لبناء الملف والاستعداد للكاستنج وتطوير الحضور المهني.', 'Practical guides for profiles, casting readiness and professional growth.', 'talent', 10),
  ('publishers', 'للناشرين', 'For Publishers', 'أدلة لكتابة الطلبات واختيار المواهب وإدارة الكاستنج بكفاءة.', 'Guides for briefs, talent selection and efficient casting workflows.', 'publisher', 20),
  ('industry', 'الصناعة', 'Industry', 'الكاستنج والإنتاج والتصوير واتجاهات الصناعة الإبداعية.', 'Casting, production, photography and creative-industry trends.', 'all', 30),
  ('using-mlamh', 'استخدام ملامح', 'Using MLAMH', 'شروحات واضحة لاستخدام أدوات وخدمات ملامح.', 'Clear guidance for using MLAMH products and workflows.', 'all', 40),
  ('stories', 'قصص ومقابلات', 'Stories & Interviews', 'قصص وتجارب من المواهب والناشرين وصناعة الإبداع.', 'Stories and experiences from talent, publishers and the creative industry.', 'all', 50),
  ('reports', 'تقارير ورؤى', 'Reports & Insights', 'بيانات وتحليلات تساعد على فهم سوق المواهب والكاستنج.', 'Data and analysis for understanding talent and casting markets.', 'all', 60)
on conflict (slug) do nothing;
