create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  group_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create index if not exists role_permissions_role_id_idx
  on public.role_permissions (role_id);

create index if not exists role_permissions_permission_id_idx
  on public.role_permissions (permission_id);

create index if not exists user_roles_user_id_idx
  on public.user_roles (user_id);

create index if not exists user_roles_role_id_idx
  on public.user_roles (role_id);

drop trigger if exists roles_set_updated_at
  on public.roles;

create trigger roles_set_updated_at
before update on public.roles
for each row
execute function public.set_updated_at();

alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_roles enable row level security;

insert into public.roles (
  key,
  name,
  description,
  is_system
)
values
  (
    'super_admin',
    'Super Admin',
    'Full access to all administrative features and permissions.',
    true
  ),
  (
    'admin',
    'Admin',
    'General administrative access.',
    true
  ),
  (
    'content_manager',
    'Content Manager',
    'Manage public website content.',
    true
  ),
  (
    'moderator',
    'Moderator',
    'Review and moderate platform content.',
    true
  ),
  (
    'viewer',
    'Viewer',
    'Read-only administrative access.',
    true
  )
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  is_system = excluded.is_system;

insert into public.permissions (
  key,
  name,
  description,
  group_name
)
values
  (
    'admin.dashboard.view',
    'View Admin Dashboard',
    'Access the main admin dashboard.',
    'admin'
  ),
  (
    'admin.site_management.view',
    'View Site Management',
    'Access the site management area.',
    'site_management'
  ),
  (
    'cms.footer.view',
    'View Footer Management',
    'View footer settings and links.',
    'cms'
  ),
  (
    'cms.footer.edit',
    'Edit Footer',
    'Create, update, and delete footer content.',
    'cms'
  ),
  (
    'cms.homepage.view',
    'View Homepage Management',
    'View homepage management.',
    'cms'
  ),
  (
    'cms.homepage.edit',
    'Edit Homepage',
    'Manage homepage content.',
    'cms'
  ),
  (
    'cms.navigation.view',
    'View Navigation Management',
    'View public navigation settings.',
    'cms'
  ),
  (
    'cms.navigation.edit',
    'Edit Navigation',
    'Manage public navigation links.',
    'cms'
  ),
  (
    'cms.seo.view',
    'View SEO Management',
    'View SEO settings.',
    'cms'
  ),
  (
    'cms.seo.edit',
    'Edit SEO',
    'Manage SEO settings.',
    'cms'
  ),
  (
    'cms.legal.view',
    'View Legal Management',
    'View legal pages.',
    'cms'
  ),
  (
    'cms.legal.edit',
    'Edit Legal Content',
    'Manage legal pages.',
    'cms'
  ),
  (
    'roles.view',
    'View Roles',
    'View roles and permissions.',
    'rbac'
  ),
  (
    'roles.manage',
    'Manage Roles',
    'Create and update roles and role permissions.',
    'rbac'
  ),
  (
    'admins.view',
    'View Admin Users',
    'View administrative users.',
    'rbac'
  ),
  (
    'admins.manage',
    'Manage Admin Users',
    'Assign and remove administrative roles.',
    'rbac'
  )
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  group_name = excluded.group_name;

insert into public.role_permissions (
  role_id,
  permission_id
)
select
  roles.id,
  permissions.id
from public.roles
cross join public.permissions
where roles.key = 'super_admin'
on conflict do nothing;

insert into public.role_permissions (
  role_id,
  permission_id
)
select
  roles.id,
  permissions.id
from public.roles
join public.permissions
  on permissions.key in (
    'admin.dashboard.view',
    'admin.site_management.view',
    'cms.footer.view',
    'cms.footer.edit',
    'cms.homepage.view',
    'cms.homepage.edit',
    'cms.navigation.view',
    'cms.navigation.edit',
    'cms.seo.view',
    'cms.seo.edit',
    'cms.legal.view',
    'cms.legal.edit'
  )
where roles.key = 'admin'
on conflict do nothing;

insert into public.role_permissions (
  role_id,
  permission_id
)
select
  roles.id,
  permissions.id
from public.roles
join public.permissions
  on permissions.key in (
    'admin.dashboard.view',
    'admin.site_management.view',
    'cms.footer.view',
    'cms.footer.edit',
    'cms.homepage.view',
    'cms.homepage.edit',
    'cms.navigation.view',
    'cms.navigation.edit',
    'cms.seo.view',
    'cms.seo.edit',
    'cms.legal.view',
    'cms.legal.edit'
  )
where roles.key = 'content_manager'
on conflict do nothing;

insert into public.role_permissions (
  role_id,
  permission_id
)
select
  roles.id,
  permissions.id
from public.roles
join public.permissions
  on permissions.key in (
    'admin.dashboard.view',
    'admin.site_management.view',
    'cms.footer.view',
    'cms.homepage.view',
    'cms.navigation.view',
    'cms.seo.view',
    'cms.legal.view'
  )
where roles.key = 'viewer'
on conflict do nothing;