create table if not exists public.opportunity_invitations (
  id bigint generated by default as identity primary key,

  publisher_id bigint not null
    references public.publishers(id)
    on update cascade
    on delete cascade,

  talent_id bigint not null
    references public.talents(id)
    on update cascade
    on delete cascade,

  opportunity_id bigint not null
    references public.opportunities(id)
    on update cascade
    on delete cascade,

  status text not null default 'sent'
    check (
      status in (
        'sent',
        'viewed',
        'applied',
        'dismissed'
      )
    ),

  read_at timestamptz,
  applied_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint opportunity_invitations_unique
    unique (opportunity_id, talent_id)
);

create index if not exists opportunity_invitations_publisher_id_idx
  on public.opportunity_invitations (publisher_id);

create index if not exists opportunity_invitations_talent_id_idx
  on public.opportunity_invitations (talent_id);

create index if not exists opportunity_invitations_opportunity_id_idx
  on public.opportunity_invitations (opportunity_id);

create index if not exists opportunity_invitations_talent_status_idx
  on public.opportunity_invitations (
    talent_id,
    status,
    created_at desc
  );

create index if not exists opportunity_invitations_publisher_created_at_idx
  on public.opportunity_invitations (
    publisher_id,
    created_at desc
  );

drop trigger if exists opportunity_invitations_set_updated_at
  on public.opportunity_invitations;

create trigger opportunity_invitations_set_updated_at
before update on public.opportunity_invitations
for each row
execute function public.set_updated_at();

alter table public.opportunity_invitations
  enable row level security;