-- Keep Admin Talent readiness aligned with the canonical Talent record.
-- `base_country_code` is stored on public.talents and must be exposed by
-- admin_talent_profiles; otherwise every admin-side readiness calculation
-- falsely reports Country of residence as missing.
--
-- The production database has talent_views while the isolated staging database
-- does not. Preserve the existing admin_views behavior in both environments.
do $$
begin
  if to_regclass('public.talent_views') is not null then
    execute $view$
      create or replace view public.admin_talent_profiles as
      select
        t.id,
        t.name_en,
        t.name_ar,
        t.category_en,
        t.category_ar,
        t.image_url,
        t.featured,
        t.created_at,
        t.sort_order,
        t.published,
        t.city_en,
        t.city_ar,
        t.age,
        t.height,
        t.bio_en,
        t.bio_ar,
        t.whatsapp,
        t.gallery_images,
        t.instagram,
        t.tiktok,
        t.snapchat,
        t.portfolio_url,
        t.status,
        t.slug,
        t.profile_completion,
        t.featured_until,
        t.availability_status,
        t.display_name_en,
        t.display_name_ar,
        t.verified,
        t.verified_at,
        t.user_id,
        t.city_slug,
        t.category_slug,
        t.gender,
        t.date_of_birth,
        t.nationality,
        t.languages,
        t.dialects,
        t.skills,
        t.nationality_slug,
        t.height_cm,
        t.weight_kg,
        t.eye_color,
        t.hair_color,
        t.hair_type,
        t.skin_color,
        t.clothing_size,
        t.shoe_size,
        t.chest_size,
        t.waist_size,
        t.hip_size,
        t.beard,
        t.mustache,
        t.hijab,
        t.tattoos,
        t.scars,
        t.glasses,
        t.language_level,
        t.experience_years,
        t.previous_work,
        t.portfolio_links,
        t.photos,
        t.full_body_photos,
        t.video_intro,
        t.showreel_url,
        t.ready_to_travel,
        t.has_passport,
        t.has_car,
        t.work_outside_city,
        t.work_outside_country,
        t.is_verified,
        t.verified_by,
        t.last_activity,
        coalesce(tv.views, 0::bigint) as admin_views,
        p.phone as account_phone,
        p.approval_status,
        p.onboarding_status,
        p.onboarding_step,
        p.profile_completed_at,
        p.created_at as account_created_at,
        p.updated_at as account_updated_at,
        t.profile_visibility,
        t.base_country_code
      from public.talents t
      left join public.profiles p on p.user_id = t.user_id
      left join public.talent_views tv on tv.talent_id = t.id
    $view$;
  else
    execute $view$
      create or replace view public.admin_talent_profiles as
      select
        t.id,
        t.name_en,
        t.name_ar,
        t.category_en,
        t.category_ar,
        t.image_url,
        t.featured,
        t.created_at,
        t.sort_order,
        t.published,
        t.city_en,
        t.city_ar,
        t.age,
        t.height,
        t.bio_en,
        t.bio_ar,
        t.whatsapp,
        t.gallery_images,
        t.instagram,
        t.tiktok,
        t.snapchat,
        t.portfolio_url,
        t.status,
        t.slug,
        t.profile_completion,
        t.featured_until,
        t.availability_status,
        t.display_name_en,
        t.display_name_ar,
        t.verified,
        t.verified_at,
        t.user_id,
        t.city_slug,
        t.category_slug,
        t.gender,
        t.date_of_birth,
        t.nationality,
        t.languages,
        t.dialects,
        t.skills,
        t.nationality_slug,
        t.height_cm,
        t.weight_kg,
        t.eye_color,
        t.hair_color,
        t.hair_type,
        t.skin_color,
        t.clothing_size,
        t.shoe_size,
        t.chest_size,
        t.waist_size,
        t.hip_size,
        t.beard,
        t.mustache,
        t.hijab,
        t.tattoos,
        t.scars,
        t.glasses,
        t.language_level,
        t.experience_years,
        t.previous_work,
        t.portfolio_links,
        t.photos,
        t.full_body_photos,
        t.video_intro,
        t.showreel_url,
        t.ready_to_travel,
        t.has_passport,
        t.has_car,
        t.work_outside_city,
        t.work_outside_country,
        t.is_verified,
        t.verified_by,
        t.last_activity,
        0::bigint as admin_views,
        p.phone as account_phone,
        p.approval_status,
        p.onboarding_status,
        p.onboarding_step,
        p.profile_completed_at,
        p.created_at as account_created_at,
        p.updated_at as account_updated_at,
        t.profile_visibility,
        t.base_country_code
      from public.talents t
      left join public.profiles p on p.user_id = t.user_id
    $view$;
  end if;
end
$$;
