-- MLAMH Marketing Hub — Growth Operations foundation
-- No external publishing or outreach execution is enabled here.

create table if not exists public.marketing_contacts (
  id bigint generated by default as identity primary key,
  organization_name text,
  contact_name text,
  email text,
  phone text,
  linkedin_url text,
  website text,
  city text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_leads (
  id bigint generated by default as identity primary key,
  organization text not null,
  contact_id bigint references public.marketing_contacts(id) on delete set null,
  source text,
  channel text,
  owner text,
  stage text not null default 'new' check (stage in ('new','contacted','replied','qualified','brief_received','opportunity','won','lost')),
  lead_score integer check (lead_score is null or (lead_score between 0 and 100)),
  demand_signal text,
  opportunity_type text,
  city text,
  last_contact_at timestamptz,
  next_action_at timestamptz,
  brief_status text not null default 'none' check (brief_status in ('none','requested','partial','complete')),
  tags text[] not null default '{}',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_conversations (
  id bigint generated by default as identity primary key,
  channel text not null,
  external_thread_id text,
  contact_id bigint references public.marketing_contacts(id) on delete set null,
  lead_id bigint references public.marketing_leads(id) on delete set null,
  publisher_id bigint references public.publishers(id) on delete set null,
  talent_id bigint references public.talents(id) on delete set null,
  assigned_agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  status text not null default 'open' check (status in ('open','closed','archived')),
  stage text not null default 'new' check (stage in ('new','contacted','replied','qualified','brief_requested','brief_received','opportunity','won','lost')),
  last_message_at timestamptz,
  unread_count integer not null default 0 check (unread_count >= 0),
  sentiment text,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(channel, external_thread_id)
);

create table if not exists public.marketing_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.marketing_conversations(id) on delete cascade,
  direction text not null check (direction in ('inbound','outbound','internal')),
  sender text,
  content text not null,
  message_type text not null default 'text',
  external_message_id text,
  delivery_status text,
  received_at timestamptz,
  sent_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(conversation_id, external_message_id)
);

create table if not exists public.marketing_briefs (
  id bigint generated by default as identity primary key,
  project_type text,
  talent_type text check (talent_type is null or talent_type in ('actor','model','mixed')),
  talent_count integer check (talent_count is null or talent_count > 0),
  city text,
  location_notes text,
  shoot_date date,
  time_window text,
  requirements jsonb not null default '{}'::jsonb,
  compensation text,
  budget numeric check (budget is null or budget >= 0),
  contact_id bigint references public.marketing_contacts(id) on delete set null,
  source text,
  lead_id bigint references public.marketing_leads(id) on delete set null,
  conversation_id bigint references public.marketing_conversations(id) on delete set null,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  status text not null default 'draft' check (status in ('draft','partial','complete','converted','cancelled')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  objective text,
  status text not null default 'draft' check (status in ('draft','active','paused','completed','cancelled')),
  start_at timestamptz,
  end_at timestamptz,
  budget numeric check (budget is null or budget >= 0),
  target_audience jsonb not null default '{}'::jsonb,
  channels text[] not null default '{}',
  owner text,
  goal jsonb not null default '{}'::jsonb,
  utm_campaign text,
  created_by text,
  metrics jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_content (
  id bigint generated by default as identity primary key,
  title text,
  hook text,
  caption text,
  body text,
  cta text,
  content_type text not null,
  channel text,
  objective text,
  audience jsonb not null default '{}'::jsonb,
  campaign_id bigint references public.marketing_campaigns(id) on delete set null,
  agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  language text not null default 'ar' check (language in ('ar','en')),
  status text not null default 'idea' check (status in ('idea','draft','review','ready','approval','scheduled','published','measured','archived')),
  scheduled_at timestamptz,
  published_at timestamptz,
  external_post_id text,
  asset_references jsonb not null default '[]'::jsonb,
  utm jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_creatives (
  id bigint generated by default as identity primary key,
  content_id bigint references public.marketing_content(id) on delete cascade,
  campaign_id bigint references public.marketing_campaigns(id) on delete set null,
  type text not null,
  platform text,
  aspect_ratio text,
  status text not null default 'draft' check (status in ('draft','in_review','approved','archived')),
  storage_path text,
  preview_path text,
  created_by_agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  version integer not null default 1 check (version > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_outreach (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.marketing_leads(id) on delete cascade,
  template_key text,
  personalization jsonb not null default '{}'::jsonb,
  channel text not null,
  approval_id bigint references public.marketing_approvals(id) on delete set null,
  send_status text not null default 'draft' check (send_status in ('draft','waiting_approval','approved','scheduled','sent','failed','cancelled')),
  reply_status text not null default 'none' check (reply_status in ('none','replied','qualified','not_interested','blocked')),
  next_follow_up_at timestamptz,
  outcome text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_followups (
  id bigint generated by default as identity primary key,
  lead_id bigint references public.marketing_leads(id) on delete cascade,
  conversation_id bigint references public.marketing_conversations(id) on delete cascade,
  follow_up_at timestamptz not null,
  reason text,
  channel text,
  owner text,
  sequence_step integer not null default 1 check (sequence_step > 0),
  status text not null default 'scheduled' check (status in ('scheduled','due','completed','cancelled','failed')),
  previous_contact_at timestamptz,
  next_action text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_automation_rules (
  id bigint generated by default as identity primary key,
  name text not null,
  event_name text not null,
  conditions jsonb not null default '[]'::jsonb,
  actions jsonb not null default '[]'::jsonb,
  delay_seconds integer not null default 0 check (delay_seconds >= 0),
  status text not null default 'draft' check (status in ('draft','active','paused','archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_session_id text,
  source text,
  medium text,
  campaign text,
  content text,
  term text,
  referrer text,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.marketing_experiments (
  id bigint generated by default as identity primary key,
  name text not null,
  hypothesis text,
  metric text,
  variant_a jsonb not null default '{}'::jsonb,
  variant_b jsonb not null default '{}'::jsonb,
  start_at timestamptz,
  end_at timestamptz,
  status text not null default 'draft' check (status in ('draft','running','paused','completed','cancelled')),
  result jsonb not null default '{}'::jsonb,
  winner text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_alerts (
  id bigint generated by default as identity primary key,
  level text not null default 'info' check (level in ('info','warning','critical')),
  alert_type text not null,
  title text not null,
  body text,
  entity_type text,
  entity_id text,
  status text not null default 'open' check (status in ('open','acknowledged','resolved','dismissed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.marketing_playbooks (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  category text not null,
  content jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('draft','active','archived')),
  version integer not null default 1 check (version > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.marketing_tasks
  add constraint marketing_tasks_campaign_id_fkey foreign key (campaign_id) references public.marketing_campaigns(id) on delete set null,
  add constraint marketing_tasks_lead_id_fkey foreign key (lead_id) references public.marketing_leads(id) on delete set null,
  add constraint marketing_tasks_content_id_fkey foreign key (content_id) references public.marketing_content(id) on delete set null,
  add constraint marketing_tasks_conversation_id_fkey foreign key (conversation_id) references public.marketing_conversations(id) on delete set null;

create index if not exists marketing_leads_stage_score_idx on public.marketing_leads(stage, lead_score desc, created_at desc);
create index if not exists marketing_leads_next_action_idx on public.marketing_leads(next_action_at) where stage not in ('won','lost');
create index if not exists marketing_conversations_stage_last_message_idx on public.marketing_conversations(stage, last_message_at desc);
create index if not exists marketing_messages_conversation_created_idx on public.marketing_messages(conversation_id, created_at desc);
create index if not exists marketing_briefs_status_created_idx on public.marketing_briefs(status, created_at desc);
create index if not exists marketing_content_status_scheduled_idx on public.marketing_content(status, scheduled_at);
create index if not exists marketing_outreach_lead_status_idx on public.marketing_outreach(lead_id, send_status, created_at desc);
create index if not exists marketing_followups_due_idx on public.marketing_followups(status, follow_up_at);
create index if not exists marketing_events_name_occurred_idx on public.marketing_events(event_name, occurred_at desc);
create index if not exists marketing_events_attribution_idx on public.marketing_events(source, medium, campaign, occurred_at desc);
create index if not exists marketing_alerts_status_level_idx on public.marketing_alerts(status, level, created_at desc);

alter table public.marketing_contacts enable row level security;
alter table public.marketing_leads enable row level security;
alter table public.marketing_conversations enable row level security;
alter table public.marketing_messages enable row level security;
alter table public.marketing_briefs enable row level security;
alter table public.marketing_campaigns enable row level security;
alter table public.marketing_content enable row level security;
alter table public.marketing_creatives enable row level security;
alter table public.marketing_outreach enable row level security;
alter table public.marketing_followups enable row level security;
alter table public.marketing_automation_rules enable row level security;
alter table public.marketing_events enable row level security;
alter table public.marketing_experiments enable row level security;
alter table public.marketing_alerts enable row level security;
alter table public.marketing_playbooks enable row level security;

-- No authenticated/anonymous client policies are added here.
-- Admin server routes use the existing service-role client after requireAdminAccess().
