alter table public.casting_projects
  add column if not exists commercial_status text not null default 'lead'
    check (commercial_status in ('lead','proposal','won','lost','cancelled'));

create table if not exists public.casting_payments (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','paid','failed','refunded','cancelled')),
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'SAR',
  provider text,
  provider_reference text,
  paid_at timestamptz,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists casting_projects_commercial_status_idx
  on public.casting_projects(commercial_status);

create index if not exists casting_payments_project_idx
  on public.casting_payments(casting_project_id, created_at desc);

create unique index if not exists casting_payments_provider_reference_key
  on public.casting_payments(provider, provider_reference)
  where provider_reference is not null;

alter table public.casting_payments enable row level security;

comment on column public.casting_projects.quoted_amount is
  'Quoted pipeline value only; never treat as collected revenue.';

comment on table public.casting_payments is
  'Internal managed casting payment ledger. Collected revenue is derived only from status=paid records.';
