create table if not exists public.managed_casting_client_reviews (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  booking_id bigint not null references public.talent_bookings(id) on delete cascade,
  talent_id bigint not null references public.talents(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (casting_project_id, booking_id)
);

alter table public.managed_casting_client_reviews enable row level security;

create index if not exists idx_managed_casting_client_reviews_project
  on public.managed_casting_client_reviews(casting_project_id);
create index if not exists idx_managed_casting_client_reviews_talent
  on public.managed_casting_client_reviews(talent_id);
