create table if not exists public.talent_bookings (
  id bigint generated by default as identity primary key,
  application_id bigint not null unique references public.opportunity_applications(id) on delete cascade,
  conversation_id bigint not null unique references public.conversations(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  publisher_id bigint not null references public.publishers(id) on delete cascade,
  talent_id bigint not null references public.talents(id) on delete cascade,
  status text not null default 'proposed' check (status in ('proposed','changes_requested','confirmed','completed','cancelled')),
  work_date date,
  work_time time without time zone,
  work_duration text,
  location_text text,
  compensation_type text not null default 'negotiable' check (compensation_type in ('fixed','negotiable','unpaid')),
  compensation_amount numeric check (compensation_amount is null or compensation_amount >= 0),
  currency text not null default 'SAR' check (currency ~ '^[A-Z]{3}$'),
  notes text,
  talent_response_note text,
  proposed_by uuid references auth.users(id),
  proposed_at timestamptz not null default now(),
  talent_response_at timestamptz,
  confirmed_at timestamptz,
  publisher_completed_at timestamptz,
  talent_completed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists talent_bookings_publisher_id_idx on public.talent_bookings(publisher_id);
create index if not exists talent_bookings_talent_id_idx on public.talent_bookings(talent_id);
create index if not exists talent_bookings_status_idx on public.talent_bookings(status);

alter table public.talent_bookings enable row level security;

revoke all on public.talent_bookings from anon, authenticated;
grant select on public.talent_bookings to authenticated;

create policy "booking participants can read"
on public.talent_bookings
for select
to authenticated
using (
  exists (
    select 1
    from public.talents t
    where t.id = talent_bookings.talent_id
      and t.user_id = (select auth.uid())
  )
  or exists (
    select 1
    from public.publishers p
    join public.profiles pr on pr.id = p.profile_id
    where p.id = talent_bookings.publisher_id
      and pr.user_id = (select auth.uid())
  )
);

create table if not exists public.talent_booking_reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.talent_bookings(id) on delete cascade,
  reviewer_user_id uuid not null references auth.users(id) on delete cascade,
  reviewer_role text not null check (reviewer_role in ('publisher','talent')),
  rating integer not null check (rating between 1 and 5),
  professionalism integer check (professionalism is null or professionalism between 1 and 5),
  communication integer check (communication is null or communication between 1 and 5),
  punctuality integer check (punctuality is null or punctuality between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (booking_id, reviewer_user_id)
);

create index if not exists talent_booking_reviews_booking_id_idx on public.talent_booking_reviews(booking_id);

alter table public.talent_booking_reviews enable row level security;

revoke all on public.talent_booking_reviews from anon, authenticated;
grant select on public.talent_booking_reviews to authenticated;

create policy "booking participants can read reviews"
on public.talent_booking_reviews
for select
to authenticated
using (
  exists (
    select 1
    from public.talent_bookings b
    where b.id = talent_booking_reviews.booking_id
      and (
        exists (
          select 1 from public.talents t
          where t.id = b.talent_id and t.user_id = (select auth.uid())
        )
        or exists (
          select 1
          from public.publishers p
          join public.profiles pr on pr.id = p.profile_id
          where p.id = b.publisher_id and pr.user_id = (select auth.uid())
        )
      )
  )
);

comment on table public.talent_bookings is 'Post-acceptance booking workflow: proposal, talent confirmation, completion.';
comment on table public.talent_booking_reviews is 'Mutual reviews after a completed talent booking.';
