-- MLAMH Marketing Hub — Core OS foundation
-- Phase A only. No external channel execution is enabled by this migration.

create table if not exists public.marketing_agents (
  id text primary key,
  name text not null,
  role text not null,
  status text not null default 'idle'
    check (status in ('idle', 'working', 'waiting_approval', 'scheduled', 'paused', 'error')),
  autonomy_level text not null default 'auto'
    check (autonomy_level in ('auto', 'approval_required', 'ceo_only')),
  assigned_channels text[] not null default '{}',
  current_task_id bigint,
  last_action_at timestamptz,
  next_scheduled_task_at timestamptz,
  tasks_completed integer not null default 0 check (tasks_completed >= 0),
  tasks_failed integer not null default 0 check (tasks_failed >= 0),
  performance jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_tasks (
  id bigint generated by default as identity primary key,
  agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  task_type text not null,
  title text not null,
  objective text,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status text not null default 'queued' check (status in ('queued', 'scheduled', 'running', 'waiting_approval', 'completed', 'failed', 'cancelled')),
  channel text,
  source text,
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  approval_level text not null default 'auto' check (approval_level in ('auto', 'approval_required', 'ceo_only')),
  approval_status text not null default 'not_required' check (approval_status in ('not_required', 'pending', 'approved', 'rejected', 'cancelled', 'expired')),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  failed_at timestamptz,
  retry_count integer not null default 0 check (retry_count >= 0),
  parent_task_id bigint references public.marketing_tasks(id) on delete set null,
  campaign_id bigint,
  lead_id bigint,
  content_id bigint,
  conversation_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_tasks_approval_state_check check (
    (approval_level = 'auto' and approval_status = 'not_required') or
    (approval_level in ('approval_required', 'ceo_only') and approval_status in ('pending', 'approved', 'rejected', 'cancelled', 'expired'))
  )
);

alter table public.marketing_agents drop constraint if exists marketing_agents_current_task_id_fkey;
alter table public.marketing_agents add constraint marketing_agents_current_task_id_fkey foreign key (current_task_id) references public.marketing_tasks(id) on delete set null;

create table if not exists public.marketing_agent_activity (
  id bigint generated by default as identity primary key,
  agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  task_id bigint references public.marketing_tasks(id) on delete set null,
  action text not null,
  reason text,
  entity_type text,
  entity_id text,
  channel text,
  approval_status text,
  result jsonb not null default '{}'::jsonb,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.marketing_approvals (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.marketing_tasks(id) on delete cascade,
  requested_by_agent_id text references public.marketing_agents(id) on update cascade on delete set null,
  requested_by_user_id uuid references auth.users(id) on delete set null,
  approval_level text not null check (approval_level in ('approval_required', 'ceo_only')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'scheduled', 'cancelled', 'expired')),
  reason text,
  proposed_action jsonb not null default '{}'::jsonb,
  channel text,
  preview jsonb not null default '{}'::jsonb,
  risk_level text not null default 'low' check (risk_level in ('low', 'medium', 'high', 'critical')),
  expires_at timestamptz,
  decision_by_user_id uuid references auth.users(id) on delete set null,
  decision_note text,
  decided_at timestamptz,
  execute_after timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_approvals_decision_check check (
    (status in ('pending', 'scheduled') and decided_at is null) or
    (status in ('approved', 'rejected', 'cancelled', 'expired'))
  )
);

create unique index if not exists marketing_approvals_one_pending_per_task_idx on public.marketing_approvals (task_id) where status = 'pending';

create table if not exists public.marketing_integrations (
  id bigint generated by default as identity primary key,
  provider text not null unique,
  status text not null default 'setup_required' check (status in ('connected', 'setup_required', 'connecting', 'error', 'paused', 'limited')),
  capabilities jsonb not null default '{}'::jsonb,
  configuration_state jsonb not null default '{}'::jsonb,
  last_sync_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists marketing_tasks_status_scheduled_idx on public.marketing_tasks (status, scheduled_at);
create index if not exists marketing_tasks_agent_status_idx on public.marketing_tasks (agent_id, status, created_at desc);
create index if not exists marketing_tasks_parent_idx on public.marketing_tasks (parent_task_id);
create index if not exists marketing_agent_activity_agent_created_idx on public.marketing_agent_activity (agent_id, created_at desc);
create index if not exists marketing_agent_activity_task_idx on public.marketing_agent_activity (task_id, created_at desc);
create index if not exists marketing_approvals_status_created_idx on public.marketing_approvals (status, created_at desc);

alter table public.marketing_agents enable row level security;
alter table public.marketing_tasks enable row level security;
alter table public.marketing_agent_activity enable row level security;
alter table public.marketing_approvals enable row level security;
alter table public.marketing_integrations enable row level security;

-- No client policies are intentionally added in Phase A.
-- Admin access continues through authenticated server-side Admin routes + service-role client.

insert into public.marketing_agents (id, name, role, status, autonomy_level, assigned_channels)
values
  ('nora', 'Nora', 'AI Growth Director', 'idle', 'approval_required', array['internal']),
  ('salman', 'Salman', 'AI Opportunity Scout', 'idle', 'auto', array['research', 'internal']),
  ('layan', 'Layan', 'AI Acquisition Specialist', 'idle', 'approval_required', array['email', 'linkedin', 'whatsapp']),
  ('reem', 'Reem', 'AI Content Strategist', 'idle', 'approval_required', array['instagram', 'facebook', 'linkedin']),
  ('sarah', 'Sarah', 'AI Creative Producer', 'idle', 'approval_required', array['instagram', 'facebook', 'linkedin']),
  ('faisal', 'Faisal', 'AI Community & Talent Growth', 'idle', 'approval_required', array['instagram', 'facebook', 'whatsapp']),
  ('rakan', 'Rakan', 'AI Growth Analyst', 'idle', 'auto', array['internal'])
on conflict (id) do update set name = excluded.name, role = excluded.role, assigned_channels = excluded.assigned_channels, updated_at = now();

insert into public.marketing_integrations (provider, status, capabilities)
values
  ('meta', 'setup_required', '{"publishing": false, "insights": false, "comments": false, "messages": false, "webhooks": false}'::jsonb),
  ('whatsapp', 'setup_required', '{"inbound": false, "outbound": false, "templates": false, "delivery_status": false}'::jsonb),
  ('linkedin', 'setup_required', '{"publishing": false, "analytics": false, "interactions": false}'::jsonb),
  ('email', 'setup_required', '{"send": false, "receive": false, "tracking": false}'::jsonb),
  ('slack', 'setup_required', '{"internal_notifications": false}'::jsonb),
  ('notion', 'setup_required', '{"knowledge_sync": false}'::jsonb)
on conflict (provider) do nothing;
