-- MLAMH Marketing Hub — channel execution foundation
-- Provider secrets remain outside database tables.

create table if not exists public.marketing_channel_jobs (
  id bigint generated by default as identity primary key,
  content_id bigint references public.marketing_content(id) on delete cascade,
  task_id bigint references public.marketing_tasks(id) on delete set null,
  approval_id bigint references public.marketing_approvals(id) on delete set null,
  channel text not null,
  status text not null default 'draft'
    check (status in ('draft','waiting_approval','approved','scheduled','publishing','published','failed','cancelled')),
  scheduled_at timestamptz,
  started_at timestamptz,
  published_at timestamptz,
  external_post_id text,
  retry_count integer not null default 0 check (retry_count >= 0),
  last_error text,
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_event_id text,
  event_fingerprint text not null unique,
  event_type text,
  signature_verified boolean not null default false,
  processing_status text not null default 'received'
    check (processing_status in ('received','processing','processed','failed','ignored')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  payload jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);

create index if not exists marketing_channel_jobs_due_idx
  on public.marketing_channel_jobs(status, scheduled_at);
create index if not exists marketing_channel_jobs_channel_status_idx
  on public.marketing_channel_jobs(channel, status, created_at desc);
create index if not exists marketing_webhook_events_provider_received_idx
  on public.marketing_webhook_events(provider, received_at desc);

alter table public.marketing_channel_jobs enable row level security;
alter table public.marketing_webhook_events enable row level security;

-- No client policies. All execution/webhook processing is server-side only.
