-- Managed Casting replacement guarantee
-- Keeps an auditable trail when MLAMH replaces a selected/confirmed talent
-- with a reserve candidate without restarting the client selection flow.

alter table public.casting_shortlist
  drop constraint if exists casting_shortlist_status_check;

alter table public.casting_shortlist
  add constraint casting_shortlist_status_check
  check (status = any (array[
    'shortlisted'::text,
    'presented'::text,
    'reserved'::text,
    'selected'::text,
    'declined'::text,
    'withdrawn'::text,
    'replaced'::text
  ]));

create table if not exists public.managed_casting_replacements (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  casting_role_id bigint references public.casting_roles(id) on delete set null,
  replaced_shortlist_id bigint not null references public.casting_shortlist(id) on delete restrict,
  replacement_shortlist_id bigint not null references public.casting_shortlist(id) on delete restrict,
  replaced_application_id bigint not null references public.opportunity_applications(id) on delete restrict,
  replacement_application_id bigint not null references public.opportunity_applications(id) on delete restrict,
  replaced_talent_id bigint not null references public.talents(id) on delete restrict,
  replacement_talent_id bigint not null references public.talents(id) on delete restrict,
  replaced_booking_id bigint not null references public.talent_bookings(id) on delete restrict,
  replacement_booking_id bigint references public.talent_bookings(id) on delete set null,
  reason text,
  status text not null default 'replacement_started'
    check (status in ('replacement_started','replacement_confirming','replacement_confirmed','replacement_failed')),
  replaced_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (replaced_booking_id)
);

create index if not exists managed_casting_replacements_project_idx
  on public.managed_casting_replacements (casting_project_id, created_at desc);
create index if not exists managed_casting_replacements_replacement_shortlist_idx
  on public.managed_casting_replacements (replacement_shortlist_id);

alter table public.managed_casting_replacements enable row level security;

revoke all on table public.managed_casting_replacements from anon, authenticated;
revoke all on sequence public.managed_casting_replacements_id_seq from anon, authenticated;

grant all on table public.managed_casting_replacements to service_role;
grant usage, select on sequence public.managed_casting_replacements_id_seq to service_role;
