create table if not exists public.casting_projects (
  id bigint generated by default as identity primary key,
  publisher_id bigint references public.publishers(id) on delete set null,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  service_mode text not null default 'managed' check (service_mode in ('managed','self_service')),
  status text not null default 'new' check (status in ('new','qualified','proposal','awaiting_client','active','screening','shortlist_ready','client_review','completed','cancelled')),
  client_name text not null,
  company_name text,
  contact_email text,
  contact_phone text,
  project_title text not null,
  talent_type text not null check (talent_type in ('actor','model','mixed')),
  city text,
  required_count integer not null default 1 check (required_count between 1 and 1000),
  work_date date,
  budget text,
  brief text not null,
  requirements jsonb not null default '{}'::jsonb,
  internal_notes text,
  source text,
  package_code text check (package_code is null or package_code in ('starter','pro','custom')),
  quoted_amount numeric(12,2) check (quoted_amount is null or quoted_amount >= 0),
  currency text not null default 'SAR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists casting_projects_status_idx on public.casting_projects(status);
create index if not exists casting_projects_publisher_idx on public.casting_projects(publisher_id);
create index if not exists casting_projects_opportunity_idx on public.casting_projects(opportunity_id);

create table if not exists public.casting_shortlist (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  application_id bigint not null references public.opportunity_applications(id) on delete cascade,
  status text not null default 'shortlisted' check (status in ('shortlisted','presented','selected','declined','withdrawn')),
  rank integer check (rank is null or rank > 0),
  internal_notes text,
  client_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(casting_project_id, application_id)
);

create index if not exists casting_shortlist_project_idx on public.casting_shortlist(casting_project_id);

alter table public.casting_projects enable row level security;
alter table public.casting_shortlist enable row level security;

comment on table public.casting_projects is 'Managed and self-service casting project records. V1 internal/admin-first model.';
comment on table public.casting_shortlist is 'Shortlisted opportunity applications for managed casting projects.';