-- MLAMH Investor Relations AI
-- Server-only CRM for investor discovery, outreach approvals and Gmail threading.
-- No client policies are intentionally added; admin operations use the server-side service-role client.

create table if not exists public.investor_leads (
  id bigint generated by default as identity primary key,
  organization_name text not null,
  organization_type text not null default 'vc'
    check (organization_type in ('vc', 'angel', 'family_office', 'corporate_vc', 'strategic', 'accelerator', 'government', 'other')),
  website_url text,
  linkedin_url text,
  country_code text,
  city text,
  investment_stage text[] not null default '{}',
  sector_focus text[] not null default '{}',
  geography_focus text[] not null default '{}',
  cheque_min numeric,
  cheque_max numeric,
  cheque_currency text,
  thesis_summary text,
  fit_score smallint check (fit_score between 0 and 100),
  fit_rationale text,
  contact_name text,
  contact_role text,
  contact_email text,
  contact_linkedin_url text,
  status text not null default 'discovered'
    check (status in ('discovered', 'qualified', 'awaiting_approval', 'contacted', 'follow_up', 'meeting', 'interested', 'due_diligence', 'passed', 'rejected', 'archived')),
  source_urls jsonb not null default '[]'::jsonb,
  research_payload jsonb not null default '{}'::jsonb,
  last_researched_at timestamptz,
  last_contacted_at timestamptz,
  next_follow_up_at timestamptz,
  gmail_thread_id text,
  gmail_last_message_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists investor_leads_org_website_unique_idx
  on public.investor_leads (lower(organization_name), lower(coalesce(website_url, '')));
create index if not exists investor_leads_status_fit_idx
  on public.investor_leads (status, fit_score desc nulls last, created_at desc);
create index if not exists investor_leads_follow_up_idx
  on public.investor_leads (next_follow_up_at)
  where status in ('contacted', 'follow_up', 'interested');

create table if not exists public.investor_outreach (
  id bigint generated by default as identity primary key,
  investor_id bigint not null references public.investor_leads(id) on delete cascade,
  kind text not null default 'initial'
    check (kind in ('initial', 'follow_up', 'reply')),
  status text not null default 'draft'
    check (status in ('draft', 'pending_approval', 'approved', 'rejected', 'sending', 'sent', 'failed', 'cancelled')),
  to_email text not null,
  subject text not null,
  body_text text not null,
  rationale text,
  positioning_angle text,
  attachment_plan jsonb not null default '[]'::jsonb,
  ai_metadata jsonb not null default '{}'::jsonb,
  approval_requested_at timestamptz,
  approved_by_user_id uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  rejected_by_user_id uuid references auth.users(id) on delete set null,
  rejected_at timestamptz,
  rejection_note text,
  sent_at timestamptz,
  gmail_message_id text,
  gmail_thread_id text,
  send_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint investor_outreach_approval_consistency_check check (
    (status not in ('approved', 'sending', 'sent') or (approved_at is not null and approved_by_user_id is not null))
  )
);

create unique index if not exists investor_outreach_one_pending_per_investor_kind_idx
  on public.investor_outreach (investor_id, kind)
  where status = 'pending_approval';
create index if not exists investor_outreach_status_created_idx
  on public.investor_outreach (status, created_at desc);
create index if not exists investor_outreach_investor_created_idx
  on public.investor_outreach (investor_id, created_at desc);
create index if not exists investor_outreach_approved_by_user_idx
  on public.investor_outreach (approved_by_user_id);
create index if not exists investor_outreach_rejected_by_user_idx
  on public.investor_outreach (rejected_by_user_id);

create table if not exists public.investor_activity (
  id bigint generated by default as identity primary key,
  investor_id bigint not null references public.investor_leads(id) on delete cascade,
  outreach_id bigint references public.investor_outreach(id) on delete set null,
  action text not null,
  actor_type text not null default 'ai' check (actor_type in ('ai', 'admin', 'gmail', 'system')),
  actor_user_id uuid references auth.users(id) on delete set null,
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists investor_activity_investor_created_idx
  on public.investor_activity (investor_id, created_at desc);
create index if not exists investor_activity_outreach_idx
  on public.investor_activity (outreach_id);
create index if not exists investor_activity_actor_user_idx
  on public.investor_activity (actor_user_id);

create table if not exists public.investor_relations_settings (
  id smallint primary key default 1 check (id = 1),
  master_brief text not null default '',
  target_regions text[] not null default array['SA', 'AE', 'GCC'],
  target_stages text[] not null default array['pre_seed', 'seed'],
  target_sectors text[] not null default array['marketplace', 'media_tech', 'creator_economy', 'future_of_work', 'ai'],
  minimum_fit_score smallint not null default 70 check (minimum_fit_score between 0 and 100),
  follow_up_days integer[] not null default array[4, 8, 15],
  gmail_integration_provider text not null default 'investor_gmail',
  updated_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists investor_relations_settings_updated_by_user_idx
  on public.investor_relations_settings (updated_by_user_id);

insert into public.investor_relations_settings (id)
values (1)
on conflict (id) do nothing;

insert into public.marketing_agents (id, name, role, status, autonomy_level, assigned_channels)
values (
  'investor-relations-ai',
  'Investor Relations AI',
  'AI Investor Relations Manager',
  'idle',
  'approval_required',
  array['research', 'email', 'internal']
)
on conflict (id) do update
set name = excluded.name,
    role = excluded.role,
    autonomy_level = excluded.autonomy_level,
    assigned_channels = excluded.assigned_channels,
    updated_at = now();

insert into public.marketing_integrations (provider, status, capabilities, metadata)
values (
  'investor_gmail',
  'setup_required',
  '{"send": false, "read": false, "threading": false}'::jsonb,
  '{"purpose": "investor_relations"}'::jsonb
)
on conflict (provider) do nothing;

alter table public.investor_leads enable row level security;
alter table public.investor_outreach enable row level security;
alter table public.investor_activity enable row level security;
alter table public.investor_relations_settings enable row level security;

-- These tables contain investor/contact and outreach data. Keep them inaccessible
-- through anon/authenticated Data API roles; the admin server client uses service_role.
revoke all on table public.investor_leads from anon, authenticated;
revoke all on table public.investor_outreach from anon, authenticated;
revoke all on table public.investor_activity from anon, authenticated;
revoke all on table public.investor_relations_settings from anon, authenticated;
