create table if not exists public.homepage_hero (
  id bigint generated by default as identity primary key,

  eyebrow_ar text,
  eyebrow_en text,

  title_line_1_ar text,
  title_line_1_en text,

  title_line_2_ar text,
  title_line_2_en text,

  description_ar text,
  description_en text,

  primary_cta_label_ar text,
  primary_cta_label_en text,
  primary_cta_href text not null default '/join',

  secondary_cta_label_ar text,
  secondary_cta_label_en text,
  secondary_cta_href text not null default '/opportunities',

  stat_1_value text,
  stat_1_label_ar text,
  stat_1_label_en text,

  stat_2_value text,
  stat_2_label_ar text,
  stat_2_label_en text,

  stat_3_value text,
  stat_3_label_ar text,
  stat_3_label_en text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.homepage_hero_cards (
  id bigint generated by default as identity primary key,

  icon_key text not null check (
    icon_key in (
      'users',
      'building',
      'sparkles'
    )
  ),

  title_ar text not null,
  title_en text not null,

  description_ar text not null,
  description_en text not null,

  sort_order integer not null default 0,
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists homepage_hero_cards_sort_order_idx
  on public.homepage_hero_cards (sort_order);

drop trigger if exists homepage_hero_set_updated_at
  on public.homepage_hero;

create trigger homepage_hero_set_updated_at
before update on public.homepage_hero
for each row
execute function public.set_updated_at();

drop trigger if exists homepage_hero_cards_set_updated_at
  on public.homepage_hero_cards;

create trigger homepage_hero_cards_set_updated_at
before update on public.homepage_hero_cards
for each row
execute function public.set_updated_at();

alter table public.homepage_hero enable row level security;
alter table public.homepage_hero_cards enable row level security;

drop policy if exists "Public can read active homepage hero"
  on public.homepage_hero;

create policy "Public can read active homepage hero"
on public.homepage_hero
for select
using (is_active = true);

drop policy if exists "Public can read active homepage hero cards"
  on public.homepage_hero_cards;

create policy "Public can read active homepage hero cards"
on public.homepage_hero_cards
for select
using (is_active = true);

insert into public.homepage_hero (
  eyebrow_ar,
  eyebrow_en,

  title_line_1_ar,
  title_line_1_en,

  title_line_2_ar,
  title_line_2_en,

  description_ar,
  description_en,

  primary_cta_label_ar,
  primary_cta_label_en,
  primary_cta_href,

  secondary_cta_label_ar,
  secondary_cta_label_en,
  secondary_cta_href,

  stat_1_value,
  stat_1_label_ar,
  stat_1_label_en,

  stat_2_value,
  stat_2_label_ar,
  stat_2_label_en,

  stat_3_value,
  stat_3_label_ar,
  stat_3_label_en
)
select
  'منصة المواهب والفرص الإبداعية',
  'Creative Talent Ecosystem',

  'اكتشف المواهب المناسبة',
  'Discover the right talent',

  'واصنع فرصتك القادمة.',
  'and create what’s next.',

  'ملامح تربط المواهب، الشركات، والفرص الإبداعية في تجربة واحدة راقية وموثوقة.',
  'MLAMH connects talents, companies, and creative opportunities through one premium, trusted experience.',

  'ابدأ الآن',
  'Get Started',
  '/join',

  'استعرض الفرص',
  'Browse Opportunities',
  '/opportunities',

  '+1000',
  'موهبة',
  'Talents',

  '+200',
  'شركة',
  'Companies',

  '+500',
  'فرصة',
  'Opportunities'
where not exists (
  select 1 from public.homepage_hero
);

insert into public.homepage_hero_cards (
  icon_key,
  title_ar,
  title_en,
  description_ar,
  description_en,
  sort_order
)
select *
from (
  values
    (
      'users',
      'مواهب مختارة',
      'Curated Talents',
      'ملفات احترافية ومعارض أعمال واضحة.',
      'Professional profiles and rich portfolios.',
      10
    ),
    (
      'building',
      'شركات موثوقة',
      'Trusted Companies',
      'فرص حقيقية من جهات وشركات إبداعية.',
      'Real opportunities from creative teams.',
      20
    ),
    (
      'sparkles',
      'اكتشاف ذكي',
      'Smart Discovery',
      'رحلة أسهل للوصول للموهبة أو الفرصة المناسبة.',
      'A faster path to the right match.',
      30
    )
) as seed (
  icon_key,
  title_ar,
  title_en,
  description_ar,
  description_en,
  sort_order
)
where not exists (
  select 1 from public.homepage_hero_cards
);