create table if not exists public.footer_settings (
  id bigint generated by default as identity primary key,

  description_ar text,
  description_en text,

  email text,
  phone text,

  address_ar text,
  address_en text,

  copyright_ar text,
  copyright_en text,

  show_contact_info boolean not null default true,
  show_social_links boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.footer_links (
  id bigint generated by default as identity primary key,

  section text not null check (
    section in (
      'platform',
      'talent',
      'publisher',
      'legal',
      'social'
    )
  ),

  label_ar text not null,
  label_en text not null,

  href text not null,

  sort_order integer not null default 0,
  is_active boolean not null default true,
  open_in_new_tab boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists footer_links_section_idx
  on public.footer_links (section);

create index if not exists footer_links_sort_order_idx
  on public.footer_links (sort_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists footer_settings_set_updated_at
  on public.footer_settings;

create trigger footer_settings_set_updated_at
before update on public.footer_settings
for each row
execute function public.set_updated_at();

drop trigger if exists footer_links_set_updated_at
  on public.footer_links;

create trigger footer_links_set_updated_at
before update on public.footer_links
for each row
execute function public.set_updated_at();

alter table public.footer_settings enable row level security;
alter table public.footer_links enable row level security;

drop policy if exists "Public can read footer settings"
  on public.footer_settings;

create policy "Public can read footer settings"
on public.footer_settings
for select
using (true);

drop policy if exists "Public can read active footer links"
  on public.footer_links;

create policy "Public can read active footer links"
on public.footer_links
for select
using (is_active = true);

insert into public.footer_settings (
  description_ar,
  description_en,
  copyright_ar,
  copyright_en
)
select
  'منصة ملامح تجمع المواهب مع فرص الكاستنج والإنتاج.',
  'MLAMH connects talent with casting and production opportunities.',
  'جميع الحقوق محفوظة لمنصة ملامح.',
  'All rights reserved by MLAMH.'
where not exists (
  select 1 from public.footer_settings
);

insert into public.footer_links (
  section,
  label_ar,
  label_en,
  href,
  sort_order
)
select *
from (
  values
    ('platform', 'الرئيسية', 'Home', '/', 10),
    ('platform', 'الفرص', 'Opportunities', '/opportunities', 20),
    ('platform', 'المواهب', 'Talent', '/talent', 30),

    ('talent', 'إنشاء حساب موهبة', 'Join as Talent', '/auth/register', 10),
    ('talent', 'لوحة الموهبة', 'Talent Dashboard', '/talent-dashboard', 20),

    ('publisher', 'التسجيل كناشر', 'Join as Publisher', '/auth/register', 10),
    ('publisher', 'لوحة الناشر', 'Publisher Dashboard', '/publisher-dashboard', 20),
    ('publisher', 'إنشاء فرصة', 'Create Opportunity', '/opportunities/new', 30),

    ('legal', 'سياسة الخصوصية', 'Privacy Policy', '/privacy', 10),
    ('legal', 'الشروط والأحكام', 'Terms and Conditions', '/terms', 20)
) as seed (
  section,
  label_ar,
  label_en,
  href,
  sort_order
)
where not exists (
  select 1 from public.footer_links
);