-- Build 11 source migration only. Do not apply to production until privacy APIs/UI/storage policy are ready.

alter table public.talents
  add column if not exists profile_visibility text not null default 'public',
  add column if not exists photo_visibility text not null default 'public',
  add column if not exists allow_search_indexing boolean not null default true,
  add column if not exists allow_mlamh_share boolean not null default true,
  add column if not exists require_private_share_approval boolean not null default false;

alter table public.talents
  drop constraint if exists talents_profile_visibility_check,
  add constraint talents_profile_visibility_check
    check (profile_visibility in ('public', 'verified_publishers', 'private')),
  drop constraint if exists talents_photo_visibility_check,
  add constraint talents_photo_visibility_check
    check (photo_visibility in ('public', 'verified_publishers', 'private'));

comment on column public.talents.profile_visibility is
  'Talent profile discovery visibility: public, verified_publishers, private.';
comment on column public.talents.photo_visibility is
  'Talent image visibility. Private images must also be protected by API/storage policy before rollout.';
comment on column public.talents.allow_search_indexing is
  'Whether public SEO/indexing is allowed. Must be false for private profiles.';
comment on column public.talents.allow_mlamh_share is
  'Whether MLAMH may include the talent in controlled matching/shortlists subject to visibility policy.';
comment on column public.talents.require_private_share_approval is
  'When true, private media/profile sharing with a publisher requires explicit talent approval.';

create table if not exists public.talent_privacy_history (
  id bigint generated by default as identity primary key,
  talent_id bigint not null references public.talents(id) on delete cascade,
  user_id uuid,
  profile_visibility text not null,
  photo_visibility text not null,
  allow_search_indexing boolean not null,
  allow_mlamh_share boolean not null,
  require_private_share_approval boolean not null,
  source text not null default 'user',
  created_at timestamptz not null default now(),
  constraint talent_privacy_history_profile_visibility_check check (profile_visibility in ('public', 'verified_publishers', 'private')),
  constraint talent_privacy_history_photo_visibility_check check (photo_visibility in ('public', 'verified_publishers', 'private'))
);

alter table public.talent_privacy_history enable row level security;

-- Intentionally no broad client policy. Privacy history should be accessed through controlled server/admin APIs.
create index if not exists talent_privacy_history_talent_created_idx
  on public.talent_privacy_history(talent_id, created_at desc);
