create table if not exists public.managed_casting_invitations (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  casting_role_id bigint not null references public.casting_roles(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  talent_id bigint not null references public.talents(id) on delete cascade,
  invited_by uuid references auth.users(id) on delete set null,
  status text not null default 'sent'
    check (status in ('sent','viewed','applied','declined','expired')),
  message text,
  sent_at timestamptz not null default now(),
  viewed_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(opportunity_id, talent_id)
);

create index if not exists managed_casting_invitations_project_idx
  on public.managed_casting_invitations(casting_project_id, created_at desc);
create index if not exists managed_casting_invitations_role_idx
  on public.managed_casting_invitations(casting_role_id, created_at desc);
create index if not exists managed_casting_invitations_talent_idx
  on public.managed_casting_invitations(talent_id, created_at desc);
create index if not exists managed_casting_invitations_invited_by_idx
  on public.managed_casting_invitations(invited_by)
  where invited_by is not null;

alter table public.managed_casting_invitations enable row level security;

create or replace function public.sync_managed_casting_invitation_application()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.managed_casting_invitations
  set status = 'applied',
      applied_at = coalesce(applied_at, now()),
      updated_at = now()
  where opportunity_id = new.opportunity_id
    and talent_id = new.talent_id
    and status in ('sent','viewed');
  return new;
end;
$$;

revoke all on function public.sync_managed_casting_invitation_application()
  from public, anon, authenticated;
grant execute on function public.sync_managed_casting_invitation_application()
  to service_role;

drop trigger if exists opportunity_application_sync_managed_invitation
  on public.opportunity_applications;
create trigger opportunity_application_sync_managed_invitation
after insert on public.opportunity_applications
for each row execute function public.sync_managed_casting_invitation_application();

comment on table public.managed_casting_invitations is
  'MLAMH-managed sourcing invitations from internal talent supply to real managed casting opportunities.';
