create table if not exists public.casting_roles (
  id bigint generated by default as identity primary key,
  casting_project_id bigint not null references public.casting_projects(id) on delete cascade,
  opportunity_id bigint references public.opportunities(id) on delete set null,
  title text not null,
  title_en text,
  talent_type text not null check (talent_type in ('actor','model')),
  required_count integer not null default 1 check (required_count between 1 and 1000),
  description text,
  description_en text,
  requirements jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','active','screening','shortlist_ready','client_review','completed','cancelled')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (casting_project_id, opportunity_id)
);

create index if not exists casting_roles_project_idx
  on public.casting_roles(casting_project_id, sort_order, id);

create index if not exists casting_roles_opportunity_idx
  on public.casting_roles(opportunity_id)
  where opportunity_id is not null;

alter table public.casting_roles enable row level security;

alter table public.casting_shortlist
  add column if not exists casting_role_id bigint
  references public.casting_roles(id) on delete set null;

create index if not exists casting_shortlist_role_idx
  on public.casting_shortlist(casting_role_id)
  where casting_role_id is not null;
